### ISSUE TITLE
windows平台下ltp_test运行<arg />乱码

### ISSUE THREAD

**Issue by skyhiter** [HIT-SCIR/ltp#116]
ltp-3.3.0 release version 
cmake2.8.12.2+VS2010编译，运行ltp_test，输出中的arg 的type属性值是乱码。Linux编译运行是没问题的。
注：输入输出都已转换为utf-8无bom格式。
![win](https://cloud.githubusercontent.com/assets/3953193/8235862/16651696-1617-11e5-99ad-78569cb4fdfd.png)
![linux](https://cloud.githubusercontent.com/assets/3953193/8235872/22c82db0-1617-11e5-97dd-c3bea864364d.png)
谢谢~~

**Comment by Oneplus** [comment]
谢谢报bug，我们会尽快修复这个问题。

**Comment by HaomingFu** [comment]
我遇到的乱码问题更夸张。执行的命令是ltp_test.exe --input ltp_test.txt，运行环境是windows Visual Studio 2012；ltp_test.txt的内容是”爱上一匹野马，可我的家里没有草原。“，编码是utf-8 without BOM。运行结果是：
![qq 20150720114027](https://cloud.githubusercontent.com/assets/7111769/8771102/3f76c2dc-2eef-11e5-9e9d-395dc2b05bd2.jpg)

另外我运行example文件夹中的程序的时候也同样得到乱码：
![qq 20150720114027](https://cloud.githubusercontent.com/assets/7111769/8771118/808cfc5a-2eef-11e5-8d1b-af448c6435ba.jpg)

一楼报告中说arg type的值是乱码，而我的情况更严重，分词结果都是乱码。因为云平台的分词是完全正确的，所以出现这种问题我也十分意外。这个bug改怎么解决？谢了。

**Comment by Oneplus** [comment]
这个是windows terminal显示utf8的问题

**Comment by HaomingFu** [comment]
Thanks goes to Oneplus. 我后来写了一个测试程序，环境依然是Windows VS2012，文件编码是utf-8 without BOM。代码和运行结果如图示：
![qq 20150720175326](https://cloud.githubusercontent.com/assets/7111769/8773704/d9197182-2f08-11e5-81c4-005f627c3b30.jpg)
![qq 20150720175207](https://cloud.githubusercontent.com/assets/7111769/8773708/df82b218-2f08-11e5-9f97-b55e3ddf01bd.jpg)

我认为是从文件读入中文数据有问题，因为我在debug我们的ltp项目的时候发现下面的代码（cws_cmdline.cpp的116行）产生error：
   std::ifstream ifs(input.c_str());
   Error Code: Error reading characters of string.
尽管产生了上面的error，但程序还是继续跑完，运行结果就是出现我在3楼报告的乱码。

我百度了一下解决方法，但目前还是没有找到。

**Comment by Oneplus** [comment]
是这样，windows终端是gbk编码。所以从终端输入的(std:cin)和向终端输出的(std::cout)字符串都被解释成gbk了。

而ltp向终端输出了一个utf8编码的字符串，如果被解释成gbk的，就会显示乱码。

所以在windows终端下使用ltp工作的方法是将待分析的数据用utf8保存，然后用`<`重定向到标准输入，对于ltp的输出，用`>`重定向到标准输出。然后用能够显示utf8编码的文本编辑器，比如`notepad++`打开文件查看结果。

**Comment by Oneplus** [comment]
http://ltp.readthedocs.org/zh_CN/latest/ltptest.html#id8

**Comment by HaomingFu** [comment]
问题解决了。谢谢！

**Comment by liquor7** [comment]
请问你是怎么解决的？

**Comment by HaomingFu** [comment]
Oneplus已经给了回答了：http://ltp.readthedocs.org/zh_CN/latest/ltptest.html#id8

由于Windows终端采用gbk编码显示，运行 ltp_test 后会在终端输出乱码。您可以将标准输出重定向到文件，以UTF8方式查看文件，就可以解决乱码的问题。

**Comment by liquor7** [comment]
请问你有在VS下运行成功过吗？

**Comment by pheelyli** [comment]
windows 终端显示utf-8的问题，可以先输入指令：
chcp 65001
然后就可以正常用utf-8 了

**Comment by endyul** [comment]
@pheelyli 感谢反馈

**Comment by skyhiter** [comment]
问题已解决，故关闭改问题。
