### ISSUE TITLE
基于分词的语义角色标注系统

### ISSUE THREAD

**Issue by jackycaf** [HIT-SCIR/ltp#118]
Ltp 专家：
因为一直受到依存语法精度不高的困扰，希望考虑基于分词和词性标注的SRL开源系统。
不知Ltp是否有开源的类似系统 或者提供此方面有关详细的论文或书籍资料，
或者对学习此类系统给出一些评价和指导

多谢

**Comment by carfly** [comment]
抱歉，目前还没有此开发计划。如果想自己开发的话，可以参考：Chinese semantic role labeling with shallow parsing 
Weiwei Sun, Zhifang Sui, Meng Wang, and Xin Wang 
Empirical Methods in Natural Language Processing (EMNLP), 2009

**Comment by jackycaf** [comment]
多谢车老师，论文阅读中。争取能做一版，如果成功还要请车老师帮忙指导。

**Comment by jackycaf** [comment]
您推荐的论文已经看了，想用Penn TreeBank转换一个chunking库，但您推荐的论文没有给出nlp标注到chunking标注的转换规则，以及chunking标注的定义。听说哈工大这方面搞得比较早也比较成功。麻烦再给些指导或推荐些论文。

**Comment by carfly** [comment]
可以使用这个工具转换：https://github.com/rainarch/ChunkLinkCTB

**Comment by jackycaf** [comment]
车老师，
太感谢您了，方便的话能否给个mail。做好了把代码发给您，帮忙给看看。
邮箱：jackycaf@163.com
郑捷

**Comment by carfly** [comment]
car@ir.hit.edu.cn ，也欢迎你提交pull request给LTP。
