### ISSUE TITLE
新代码无法加载3.3.0版本分词模型问题

### ISSUE THREAD

**Issue by carfly** [HIT-SCIR/ltp#120]
新代码无法加载3.3.0版本分词模型问题

**Comment by Oneplus** [comment]
master开不了3.3.0的model，因为master修了一个模型签名的bug。

quick fix可以是：
- 用ltp release 3.3.0，加3.3.0的model
- 用master，开3.3.0的cws.model，把otner改成otcws。

**Comment by VinGorilla** [comment]
master上能尽快修复么？

**Comment by MingleiLI** [comment]
我用的就是ltp release 3.3.0，模型也是3.3.0。单独加载segmentor可以，但是加载pos的时候就会报错：
[INFO] 2015-11-23 11:12:07 Loading segmentor model from "../../ltp-3.3.0/ltp_data/cws.model" ...
[INFO] 2015-11-23 11:12:07 segmentor model is loaded.
[INFO] 2015-11-23 11:12:07 Loading postagger model from "../../ltp-3.3.0/ltp_data/cws.model" ...
而命令是：
../../ltp-3.3.0/bin/ltp_test --input ./data_source/event_nh_merge.txt --last-stage pos --segmentor-model ../../ltp-3.3.0/ltp_data/cws.model --postagger-model ../../ltp-3.3.0/ltp_data/pos.model --ner-model ../../ltp-3.3.0/ltp_data/ner.model --parser-model ../../ltp-3.3.0/ltp_data/parser.model --srl-data ../../ltp-3.3.0/ltp_data/srl/

**Comment by endyul** [comment]
fixed in https://github.com/HIT-SCIR/ltp/tree/v3.3.1-beta
