### ISSUE TITLE
语言云平台域名到期了

### ISSUE THREAD

**Issue by Truilin** [HIT-SCIR/ltp#121]
所以网站是无法访问了么 http://www.ltp-cloud.com/

**Comment by HaomingFu** [comment]
我可以访问，并且LTP在线分词也完全没问题。

**Comment by Truilin** [comment]
![ltp](https://cloud.githubusercontent.com/assets/7464189/8948960/e1b0198a-35df-11e5-9c63-b039b5176521.png)

换了几个浏览器都不行  难道是我ip的问题？

**Comment by HaomingFu** [comment]
![qq 20150729111315](https://cloud.githubusercontent.com/assets/7111769/8950706/8610ba18-35f7-11e5-8616-03e1c6f030fa.jpg)
我查了一下，发现这个域名应该是2025年才到期的。

**Comment by Truilin** [comment]
嗯  应该是电脑的问题  网站没有问题
