### ISSUE TITLE
model loading问题

### ISSUE THREAD

**Issue by Oneplus** [HIT-SCIR/ltp#125]
由于windows 32/64 linux 64对size_t的解释不一样，会出现windows 64下训练的模型无法使用的问题。

https://groups.google.com/forum/#!topic/ltp-cloud/7j3l2vlYVUA

在考虑使用boost::text_archive来解决这个问题。

- pro: text形式的模型，跨平台性根号
- con: 模型加载时间会增加

另一项跨平台的考虑是使用unordered_map或者google dense_hash代替smartmap。

暂时没想好是在3.3.1中fix这个bug还是等到3.3.2。

考虑到postagger和ner的模型要更新，我倾向于放到3.3.1一起更新了。

@carfly @endyul

**Comment by endyul** [comment]
[google/sparsehash](https://github.com/google/sparsehash)在OS X 10.10 make fail了，看issue各平台反馈的make问题很多。另外就是这项目4年没更新了。。。。还是用unordered_map吧

**Comment by Oneplus** [comment]
@endyul sparsehash可以head only的。make应该是make单元测试这些。你可以试试clone这个https://github.com/Oneplus/ZuoPar 看看能make过吗？

**Comment by Oneplus** [comment]
不过unordered_map性能差不多。
