### ISSUE TITLE
Win7 x64 VS2010 编译 LTP 3.3.0失败

### ISSUE THREAD

**Issue by scjiaer** [HIT-SCIR/ltp#138]
使用LTP 3.3.0版本测试了很多遍，CMake生成的只有 ALL_BUILD 和 ZERO_CHECK，使用VS2010编译总是出现错误。
第一个error出现在

    7>..\..\..\..\..\thirdparty\boost\libs\program_options\src\variables_map.cpp(103): error C2317: 在行“46”上开始的“try”块没有 catch 处理程序。

导致后面接连出现错误。

编译LTP 3.2.0一切正常。
平台： Win7 x64
编译器： VS 2010 专业版

**Comment by endyul** [comment]
fixed in https://github.com/HIT-SCIR/ltp/tree/v3.3.1-beta
