### ISSUE TITLE
ltp-test加载3.3.0模型出错

### ISSUE THREAD

**Issue by MingleiLI** [HIT-SCIR/ltp#140]
执行命令是：
../../ltp-3.3.0/bin/ltp_test --input ./data_source/event_nh_merge.txt --last-stage pos --segmentor-model ../../ltp-3.3.0/ltp_data/cws.model --postagger-model ../../ltp-3.3.0/ltp_data/pos.model --ner-model ../../ltp-3.3.0/ltp_data/ner.model --parser-model ../../ltp-3.3.0/ltp_data/parser.model --srl-data ../../ltp-3.3.0/ltp_data/srl/
但是报错是：
[INFO] 2015-11-23 11:12:07 Loading segmentor model from "../../ltp-3.3.0/ltp_data/cws.model" ...
[INFO] 2015-11-23 11:12:07 segmentor model is loaded.
[INFO] 2015-11-23 11:12:07 Loading postagger model from "../../ltp-3.3.0/ltp_data/cws.model" ...
Segmentation fault (core dumped)

我传的参数明明是pos.model啊，怎么报错是cws.model............

**Comment by MingleiLI** [comment]
没人回复吗？？？

**Comment by endyul** [comment]
暂时无法重现该问题，请问系统环境？

**Comment by Oneplus** [comment]
可能是3.3.0 release里有一处笔误把`postag_model`写成了`segment_model`，master上已经修复了这个问题。3.3.1的release会解决。

如果还想用3.3.0，直接的解决是把ltp_data放到ltp同目录下，然后不指定`postager-model`
