### ISSUE TITLE
请问这里的离线版本能使用语义依存分析吗？

### ISSUE THREAD

**Issue by bohaoist** [HIT-SCIR/ltp#141]
我想使用语义依存分析的功能，但是好像只有在线的API支持（http://www.ltp-cloud.com/demo/ ）
离线的model中没有说支持语义依存分析 http://ltp.readthedocs.org/zh_CN/latest/ltptest.html
请问除了用在线API之外，还有其他方式使用语义依存分析的功能吗？

**Comment by endyul** [comment]
现在的版本（3.3.0）还不支持
下个版本(3.3.1)会提供，预计下周会更新

**Comment by luochuwei** [comment]
请问什么时候可以支持语义依存分析的功能呢？

**Comment by renjhchn** [comment]
有计划哪个版本开始支持吗？

**Comment by GabrielLin** [comment]
同问。

**Comment by endyul** [comment]
抱歉 不能

发自我的 iPhone
