### ISSUE TITLE
请问，现在最新的 LTP 版本是 3.3.1，而模型文件的版本是 3.3.0，行不行呢？

### ISSUE THREAD

**Issue by chrysanthemum** [HIT-SCIR/ltp#142]
谢谢！

**Comment by endyul** [comment]
不行，3.3.1的模型格式和3.3.0不一样，还请先使用3.3.0的版本

@Oneplus 要不以后新开个dev分支吧，master上只发布新版本？

**Comment by Oneplus** [comment]
从3.3.1开始在development上开发吧。

2015-11-30 20:34 GMT+08:00 Oliver Xu <notifications@github.com>:

> 不行，3.3.1的模型格式和3.3.0不一样，还请先使用3.3.0的版本
>
> @Oneplus <https://github.com/Oneplus> 要不以后新开个dev分支吧，master上只发布新版本？
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HIT-SCIR/ltp/issues/142#issuecomment-160617345>.
>



-- 
Best regards!
- Yijia Liu (http://ir.hit.edu.cn/~yjliu)
- Static Oneplus (http://yjliu.net)

**Comment by chrysanthemum** [comment]
就再做个3.3.1的模型呗 ：）
