### ISSUE TITLE
Linux  master 3.3.1 模型3.3.0  测试词性标注时产生coredump

### ISSUE THREAD

**Issue by CodingLionDargon** [HIT-SCIR/ltp#146]
root@cpc:/opt/ltp/ltp/bin/examples# ./pos_cmdline --input ./input --postagger-model ../../ltp_data/pos.model 
*** Error in `./pos_cmdline': corrupted double-linked list: 0x00000000008bd520 ***
Aborted (core dumped)

root@cpc:/opt/ltp/ltp/bin/examples# cat input 
这是测试文本。

**Comment by endyul** [comment]
请用3.3.0 ltp
