### ISSUE TITLE
model加载失败， linux   master 3.3.1   model 3.3.0

### ISSUE THREAD

**Issue by CodingLionDargon** [HIT-SCIR/ltp#147]
root@cpc:/opt/ltp/ltp/bin# ./ltp_test --input ./input --postagger-model ../ltp_data/pos.model 
[INFO] 2016-01-08 10:48:57 Loading segmentor model from "ltp_data/cws.model" ...
[ERROR] 2016-01-08 10:48:57 /opt/ltp/ltp/src/ltp/LTPResource.cpp: line 50: LoadSegmentorResource(): Failed to load segmentor model
[ERROR] 2016-01-08 10:48:57 /opt/ltp/ltp/src/ltp/Ltp.cpp: line 76: load(): in LTP::wordseg, failed to load segmentor resource
Failed to load LTP

**Comment by Oneplus** [comment]
`ltp_test`是pipeline程序，也就是说：先进行分词，再进行词性标注。所以需要同时提供--segmentor-model的地址。
