### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by cindymuji** [HIT-SCIR/ltp#148]
![image](https://cloud.githubusercontent.com/assets/15852976/12263200/307c4e42-b968-11e5-89a7-f749930463cf.png)
运行到句法分析部分时出现如上错误。

**Comment by endyul** [comment]
能否提供一下你的代码

**Comment by cindymuji** [comment]
是不是处理的数据太多了？

**Comment by endyul** [comment]
是否在循环里load了模型

**Comment by cindymuji** [comment]
嗯，多语句循环输入到load方法里了。

**Comment by endyul** [comment]
模型只需要load一次即可，不要放到循环里

**Comment by cindymuji** [comment]
好的，谢谢
