### ISSUE TITLE
编译错误：No rule to make target 'src/unittest/CMakeFiles/model_validation.dir/depend'。

### ISSUE THREAD

**Issue by zhoususheng** [HIT-SCIR/ltp#149]
不论3.3.0还是3.3.1版本，都产生这样的错误。
版本信息：g++ (Ubuntu 5.2.1-22ubuntu2) 5.2.1 20151010
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

系统是64位

![2016-01-17 21-29-20](https://cloud.githubusercontent.com/assets/9567903/12377698/65a798b8-bd61-11e5-9232-363e372b6677.png)
![2016-01-17 22-13-53](https://cloud.githubusercontent.com/assets/9567903/12377896/a53e9fa2-bd67-11e5-8328-01a9859729d6.png)

**Comment by endyul** [comment]
可能是由g++版本引起的，我今天看一下此问题。
如果条件允许的话可以先尝试使用4.x版本的g++编译

**Comment by zhoususheng** [comment]
谢谢回复，我试过4.8版本的，也是这样的错误。

**Comment by Oneplus** [comment]
fixed in 982b132
