### ISSUE TITLE
3.3 model cws.model 不能加载

### ISSUE THREAD

**Issue by limisi** [HIT-SCIR/ltp#150]
when run ./bin/examples/cws_cmdline --segmentor-model ltp-data/cws.model --input my.txt, I get no outputs
the ltp_data/cws.model didn't load success, and then return 
at src/console/cws_cmdline.cpp:111(version:eaa0b7d ).

the md5sum check file is ok.

**Comment by endyul** [comment]
用的是tag 3.3.0的ltp吗？

**Comment by limisi** [comment]
是啊， 我在 代码里边 调试了，
例如 cws.model , 3.3 的 begin 是 otner，
但是代码里边 要 判断 model_header == "otcws"
还有 labels, space,  param 来读模型的时候，三个的格式都对齐不了，
例如 space 的 featurespaceh: 210: 代码里边是 32 bit的， 但是我在 cws.model 里边发现是 64bit的，
    ifs.read(reinterpret_cast<char *>(&_offset), sizeof(uint32_t));
    ifs.read(chunk, 4);
    ifs.read(reinterpret_cast<char *>(&sz), sizeof(uint32_t));
    ifs.read(chunk, 4);
  做了好几个修改都无法顺利运行，模型是用同一份代码跑的吗？开头的标识符号都没匹配到，太坑了。

**Comment by limisi** [comment]
是否代码 32位和 64位的model 不同？

**Comment by endyul** [comment]
#125 will be fixed in 3.3.1

**Comment by endyul** [comment]
fixed in https://github.com/HIT-SCIR/ltp/tree/v3.3.1-beta
