### ISSUE TITLE
速度评测

### ISSUE THREAD

**Issue by chivychao** [HIT-SCIR/ltp#156]
根据wiki上的数据，分词模块的运行速度是392.5K/sec。（http://ltp.readthedocs.org/zh_CN/latest/theory.html#id9）
但我自己实测下来，平均速度才是140K/sec啊。。。
测的是这个：ltp_master/tools/train/otcws

请问官方给的数字是要在怎样的情况下才能达到呢？

**Comment by endyul** [comment]
和测试机配置有关

**Comment by endyul** [comment]
和测试机配置有关

**Comment by chivychao** [comment]
>和测试机配置有关
我的评测环境是一台四路服务器，CPU是E7-4830v2
>计算速度的时候是否扣除了模型加载的时间
评测时，仅计算读取文本到文本处理结束的所花费的时间，不包含模型的读取与释放

**Comment by endyul** [comment]
那应该不会差这么多，单位是byte

**Comment by endyul** [comment]
@Oneplus 我重新跑一下3.3.1的benchmark
