### ISSUE TITLE
建议修改这个变量名

### ISSUE THREAD

**Issue by zhoususheng** [HIT-SCIR/ltp#157]
我用gcc5出现如下错误，希望可以修改相应的变量名。
![2016-02-07 01-37-48](https://cloud.githubusercontent.com/assets/9567903/12868152/9f897fd0-cd3b-11e5-8f39-d573d5ef6f32.png)

**Comment by Oneplus** [comment]
@endyul 梓翔，这个bug是由于boost 1.57.0不兼容gcc5吗？如果是什么时候升级一下ship的boost？

**Comment by endyul** [comment]
我有猜测但是还没有找到证据，上次尝试用了下1.60会产生其它的问题。另外使用vs2015编译也不能通过。我过几天再统一解决一下

**Comment by Oneplus** [comment]
查了编译log，应该是googletest framework引入的。想到一个解决方法就是在gcc5上不编译unittest模块。

**Comment by Oneplus** [comment]
see commit #982b13270f8d18b3e3ecfca2ba4296d941640b02
