### ISSUE TITLE
测试无法运行

### ISSUE THREAD

**Issue by taozhijiang** [HIT-SCIR/ltp#158]
user@gentoo ltp % cat input
这 是 测试 文本 。%                                                                                                                                          user@gentoo ltp % cat input | ./bin/examples/pos_cmdline --postagger-model ./ltp_data/pos.model
*** Error in `./bin/examples/pos_cmdline': corrupted double-linked list: 0x0000000000692f80 ***
^C
user@gentoo ltp %

然后一直没有反应
我用的3.3.0版本的
git checkout -b v3.3.0 
语言模型也是下载的3.3.0的

**Comment by endyul** [comment]
cannnot reproduce this issue，please try 3.3.1 instead
close temporarily
