### ISSUE TITLE
CI on Windows

### ISSUE THREAD

**Issue by endyul** [HIT-SCIR/ltp#162]
Travis CI目前不支持Windows。会调研一下[AppVeyor](https://www.appveyor.com)，支持Windows，看到有人用其generate binary wheels for PyPI

ref: 
https://en.wikipedia.org/wiki/Comparison_of_continuous_integration_software
http://tomassetti.me/continous-integration-on-linux-and-windows-travis-and-appveyor/

**Comment by dontpanic92** [comment]
微软有很多项目也用的AppVeyor 比如
https://github.com/BVLC/caffe/tree/windows
https://github.com/Microsoft/vscode

**Comment by Oneplus** [comment]
implemented in 836ab28

@endyul 只做了vs13的，可以考虑一下vs15的compile matrix。
