### ISSUE TITLE
./ner: error while loading shared libraries: libner.so.0.0.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by RominYue** [HIT-SCIR/ltp#163]
ltp版本：3.3.1
Hello,编译成功，但是在运行的时候发现动态库找不到。但是我把../lib/\*.so全删掉只用../lib/\*.a静态库的时候可以编译运行。请问：
(1)错误的原因是什么
(2)只用.a静态库会有什么问题么

**Comment by RominYue** [comment]
update:查了一下当有重名动态库和静态库，运行时优先查找动态库，查找路径是/usr/lib/,/lib,并不会检查编译时指定链接的路径？所以才会找不到？

**Comment by endyul** [comment]
1. gcc链接时优先使用动态库，运行时你的`LD_LIBRARY_PATH`没有加入ltp的lib目录，所以导致运行时找不到动态库；你删掉*.so之后，gcc链接时使用了静态库，运行时不依赖于.so。
2. 相当于静态编译，二进制文件体积变大，没有什么问题
3. 不是**运行时**优先查找动态库，是**编译时**优先查找动态库。运行时还需要再配置`LD_LIBRARY_PATH`环境变量加入lib目录才能找到需要的动态库

**Comment by RominYue** [comment]
谢谢，惭愧有些概念还没有搞明白。
