### ISSUE TITLE
publishing artifacts by AppVeyor

### ISSUE THREAD

**Issue by endyul** [HIT-SCIR/ltp#167]
AppVeyor 似乎可以打包并发布编译好的二进制文件

http://www.appveyor.com/docs/packaging-artifacts
http://www.appveyor.com/docs/deployment/github

**Comment by carfly** [comment]
好啊！

**Comment by Oneplus** [comment]
artifacts的部分我搞定了。

https://ci.appveyor.com/project/Oneplus/ltp

每个build job都会产生artifact。
