### ISSUE TITLE
ltp master 或者ltp 3.3.1 加载 ltp model 出错 srl resource

### ISSUE THREAD

**Issue by GZJackCai** [HIT-SCIR/ltp#169]
ltpresource.cpp:line 242:  loadSRLResource  to load srl resource

**Comment by endyul** [comment]
请提供模型版本、系统信息

**Comment by GZJackCai** [comment]
系统：mac 10.11 模型版本3.3.1。 master 和3.1版本都试过了

**Comment by endyul** [comment]
我这里无法复现。请提供一下能够复现的命令或者代码

**Comment by GZJackCai** [comment]
./ltp_test --threads 3 --segmentor-model /Users/jack/Documents/ltp_data/cws.model --postagger-model /Users/jack/Documents/ltp_data/pos.model --ner-model /Users/jack/Documents/ltp_data/ner.model --parser-model /Users/jack/Documents/ltp_data/parser.model --srl-data /Users/jack/Documents/ltp_data/srl_data/

**Comment by carfly** [comment]
参数中的：ltp_data/srl_data/ 应该是 ltp_data/srl/

**Comment by GZJackCai** [comment]
哦，是的，非常感谢。可以了。
