### ISSUE TITLE
虚拟机下CentOS6.5下ltp_server无法开启

### ISSUE THREAD

**Issue by lisisong** [HIT-SCIR/ltp#171]
[root@CentOS01 bin]# ./ltp_server --port 3434
[INFO] 2016-06-20 19:22:50 Loading segmentor model from "ltp_data/cws.model" ...
[INFO] 2016-06-20 19:22:59 segmentor model is loaded.
[INFO] 2016-06-20 19:22:59 Loading postagger model from "ltp_data/pos.model" ...
[INFO] 2016-06-20 19:23:20 postagger model is loaded
[INFO] 2016-06-20 19:23:20 Loading NER resource from "ltp_data/ner.model"
[INFO] 2016-06-20 19:23:21 NER resource is loaded.
[INFO] 2016-06-20 19:23:21 Loading parser resource from "ltp_data/parser.model"
[INFO] 2016-06-20 19:23:39 parser is loaded.
[INFO] 2016-06-20 19:23:39 Loading SRL resource from "ltp_data/srl/"
[INFO] 2016-06-20 19:23:41 SRL resource is loaded.

**Comment by lisisong** [comment]
加载到 SRL resource 后面就不执行了

**Comment by endyul** [comment]
这样就表示server已经开启，waiting request中
