### ISSUE TITLE
pyltp的ner功能和ner_cmdline不允许读入空行，会报段错误？

### ISSUE THREAD

**Issue by eecrazy** [HIT-SCIR/ltp#173]
3.3.1版本的pyltp的ner功能和ner_cmdline不允许读入空行，会报段错误。但是ner依赖的词性标注结果中默认句子间有空行，这样pos_cmdline的结果不能直接输出给ner_cmdline。只需判断一下是否空行就好了，算个bug吧。。   不知道3.3.2解决没？

**Comment by Nick-Alam** [comment]
+ 1, 缺少空行判断，报```段错误```
