### ISSUE TITLE
实体识别

### ISSUE THREAD

**Issue by rulongchen** [HIT-SCIR/ltp#178]
1. 实体识别的时候，比如公司名以“集团公司”结尾，则识别不出，如果改成集团有限公司则可以识别，比如中国移动通讯集团公司，识别不出
2. 公司名好像对有限公司比较敏感，其他类型的公司识别率比较低，比如“国创开元股权投资基金（有限合伙）”，这是一个公司名，类型为有限合伙公司，无法识别。对于一些公司名包含“（北京）”之类的识别率也比较低，比如“阿里巴巴（中国）网络技术有限公司”

**Comment by carfly** [comment]
你提的问题非常好！由于训练数据比较旧，造成了我们实体识别模型现存的问题，以后我们会增加相应的数据，提升识别准确率。
