### ISSUE TITLE
训练 nndepparser时，下面几个参数有哪个必需提供，哪个是option的

### ISSUE THREAD

**Issue by jackycaf** [HIT-SCIR/ltp#179]
options:
  --model arg               the path to the model. 
  --embedding arg           the path to the embedding file.  
  --reference arg           the path to the reference file. 
  --development arg         the path to the development file.
最好能给个命令行的例子。多谢车大神

**Comment by endyul** [comment]
./nndepparser learn -h 没有default值的参数是必须的： model、embedding、reference、development
Regards --
On 周一, 8月 1, 2016 at 14:53, jack,zheng <notifications@github.com> wrote:
options:
--model arg the path to the model. （必需给定）
--embedding arg the path to the embedding file.

--reference arg the path to the reference file.
--development arg the path to the development file.

**Comment by jackycaf** [comment]
Oliver Xu, 下面四个都是必选项
model: 输出模型的路径
embedding: word-embedding 词向量文件
reference: 训练集（用于训练的依存树库）
development: 开发集（容量是10%~20%训练集）
我这么理解对吗

**Comment by endyul** [comment]
是的

Regards --
On 周四, 8月 4, 2016 at 09:23, jack,zheng <notifications@github.com> wrote:
Oliver Xu, 下面四个都是必选项
model: 输出模型的路径
embedding: word-embedding 词向量文件
reference: 训练集（用于训练的依存树库）
development: 开发集（容量是10%~20%训练集）
我这么理解对吗

**Comment by jackycaf** [comment]
Oliver Xu,
 下面四个都是必选项
model: 输出模型的路径
embedding: word-embedding 词向量文件
reference: 训练集（用于训练的依存树库）
development: 开发集（容量是10%~20%训练集）
我这么理解对吗






At 2016-08-01 14:55:40, "Oliver Xu" <notifications@github.com> wrote:
./nndepparser learn -h 没有default值的参数是必须的： model、embedding、reference、development
Regards --
On 周一, 8月 1, 2016 at 14:53, jack,zheng <notifications@github.com> wrote:
options:
--model arg the path to the model. （必需给定）
--embedding arg the path to the embedding file.

--reference arg the path to the reference file.
--development arg the path to the development file.
