### ISSUE TITLE
语义依存模块的源代码什么时候发布

### ISSUE THREAD

**Issue by jackycaf** [HIT-SCIR/ltp#180]
语义依存模块的源代码什么时候发布

**Comment by carfly** [comment]
目前还没有计划……

**Comment by jackycaf** [comment]
目前的精度和召回都是多少，我看文档中没有说明

**Comment by jackycaf** [comment]
写一篇论文要用 ，麻烦能提供一些更详细的资料吗？
比如使用的算法，训练语料，标注样本什么的

**Comment by jackycaf** [comment]
多谢车大神

**Comment by FannyChung** [comment]
请问在哪里有具体的语义依存关系标签的介绍呢？感觉官网的intro里面（https://www.ltp-cloud.com/intro/#sdp_how）写的不够具体啊
