### ISSUE TITLE
实体识别怎么在没有B的情况下就出现了I？

### ISSUE THREAD

**Issue by rulongchen** [HIT-SCIR/ltp#181]
测试文本如下：
[15.txt](https://github.com/HIT-SCIR/ltp/files/417406/15.txt)
输出结果
![image](https://cloud.githubusercontent.com/assets/18520540/17653342/7585e6c6-62c6-11e6-9373-94a0261539e8.png)

**Comment by rulongchen** [comment]
在不分句的情况下，直接做seg，postag，和ner

**Comment by endyul** [comment]
可能是换行符的问题，建议分句后重试。

![2016-08-19 14 55 53](https://cloud.githubusercontent.com/assets/1056031/17801478/fb7697ae-661c-11e6-9b0f-54dba4810c08.png)

**Comment by endyul** [comment]
similar problem
https://github.com/HIT-SCIR/ltp4j/issues/12

**Comment by rulongchen** [comment]
能不能不做分句？从Java调的ltp，如果做了分句相当于多次调用，会不会有性能问题？
