### ISSUE TITLE
Memory leak in  NamedEntityRecognizer

### ISSUE THREAD

**Issue by rudaoshi** [HIT-SCIR/ltp#184]
global_con allocated without free.

move the free code from NamedEntityRecognizerFrontend to NamedEntityRecognizer.

**Comment by heartszhang** [comment]
PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
11822 xxxx      20   0 6573236 5.902g   5020 S  73.3 76.6  22:21.86 ltp_server

我觉得这个可能不算正常

**Comment by endyul** [comment]
@heartszhang 这是只进行ner的结果吗？请求量大概是多少？

**Comment by heartszhang** [comment]
之前的issue被删掉了，所以我在这里贴出来。t=ws,pos,ner 。这个5G不算什么，我的另一台机器跑到过40G。
另外，服务端TIME_WAIT太多了。我觉得是不是可以打开KEEP-ALIVE。有时候我能看到一万好几个TIME_WAIT。
5G的请求量不大，百万次

**Comment by heartszhang** [comment]
ltp_server:288 new出来的sentence在 318行return前没有释放，324行也一样

xml4nlp也不是在每个return前都有CleanDOM, 不知道这个是不是有影响

实际上，我把segment_dll.so.xxx分离出来了，自己封装一个webserver，在百万次请求上看不出泄漏

**Comment by endyul** [comment]
@heartszhang 谢谢，应该是这个原因
