### ISSUE TITLE
Memory leak in SRL

### ISSUE THREAD

**Issue by rudaoshi** [HIT-SCIR/ltp#185]
memory leaks all over the module. 

please check it carefully. 

eg:

SRLBaselineExt
DepSRL::GetSRLResult

**Comment by rudaoshi** [comment]
some of them may not result in real memory leak. but delete is far away from the new operator, and there are some workflow that delete is not called.

**Comment by heartszhang** [comment]
我在公司生产环境部署了一个ltp_server，一晚上跑了几千万次分词以后，内存使用涨到了40多G，剩下的时间就是等ltp_server coredump 了。因为内存泄漏问题，我们现在不得不放弃使用ltp

**Comment by rudaoshi** [comment]
当前版本的ltp应该没有明显的大规模内存泄漏问题。我使用python接口，跑几百万数据没有明显的内存问题。
