### ISSUE TITLE
如何自定义分词模型，具体命令是什么，能否给个实例？

### ISSUE THREAD

**Issue by struggleToDawn** [HIT-SCIR/ltp#188]

**Comment by endyul** [comment]
请参考文档
http://ltp.readthedocs.io/zh_CN/latest/theory.html#customized-cws-reference-label

**Comment by struggleToDawn** [comment]
我在服务器端执行如下命令 :  ./tools/train/otcws learn --model ttt --reference ./tools/train/thefile.txt --dump-details true 
--reference ./tools/train/thefile.txt 是我想添加的医学专用名词  
执行之后报错：
[INFO] 2016-10-24 17:41:10 training: 40% (1656) instances is trained.
[INFO] 2016-10-24 17:41:10 training: 50% (2070) instances is trained.
[INFO] 2016-10-24 17:41:10 training: 60% (2484) instances is trained.
[INFO] 2016-10-24 17:41:11 training: 70% (2898) instances is trained.
[INFO] 2016-10-24 17:41:11 training: 80% (3312) instances is trained.
[INFO] 2016-10-24 17:41:11 training: 90% (3726) instances is trained.
[INFO] 2016-10-24 17:41:11 training: 100% (4140) instances is trained.
[INFO] 2016-10-24 17:41:11 trace: 4148 instances is trained.
[ERROR] 2016-10-24 17:41:11 /ltp/src/segmentor/segmentor_frontend.cpp: line 421: evaluate(): Failed to open holdout file.
[INFO] 2016-10-24 17:41:11 Training iteration #10
[INFO] 2016-10-24 17:41:11 training: 10% (414) instances is trained.
[INFO] 2016-10-24 17:41:11 training: 20% (828) instances is trained.
[INFO] 2016-10-24 17:41:11 training: 30% (1242) instances is trained.
[INFO] 2016-10-24 17:41:11 training: 40% (1656) instances is trained.
[INFO] 2016-10-24 17:41:11 training: 50% (2070) instances is trained.
[INFO] 2016-10-24 17:41:11 training: 60% (2484) instances is trained.
[INFO] 2016-10-24 17:41:11 training: 70% (2898) instances is trained.
[INFO] 2016-10-24 17:41:11 training: 80% (3312) instances is trained.
[INFO] 2016-10-24 17:41:11 training: 90% (3726) instances is trained.
[INFO] 2016-10-24 17:41:11 training: 100% (4140) instances is trained.
[INFO] 2016-10-24 17:41:11 trace: 4148 instances is trained.
[ERROR] 2016-10-24 17:41:11 /ltp/src/segmentor/segmentor_frontend.cpp: line 421: evaluate(): Failed to open holdout file.

**Comment by endyul** [comment]
holdout file（开发集数据）在训练过程中是必须的
另外，如果你的thefile是词典类型的话，是不能够用来做训练数据的。自定义词典请使用分词套件中的`--segmentor-lexicon` 参数指定

**Comment by struggleToDawn** [comment]
老师，您好。我刚上研究生，刚接触自然语言处理，实在是小白。有些细节还是不清楚，希望老师详细介绍下。 我的需求是这样，就是想在原来的分词模型中添加几个特定的分词。 向jieba分词load_userdict("thefile.txt") 这样，jieba分词加载我的字典后便可以识别我想要分词。
我想知道哈工大ltp具体 具体 具体哪些东西是需要准备的，应该执行哪些命令，具体步骤是什么。

 
otcws这个用法参数中没有holdout file  为什么就成了必须的？ 我怎么加上去？
usage: ./otcws learn <options>

options:
  --baseline-model arg         The baseline model, which should be saved with
                               --dump-details options.
  --model arg                  The prefix of the model file, model will be
                               stored as model.$iter.
  --reference arg              The path to the reference file.
  --development arg            The path to the development file.
  --algorithm arg              The learning algorithm
                                - ap: averaged perceptron
                                - pa: passive aggressive [default]
  --max-iter arg               The number of iteration [default=10].
  --rare-feature-threshold arg The threshold for rare feature, used in model
                               truncation. [default=0]
  -h [ --help ]                Show help information

**Comment by endyul** [comment]
`otcws learn`是机器学习中的训练器，用来学习模型。您可以查阅一下机器学习的基本框架，以及训练集、开发集、测试集的相关概念。

jieba的`load_userdict`不是训练器，而是提供词典来做词典特征。ltp中也提供了类似的接口，例如`./cws_cmdline`分词命令行中的`--segmentor-lexicon`参数

从你的需求来看，您应该使用`cws_cmdline`中的`--segmentor-lexicon`来指定词典文件，而不是使用`otcws`来训练模型

另外，`otcws learn`中的`--development`参数就是用来指定holdout file

**Comment by struggleToDawn** [comment]
谢谢，我有试过用python版api指定--segmentor-lexicon参数，发现分词并未按照我指定的词来。 最后我是用jiaba分词并将加重我的词频进行切割，然后把切好的词再给ltp进行分析处理。

**Comment by endyul** [comment]
由于算法的原因，不会强制按照用户的词典进行切分。我们未来会考虑一下是否加重用户词典的权重
