### ISSUE TITLE
浏览器访问本地服务的url

### ISSUE THREAD

**Issue by lifeng1989** [HIT-SCIR/ltp#191]
http://192.168.1.107:12345/ltp?s=提问的也越来越多，但是好的问题却凤毛麟角&t=all&x=n

上面这个url无法在浏览器中使用，希望告知url格式

谢谢～

**Comment by endyul** [comment]
您好，您需要以POST方式请求数据。浏览器直接访问地址是GET方法

Regards --
On 周三, 11月 16, 2016 at 23:11, lifeng1989 <notifications@github.com> wrote:
http://192.168.1.107:12345/ltp?s=提问的也越来越多，但是好的问题却凤毛麟角&t=all&x=n [http://192.168.1.107:12345/ltp?s=%E6%8F%90%E9%97%AE%E7%9A%84%E4%B9%9F%E8%B6%8A%E6%9D%A5%E8%B6%8A%E5%A4%9A%EF%BC%8C%E4%BD%86%E6%98%AF%E5%A5%BD%E7%9A%84%E9%97%AE%E9%A2%98%E5%8D%B4%E5%87%A4%E6%AF%9B%E9%BA%9F%E8%A7%92&t=all&x=n]

上面这个url无法在浏览器中使用，希望告知url格式

谢谢～
