### ISSUE TITLE
ltp-cloud 新接口缺少自定义分词中xml文件格式

### ISSUE THREAD

**Issue by jackycaf** [HIT-SCIR/ltp#192]
在ltp-cloud的接口文档中《重要说明》一节

1.关于如何自定义分词

语言云允许用户自定义分词，并在此基础上进行更深层次的语言分析。用户需指定参数xml_input=true，分词结果需要以XML的表示方式指定在text参数中。用户必须使用POST方式开展此项功能。

从 ltp-cloud-api-tutorial 项目的python模块中生成的xml文档无法用于：api_url = "http://api.ltp-cloud.com/analysis/"

而老接口（http://ltpapi.voicecloud.cn/analysis/?）中缺少语义依存的标注功能。
求新接口（ "http://api.ltp-cloud.com/analysis/）的自定义分词和词性标注的xml文档格式。

**Comment by endyul** [comment]
@memeda

**Comment by memeda** [comment]
今晚检查一下~
