### ISSUE TITLE
平台无法注册

### ISSUE THREAD

**Issue by sherlockzoom** [HIT-SCIR/ltp#194]
```
DatabaseError at /accounts/register/
(1114, "The table 'ltpwebsite_userprofile' is full")
Request Method:	POST
Request URL:	http://www.ltp-cloud.com/accounts/register/
Django Version:	1.5.4
Exception Type:	DatabaseError
Exception Value:	
(1114, "The table 'ltpwebsite_userprofile' is full")
Exception Location:	/usr/lib/python2.7/dist-packages/MySQLdb/connections.py in defaulterrorhandler, line 36
Python Executable:	/usr/bin/python
Python Version:	2.7.6
Python Path:	
['/home/ubuntu/ltp-frontend/frontend',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages']
Server time:	Wed, 30 Nov 2016 09:37:17 +0800
```
语言云平台注册时，出现如上所示的错误。希望能修复。

**Comment by endyul** [comment]
感谢反馈，正在处理

Regards --
On 周三, 11月 30, 2016 at 09:42, ylz <notifications@github.com> wrote:
DatabaseError at /accounts/register/
(1114, "The table 'ltpwebsite_userprofile' is full")
Request Method:	POST
Request URL:	http://www.ltp-cloud.com/accounts/register/
Django Version:	1.5.4
Exception Type:	DatabaseError
Exception Value:	
(1114, "The table 'ltpwebsite_userprofile' is full")
Exception Location:	/usr/lib/python2.7/dist-packages/MySQLdb/connections.py in defaulterrorhandler, line 36
Python Executable:	/usr/bin/python
Python Version:	2.7.6
Python Path:	
['/home/ubuntu/ltp-frontend/frontend',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages']
Server time:	Wed, 30 Nov 2016 09:37:17 +0800


语言云平台注册时，出现如上所示的错误。希望能修复。

**Comment by sherlockzoom** [comment]
@endyul 已经成功注册，感谢。
