### ISSUE TITLE
为什么我使用分词接口只能分一串英文，不能分中文？求指点

### ISSUE THREAD

**Issue by liquor7** [HIT-SCIR/ltp#196]

**Comment by endyul** [comment]
能否给出具体的例子？
是否下载了完整的模型？

**Comment by liquor7** [comment]
我已经下载了完整了模型，但是测试只使用cws_model   据说是因为windows下终端显示会出现乱码，现在正在尝试解决，不知道是不是这个原因。

**Comment by endyul** [comment]
输入输出均为utf8编码

**Comment by liquor7** [comment]
我使用的是测试用例  “我爱上了一匹野马，但我家里没有草原” 可是分词后的单词数为0(用VS）  在终端改成gbk编码后，xml显示结果是乱码

**Comment by endyul** [comment]
请确认你的输入为utf8编码

**Comment by liquor7** [comment]
windows终端下的问题已经解决了..谢谢@endyul   只是想请问你有没有在VS下运行成功？

**Comment by endyul** [comment]
VS是测试过的，请确认VS接口输入的是UTF-8编码
