### ISSUE TITLE
ltp_sever占用虚拟内存高问题

### ISSUE THREAD

**Issue by 18474475** [HIT-SCIR/ltp#197]
ltp_Server部署在我自己电脑虚拟机上一段时间后，发现占用了30几G的虚拟内存VIRT。这个算正常吗还是内存泄露引起的？

**Comment by 18474475** [comment]
会不会是跟线程数设置大有关系，配置了5000

**Comment by endyul** [comment]
5000太多了
srl好像有memory leak问题

**Comment by 18474475** [comment]
好的，语义角色标注还没用过。
线程改成200以后虚拟内存占用1G多。应该是正常了。 
谢谢
