### ISSUE TITLE
生成的release中语义角色标注问题

### ISSUE THREAD

**Issue by Icomming** [HIT-SCIR/ltp#198]
我在windows下使用ltp_test处理的结果如下：
            sent id="0" cont="特朗普 是 在 接受 福克斯 电视台 “ 福克斯 周日 新闻 ” 栏目 采访 时 做出 上述 表态 的 。"
                word id="0" cont="特朗普" pos="nh" ne="S-Nh" parent="1" relate="SBV" 
                word id="1" cont="是" pos="v" ne="O" parent="-1" relate="HED"
                    arg id="0" type="ۦ#x0F;" beg="0" end="0" 
               
这个结果的语义角色标注有乱码，而且和语言云的xml结果比较，缺少sem。使用的是3.3.1的模型文件，最新的release。求解答。
语言云结果：

			sent id="0" cont="特朗普是在接受福克斯电视台“福克斯周日新闻”栏目采访时做出上述表态的。"
				word id="0" cont="特朗普" pos="nh" ne="S-Nh" parent="1" relate="SBV" semparent="3" semrelate="Agt"
					sem id="0" parent="3" relate="Agt"

				word id="1" cont="是" pos="v" ne="O" parent="-1" relate="HED" semparent="3" semrelate="mMod"
					arg id="0" type="A0" beg="0" end="0"
					sem id="0" parent="3" relate="mMod"

**Comment by endyul** [comment]
win下的srl乱码是bug
语义依存功能还未在离线版中提供

**Comment by Icomming** [comment]
语义角色标注在ubuntu下可以吗？

**Comment by endyul** [comment]
可以

**Comment by Icomming** [comment]
谢谢，我去试试。
