### ISSUE TITLE
Windows下静态库与动态库存在同名覆盖问题

### ISSUE THREAD

**Issue by memeda** [HIT-SCIR/ltp#199]
因为Windows下动态库一般包含 `*.lib` , `*.dll`, `*.exp` 三个文件，其中的`*.lib`是导出的符号表；

而静态库输出为 `*.lib`, 该lib中包含符号和实现；

目前LTP中`splitsnt`, `cws`, `postagger`, `ner`, `parser`, `srl`等导出的静态库和动态库名字都是相同的，这在Linux上没有问题（分别是`*.a` 和 `*.so`）, 但是在Windows下静态库的`*.lib`与动态库的`*.lib`会存在覆盖的问题。

或许可以修改静态库和动态库的导出名字，使它们名称不同？或者限定仅在Windows平台下导出为不同名字？

**Comment by endyul** [comment]
计划在Windows下，导出静态库的名字后加`_static`

**Comment by endyul** [comment]
@memeda 现在的名称是怎样的呀？

appveyor上的编译结果貌似只产出了dll
https://ci.appveyor.com/project/Oneplus/ltp/build/1.0.62/job/6x7692apn9fcbl3p/artifacts

**Comment by memeda** [comment]
应该是打包的问题，我看前面上面的日志，动态库的导入库和静态库都生成了，但是打包的时候只压缩了*.dll.


```
1823: Time Elapsed 00:11:48.23
1824: cd c:\projects\ltp
1825: 7z a ltp-win-%PLATFORM%-%CONFIGURATION%.zip bin\examples\%CONFIGURATION%\*_cmdline.exe bin\%CONFIGURATION%\ltp_test.exe lib\%CONFIGURATION%\*.dll
```

不知道打包这个能不能配置下，把 `*.lib` 都给加上吧
