### ISSUE TITLE
模型百度云下载链接无法访问

### ISSUE THREAD

**Issue by lzhibin** [HIT-SCIR/ltp#200]
您好，请问http://pan.baidu.com/share/link?shareid=1988562907&uk=2738088569 这个模型百度云的模型下载链接无法访问，有没有别的下载地址可以下载到模型？或者说能否修复一下链接，谢谢。

**Comment by endyul** [comment]
可以访问的，请您确认一下是否是网络问题

**Comment by lzhibin** [comment]
抱歉，可以了访问了，不清楚是什么原因，昨天我一直就打开都是404，今天可以正常访问，谢谢，打扰了
