### ISSUE TITLE
LTP 切词丢失空格的问题

### ISSUE THREAD

**Issue by rudaoshi** [HIT-SCIR/ltp#201]
一段带空格的文本切词后，空格会丢失。

这样 "".join(segmenter.segment(string)) != string 

语义上不一致。

**Comment by endyul** [comment]
@Oneplus should we support this issue?

**Comment by rudaoshi** [comment]
处理空格会给使用者以额外的切词控制自由度，应当支持。

**Comment by endyul** [comment]
目前我们分词的规范依照北大标准，ref: http://icl.pku.edu.cn/icl_groups/corpus/spec.htm

该标准未对文本中的「空格」处理方式作出明确说明。如果我们将「空格」视为标点，那么处理方式就应该如您所述。

希望能从中文文本规范的角度讨论「将『空格』作为句子构成元素」的必要性，而非从程序语义的角度出发，希望您能够提供一些句例。

另外，若在分词任务中引入「空格」的支持，我们还需要考虑到「空格」在词性标注/句法分析等任务中的处理规范。

@Oneplus

**Comment by endyul** [comment]
有语言学学者指出「书面汉语是字的序列，词没有明确边界」；也有语言学的学者提出在中文中引入空格作为「意群切分标记」。不过此处的「意群切分标记」也不能和「标点」划等号。

所以考虑三种处理方式：
  
  1. 不将空格视为语法单位，完全忽略输入中的空格，所以分词结果中也不会有空格
  2. 不将空格视为语法单位，但是将空格作为一种「意群切分标记」的特征，但是不能起到切分的决定性作用。由于空格标记和分词结果可能会有冲突，所以结果中不保留空格。
  3. 不将空格视为语法单位，但是将输入中的空格作为一种「意群切分标记」的gold标记，遇到空格强制切分。所以空格标记和分词结果不会冲突，结果中可以显示空格。
  4. 将空格视为语法单位。该做法缺少语言学支撑

目前LTP采用的是第2种处理方式。

所以如果要在分词结果中保留空格，只有采用第3种方式，这与目前系统的实现是有冲突的。我们还要考虑一下

@Oneplus

**Comment by JavyZheng** [comment]
在需要计算词在句中offset(相对于句首的位置)的场合，分词结果丢失空格会给offset的计算带来麻烦。

**Comment by endyul** [comment]
我觉得这个需求不应该问责给 segment，个人观点依然是 segment 的结果应该只包含语法单位。否则对随后的词性、句法等模块也会带来 confusion。引入了空格，会让分词接口以及整个 pipeline 变得不干净

我们可以考虑提供分词结果中的某个词在原输入中的offset的额外接口，用户也可以自己实现，并不是很麻烦

**Comment by JavyZheng** [comment]
使用中发现以下句子

`賽歐3 1.5手動理想版，` (賽歐3后面有个空格，后面的1.5表示排量)

会被分成:

`賽歐","31.5","手動","理想","版","，"`

分词器把3后面的空格去掉，然后把3和1.5合并成了一个词。这样该怎样计算词的offset呢？

**Comment by memeda** [comment]
在使用中发现在预处理过程中丢失空格导致结果不对的case：

*source*

> 2016-12-08 12:29 139邮箱 短信及时提醒，随时随地收发邮件。

*segmented result*

> 2016-12-08  12  :  29139  邮箱  短信  及时  提醒  ，  随时随地  收发  邮件  。

其中 `139邮箱`中的`139`与前面的时间粘到一起了. 

PS： 感觉这个处理起来真的蛮复杂的，预处理与分词流程的结合，还是比较复杂。

**Comment by endyul** [comment]
@memeda 这个问题开一个新issue吧

**Comment by Oneplus** [comment]
@endyul 解决的话：

1. 就需要给分词初始化时加一个参数
2. 预处理需要改
3. 训练模型时可能也需要一部分有空格的数据
