### ISSUE TITLE
在mac下安装ltp成功，但是编译java调用的动态库出现错误

### ISSUE THREAD

**Issue by zxy00** [HIT-SCIR/ltp#202]
[ 16%] Linking CXX shared library libs/libsrl_jni.dylib
Undefined symbols for architecture x86_64:
  "SRL_LoadResource(std::string const&)", referenced from:
      _Java_edu_hit_ir_ltp4j_SRL_create in srl_jni.cpp.o
  "DoSRL(std::vector<std::string, std::allocator<std::string> > const&, std::vector<std::string, std::allocator<std::string> > const&, std::vector<std::string, std::allocator<std::string> > const&, std::vector<std::pair<int, std::string>, std::allocator<std::pair<int, std::string> > > const&, std::vector<std::pair<int, std::vector<std::pair<std::string, std::pair<int, int> >, std::allocator<std::pair<std::string, std::pair<int, int> > > > >, std::allocator<std::pair<int, std::vector<std::pair<std::string, std::pair<int, int> >, std::allocator<std::pair<std::string, std::pair<int, int> > > > > > >&)", referenced from:
      _Java_edu_hit_ir_ltp4j_SRL_srl in srl_jni.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libs/libsrl_jni.dylib] Error 1
make[1]: *** [CMakeFiles/srl_jni.dir/all] Error 2
make: *** [all] Error 2
zxydeMacBook-Pro:ltp4j-master zxy$

**Comment by endyul** [comment]
可以尝试用neoltp4j这个分支，该分支用maven进行编译
https://github.com/HIT-SCIR/ltp4j/tree/neoltp4j

文档参考：
http://ltp4j.readthedocs.io/en/neoltp4j/install.html#maven

macOS 10.12 下 maven 的 test phrase 会失败，这是maven-nar的bug，可以暂时忽略
编译出的jar和动态库分别是：
`target/ltp4j-0.1.0-SNAPSHOT-x86_64-MacOSX-gpp-jni.nar`
`target/nar/ltp4j-0.1.0-SNAPSHOT-x86_64-MacOSX-gpp-jni/lib/x86_64-MacOSX-gpp/jni`
