### ISSUE TITLE
如何显示分词位置信息？

### ISSUE THREAD

**Issue by 642874367** [HIT-SCIR/ltp#203]
<?xml version="1.0" encoding="utf-8" ?>
<xml4nlp>
    <note sent="y" word="y" pos="y" ne="y" parser="y" wsd="y" srl="y" />
    <doc>
        <para id="0">
            <sent id="0" cont="我们都是中国人">
                <word id="0" cont="我们" pos="r" ne="O" parent="2" relate="SBV" />
                <word id="1" cont="都" pos="d" ne="O" parent="2" relate="ADV" />
                <word id="2" cont="是"  pos="v" ne="O" parent="-1" relate="HED">
                    <arg id="0" type="A0" beg="0" end="0" />
                    <arg id="1" type="AM-ADV" beg="1" end="1" />
                </word>
                <word id="3" cont="中国" pos="ns" ne="S-Ns" parent="4" relate="ATT" />
                <word id="4" cont="人" pos="n" ne="O" parent="2" relate="VOB" />
            </sent>
        </para>
    </doc>
</xml4nlp>

没有看到分词的位置信息，这个如何显示？

**Comment by endyul** [comment]
暂不支持

**Comment by carfly** [comment]
没理解，什么叫显示分词的位置信息？

**Comment by Linusp** [comment]
@carfly 我理解是词在原文中的 offset，比如在 jieba  中可以这样

```
In [7]: for tok, beg, end in jieba.tokenize('如何显示分词位置信息'):
   ...:     print(tok, beg, end)
   ...:     
如何 0 2
显示 2 4
分词 4 6
位置 6 8
信息 8 10
```

cc @642874367 不知是否是这样的
