### ISSUE TITLE
空格分开的数字经过分词后连在一起了

### ISSUE THREAD

**Issue by memeda** [HIT-SCIR/ltp#204]
在使用中发现在预处理过程中丢失空格导致结果不对的case：

*source*

> 2016-12-08 12:29 139邮箱 短信及时提醒，随时随地收发邮件。

*segmented result*

> 2016-12-08 12 : 29139 邮箱 短信 及时 提醒 ， 随时随地 收发 邮件 。

其中 139邮箱中的139与前面的时间粘到一起了.

PS： 感觉这个处理起来真的蛮复杂的，预处理与分词流程的结合，还是比较复杂。

**Comment by Oneplus** [comment]
是的…

**Comment by fan31415** [comment]
居然这么久了还没修复..
