### ISSUE TITLE
示例中cws.cpp在linux中运行的问题

### ISSUE THREAD

**Issue by ghbtest** [HIT-SCIR/ltp#208]
按照http://ltp.readthedocs.io/zh_CN/latest/api.html上的示例说明，运行
g++ -o cws cws.cpp -I /path/to/your/ltp-project/include/ -I /path/to/your/ltp-project/thirdparty/boost/include -WL,-dn -L /path/to/your/ltp-project/lib/ -lsegmentor -lboost_regex -WL,-dy
提示：
g++: error: unrecognized command line option ‘-WL,-dn’
g++: error: unrecognized command line option ‘-WL,-dy’

请问如何解决？谢谢！

**Comment by endyul** [comment]
抱歉，请把两个`-WL`改成`-Wl`，（小写l）
`g++ -o cws cws.cpp -I /path/to/your/ltp-project/include/ -I /path/to/your/ltp-project/thirdparty/boost/include -Wl,-dn -L /path/to/your/ltp-project/lib/ -lsegmentor -lboost_regex -Wl,-dy`
