### ISSUE TITLE
如何在本地ltp中加载用户词典

### ISSUE THREAD

**Issue by smallflying** [HIT-SCIR/ltp#210]

**Comment by endyul** [comment]
请参考文档 http://ltp.readthedocs.io/zh_CN/latest/ltptest.html#ltpexlex-reference-label

**Comment by smallflying** [comment]
@endyul 加载外部词典时出现输出的out.txt文件中是空的。
代码是：# -*- coding: utf-8 -*
import os

project_path = "d:\\myprojects\\ltp"  # 项目文件夹目录

model_exe = "cws_cmdline"   # 分词模块，相当于ltp_test的last_stage=ws，但是输出格式不同
threads_num = " --threads " + str(3)  # 更改线程数
input_path = " --input " + "d:\\myprojects\\LTP\\file\\test.txt"  # 输入文件
seg_lexicon = " --segmentor-lexicon " + "D:\\myprojects\\LTP\\file\\seg_lexicon.txt"  # 分词用户词典
output_path = "D:\\myprojects\\LTP\\result\\out.txt"  # 输出文件

command = "cd "+project_path + " & " +model_exe + threads_num +input_path+seg_lexicon + " > " + output_path
os.system(command)
下面的运行结果是：
C:\Python27\python.exe C:/Users/Administrator.USER-20170302KC/PycharmProjects/untitled2/2.py
'cws_cmdline' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

Process finished with exit code 0
这是什么原因

**Comment by endyul** [comment]
请检查您各参数使用的文件编码是否均为utf-8

**Comment by smallflying** [comment]
@endyul 我将所有的文件都改为utf-8格式后还是出现上边的问题，我又用windows控制台运行，显示的问题是：cws_cmdline不是内部命令和外部命令，也不是可运行的程序。我将tp-3.3.1-win-x86.zip的解压后和ltp-data的模型包都放在了同一个项目文件夹下了。

**Comment by endyul** [comment]
试下`./cws_cmdline`

**Comment by smallflying** [comment]
@endyul 没有用，显示  “.”不是内部命令和外部命令，也不是可运行的程序。

**Comment by endyul** [comment]
您查一下os.system的用法吧，这个问题不是ltp引起的

**Comment by endyul** [comment]
refer to #211
