### ISSUE TITLE
为何本地部署ltp，用python调用ltp_test.exe时显示停止运行？

### ISSUE THREAD

**Issue by smallflying** [HIT-SCIR/ltp#211]
代码如下：
# -*- coding:UTF-8 -*-
import os

LTP_path = "D:\\myprojects\\LTP"
model_exe = "ltp_test"
threads_num = " --threads 3"
last_stage = " --last-stage" + "all"
input_path = " --input" + "D:\\myprojects\\LTP\\file\\test.txt"
seg_lexicon = ""
pos_lexicon = ""
output_path = "D:\\myprojects\\LTP\\result\\out.txt"
command = "cd " + LTP_path + "& " + model_exe + threads_num + input_path + last_stage + " >" + output_path
os.system(command)

**Comment by endyul** [comment]
有没有错误信息？请检查一下模型是否被正确加载

**Comment by smallflying** [comment]
@endyul 在dos下单独运行ltp_test.exe没有问题，就是在运行调用程序时会弹出窗口“”ltp_test.exe已停止工作“”的消息，其他的错误信息没有

**Comment by endyul** [comment]
任何log也没有吗？

可能是你的路径转义了，例如`"D:\myprojects\LTP\file\test.txt"`中的`\t`
建议所有路径都写成正斜杠的形式

**Comment by smallflying** [comment]
@endyul 没有任何的log，路径改过后运行还是出现“ltp_test.exe已停止工作”，我想可能是兼容问题，但是调试后还是不行。

**Comment by endyul** [comment]
```
last_stage = " --last-stage" + "all"
input_path = " --input" + "D:\myprojects\LTP\file\test.txt"
```
是不是漏空格了

**Comment by smallflying** [comment]
@endyul 上方的问题解决了，但是输出的结果out.txt文件中什么都没有。

**Comment by endyul** [comment]
same with #213
