### ISSUE TITLE
ltp-server 对同一段话测试，有时候会出现乱码

### ISSUE THREAD

**Issue by lhyxcxy** [HIT-SCIR/ltp#212]
# 测试句子
黎汉奸离坐牢不远了，现在主要收集他犯罪证据。
# 不出现乱码：
<pre name="code" class="html">&lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
&lt;xml4nlp&gt;
    &lt;note sent=&quot;y&quot; word=&quot;y&quot; pos=&quot;y&quot; ne=&quot;y&quot; parser=&quot;y&quot; wsd=&quot;n&quot; srl=&quot;y&quot; /&gt;
    &lt;doc&gt;
        &lt;para id=&quot;0&quot;&gt;
            &lt;sent id=&quot;0&quot; cont=&quot;黎汉奸离坐牢不远了，现在主要收集他犯罪证据。&quot;&gt;
                &lt;word id=&quot;0&quot; cont=&quot;黎&quot; pos=&quot;j&quot; ne=&quot;S-Ns&quot; parent=&quot;1&quot; relate=&quot;ATT&quot; /&gt;
                &lt;word id=&quot;1&quot; cont=&quot;汉奸&quot; pos=&quot;n&quot; ne=&quot;O&quot; parent=&quot;3&quot; relate=&quot;SBV&quot; /&gt;
                &lt;word id=&quot;2&quot; cont=&quot;离&quot; pos=&quot;v&quot; ne=&quot;O&quot; parent=&quot;3&quot; relate=&quot;ADV&quot; /&gt;
                &lt;word id=&quot;3&quot; cont=&quot;坐牢&quot; pos=&quot;v&quot; ne=&quot;O&quot; parent=&quot;-1&quot; relate=&quot;HED&quot;&gt;
                    &lt;arg id=&quot;0&quot; type=&quot;A0&quot; beg=&quot;0&quot; end=&quot;1&quot; /&gt;
                    &lt;arg id=&quot;1&quot; type=&quot;DIR&quot; beg=&quot;2&quot; end=&quot;2&quot; /&gt;
                &lt;/word&gt;
                &lt;word id=&quot;4&quot; cont=&quot;不&quot; pos=&quot;d&quot; ne=&quot;O&quot; parent=&quot;5&quot; relate=&quot;ADV&quot; /&gt;
                &lt;word id=&quot;5&quot; cont=&quot;远&quot; pos=&quot;a&quot; ne=&quot;O&quot; parent=&quot;3&quot; relate=&quot;CMP&quot; /&gt;
                &lt;word id=&quot;6&quot; cont=&quot;了&quot; pos=&quot;u&quot; ne=&quot;O&quot; parent=&quot;3&quot; relate=&quot;RAD&quot; /&gt;
                &lt;word id=&quot;7&quot; cont=&quot;，&quot; pos=&quot;wp&quot; ne=&quot;O&quot; parent=&quot;3&quot; relate=&quot;WP&quot; /&gt;
                &lt;word id=&quot;8&quot; cont=&quot;现在&quot; pos=&quot;nt&quot; ne=&quot;O&quot; parent=&quot;10&quot; relate=&quot;ADV&quot; /&gt;
                &lt;word id=&quot;9&quot; cont=&quot;主要&quot; pos=&quot;d&quot; ne=&quot;O&quot; parent=&quot;10&quot; relate=&quot;ADV&quot; /&gt;
                &lt;word id=&quot;10&quot; cont=&quot;收集&quot; pos=&quot;v&quot; ne=&quot;O&quot; parent=&quot;3&quot; relate=&quot;COO&quot;&gt;
                    &lt;arg id=&quot;0&quot; type=&quot;A0&quot; beg=&quot;0&quot; end=&quot;1&quot; /&gt;
                    &lt;arg id=&quot;1&quot; type=&quot;TMP&quot; beg=&quot;8&quot; end=&quot;8&quot; /&gt;
                    &lt;arg id=&quot;2&quot; type=&quot;ADV&quot; beg=&quot;9&quot; end=&quot;9&quot; /&gt;
                    &lt;arg id=&quot;3&quot; type=&quot;A1&quot; beg=&quot;11&quot; end=&quot;13&quot; /&gt;
                &lt;/word&gt;
                &lt;word id=&quot;11&quot; cont=&quot;他&quot; pos=&quot;r&quot; ne=&quot;O&quot; parent=&quot;13&quot; relate=&quot;ATT&quot; /&gt;
                &lt;word id=&quot;12&quot; cont=&quot;犯罪&quot; pos=&quot;v&quot; ne=&quot;O&quot; parent=&quot;13&quot; relate=&quot;ATT&quot; /&gt;
                &lt;word id=&quot;13&quot; cont=&quot;证据&quot; pos=&quot;n&quot; ne=&quot;O&quot; parent=&quot;10&quot; relate=&quot;VOB&quot; /&gt;
                &lt;word id=&quot;14&quot; cont=&quot;。&quot; pos=&quot;wp&quot; ne=&quot;O&quot; parent=&quot;3&quot; relate=&quot;WP&quot; /&gt;
            &lt;/sent&gt;
        &lt;/para&gt;
    &lt;/doc&gt;
&lt;/xml4nlp&gt;</pre>
<br />

# 出现乱码

<pre name="code" class="html">&lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
&lt;xml4nlp&gt;
    &lt;note sent=&quot;y&quot; word=&quot;y&quot; pos=&quot;y&quot; ne=&quot;y&quot; parser=&quot;y&quot; wsd=&quot;n&quot; srl=&quot;y&quot; /&gt;
    &lt;doc&gt;
        &lt;para id=&quot;0&quot;&gt;
            &lt;sent id=&quot;0&quot; cont=&quot;黎汉奸离坐牢不远了，现在主要收集他犯罪证据。&quot;&gt;
                &lt;word id=&quot;0&quot; cont=&quot;黎&quot; pos=&quot;j&quot; ne=&quot;S-Ns&quot; parent=&quot;1&quot; relate=&quot;ATT&quot; /&gt;
                &lt;word id=&quot;1&quot; cont=&quot;汉奸&quot; pos=&quot;n&quot; ne=&quot;O&quot; parent=&quot;3&quot; relate=&quot;SBV&quot; /&gt;
                &lt;word id=&quot;2&quot; cont=&quot;离&quot; pos=&quot;v&quot; ne=&quot;O&quot; parent=&quot;3&quot; relate=&quot;ADV&quot; /&gt;
                &lt;word id=&quot;3&quot; cont=&quot;坐牢&quot; pos=&quot;v&quot; ne=&quot;O&quot; parent=&quot;-1&quot; relate=&quot;HED&quot;&gt;
                    &lt;arg id=&quot;0&quot; type=&quot;A0&quot; beg=&quot;0&quot; end=&quot;1&quot; /&gt;
                    &lt;arg id=&quot;1&quot; type=&quot;DIR&quot; beg=&quot;2&quot; end=&quot;2&quot; /&gt;
                &lt;/word&gt;
                &lt;word id=&quot;4&quot; cont=&quot;不&quot; pos=&quot;d&quot; ne=&quot;O&quot; parent=&quot;5&quot; relate=&quot;ADV&quot; /&gt;
                &lt;word id=&quot;5&quot; cont=&quot;远&quot; pos=&quot;a&quot; ne=&quot;O&quot; parent=&quot;3&quot; relate=&quot;CMP&quot; /&gt;
                &lt;word id=&quot;6&quot; cont=&quot;了&quot; pos=&quot;u&quot; ne=&quot;O&quot; parent=&quot;3&quot; relate=&quot;RAD&quot; /&gt;
                &lt;word id=&quot;7&quot; cont=&quot;，&quot; pos=&quot;wp&quot; ne=&quot;O&quot; parent=&quot;3&quot; relate=&quot;WP&quot; /&gt;
                &lt;word id=&quot;8&quot; cont=&quot;现在&quot; pos=&quot;nt&quot; ne=&quot;O&quot; parent=&quot;10&quot; relate=&quot;ADV&quot; /&gt;
                &lt;word id=&quot;9&quot; cont=&quot;主要&quot; pos=&quot;d&quot; ne=&quot;O&quot; parent=&quot;10&quot; relate=&quot;ADV&quot; /&gt;
                &lt;word id=&quot;10&quot; cont=&quot;收集&quot; pos=&quot;v&quot; ne=&quot;O&quot; parent=&quot;3&quot; relate=&quot;COO&quot;&gt;
                    &lt;arg id=&quot;0&quot; type=&quot;&quot; beg=&quot;0&quot; end=&quot;1&quot; /&gt;
                    &lt;arg id=&quot;1&quot; type=&quot;p&gt;��&quot; beg=&quot;8&quot; end=&quot;8&quot; /&gt;
                    &lt;arg id=&quot;2&quot; type=&quot;&quot; beg=&quot;9&quot; end=&quot;9&quot; /&gt;
                    &lt;arg id=&quot;3&quot; type=&quot;PG
��&quot; beg=&quot;11&quot; end=&quot;13&quot; /&gt;
                &lt;/word&gt;
                &lt;word id=&quot;11&quot; cont=&quot;他&quot; pos=&quot;r&quot; ne=&quot;O&quot; parent=&quot;13&quot; relate=&quot;ATT&quot; /&gt;
                &lt;word id=&quot;12&quot; cont=&quot;犯罪&quot; pos=&quot;v&quot; ne=&quot;O&quot; parent=&quot;13&quot; relate=&quot;ATT&quot; /&gt;
                &lt;word id=&quot;13&quot; cont=&quot;证据&quot; pos=&quot;n&quot; ne=&quot;O&quot; parent=&quot;10&quot; relate=&quot;VOB&quot; /&gt;
                &lt;word id=&quot;14&quot; cont=&quot;。&quot; pos=&quot;wp&quot; ne=&quot;O&quot; parent=&quot;3&quot; relate=&quot;WP&quot; /&gt;
            &lt;/sent&gt;
        &lt;/para&gt;
    &lt;/doc&gt;
&lt;/xml4nlp&gt;</pre>
<br />
<br />

**Comment by endyul** [comment]
这是语义角色标注模块在windows下的bug，下个版本修复

**Comment by lhyxcxy** [comment]
我是在ubuntu 下面运行的

**Comment by lhyxcxy** [comment]
同一个句子有时候乱码，有时候不乱码

**Comment by endyul** [comment]
感谢反馈，会尽快修复

**Comment by lhyxcxy** [comment]
您好，有没有改好的代码发我一下，

**Comment by endyul** [comment]
抱歉，暂时还没有

**Comment by endyul** [comment]
fix in #218
