### ISSUE TITLE
本地部署的ltp在系统调用时输出的out.txt文件中没有内容？

### ISSUE THREAD

**Issue by smallflying** [HIT-SCIR/ltp#213]
代码如下：
```
# -*- coding: utf-8 -*-

"""
功能：LTP本地分词cws_cmdline，输入文本需要每行一句。（不能自动分句）
时间：2016年4月13日 20:22:39
"""

import os

project_path = "d:\\myprojects\\LTP"  # 项目文件夹目录

model_exe = "cws_cmdline"  # 分词模块，相当于ltp_test的last_stage=ws，但是输出格式不同

threads_num = " --threads " + str(3)  # 更改线程数
input_path = " --input " + " d:\\myprojects\\LTP\\file\\test.txt"  # 输入文件
#seg_lexicon = " --segmentor-lexicon " + "D:\\myprojects\\LTP\\file\\seg_lexicon.txt"  # 分词用户词典
output_path = "D:\\myprojects\\LTP\\result\\out.txt"  # 输出文件

command = "cd " + project_path + " & " + model_exe + threads_num + input_path + " > " + output_path
os.system(command)
```
运行结果信息如下：
```
C:\Python27\python.exe C:/Users/Administrator.USER-20170302KC/PycharmProjects/untitled4/test.py

Process finished with exit code 0
```

**Comment by endyul** [comment]
#211 中提到的路径问题改过么

**Comment by smallflying** [comment]
改过

**Comment by smallflying** [comment]
改成这样：input_path = " --input " + " d:\\myprojects\\LTP\\file\\test.txt"  或者是这样：input_path = " --input " + " d:/myprojects/LTP/file/test.txt"  都是out.txt文件中没有内容。

**Comment by smallflying** [comment]
改成这样：input_path = " --input " + " d:/myprojects/LTP/file/test.txt"  或者双斜杠都是out.txt文件中没有内容

**Comment by smallflying** [comment]
@endyul 上面的问题能解决吗

**Comment by endyul** [comment]
暂时还不能复现问题，在macos上是没问题的

**Comment by endyul** [comment]
`print command` 并把打印结果直接粘贴到命令行中运行是否有结果？

**Comment by endyul** [comment]
另外输入文件的编码是否是utf-8

**Comment by smallflying** [comment]
@endyul 输入格式和部署都是按照官方的弄的。

**Comment by endyul** [comment]
`print command` 打印出的结果是什么，直接粘贴到命令行中运行是否有结果？

另外`model_exe = "cws_cmdline"`为何不是`cws_cmdline.exe`

**Comment by smallflying** [comment]
@endyul printos.system(command)不是和print command一样的功能吗？ 这个本地部署的是用系统调用命令行的形式来进行分词的，所以python代码都是在目录d:\myprojects\LTP下的系统会自动的找到路径来分辨可执行文件，所以不用cws_cmdline.exe

**Comment by endyul** [comment]
两者不一样。我是想请您试一下不用`os.system`调用，而是直接在命令行中运行该命令是否有输出。
另外麻烦请试一下用`--segmentor-model`参数显式指定一下模型路径

**Comment by smallflying** [comment]
@endyul 在命令行中运行该命令有输出，--segmentor-model参数显式指定的模型路径是ltp_data/cws,model

**Comment by endyul** [comment]
抱歉，我在windows上实在无法重现您的问题。我做了如下工作，得到了期望的结果：
1. 使用您上面的代码，除了`project_path`、`input_path`和`output_path`设置成了我自己的目录

```
#coding: utf-8
import os

project_path = "c:\\ltp\\bin\\examples\\Release" # 项目文件夹目录

model_exe = "cws_cmdline" # 分词模块，相当于ltp_test的last_stage=ws，但是输出格式不同

threads_num = " --threads " + str(3) # 更改线程数
input_path = " --input " + " c:\\ltp\\input.txt" # 输入文件
output_path = "c:\\ltp\\out.txt" # 输出文件

command = "cd " + project_path + " & " + model_exe + threads_num + input_path + " > " + output_path
#command = "cd " + project_path + " & " + model_exe + threads_num + input_path + " --segmentor-model \\\\Mac\\Home\\data\\ltp-model\\3.3.1\\ltp_data\\cws.model" + " > " + output_path
print command
os.system(command)
```

2. 将ltp模型目录`ltp_data`放到了`project_path`目录中。
3. 在`input_path`的文件中，只有一行内容`这是测试文本`。并且将该文件保存为utf-8编码
4. 在终端中运行该程序，终端中输出结果如下，并且`output_path`文件中有分词后的结果
```
c:\ltp>python test.py
TRACE: Model is loaded
TRACE: Running 3 thread(s)
TRACE: consume 0.00100017 seconds.
```

麻烦您确认一下流程是否一致

**Comment by endyul** [comment]
另外请问您在终端中直接运行
`cd d:\myprojects\LTP & cws_cmdline --threads 3 --input d:\myprojects\LTP\file\test.txt > c:\ltp\output.txt`的终端的log输出是什么，以及`output.txt`里的内容是什么。

如果运行下面这个python程序是否可以得到结果
```
import os
command = r`cd d:\myprojects\LTP & cws_cmdline --threads 3 --input d:\myprojects\LTP\file\test.txt > c:\ltp\output.txt`
os.system(command)
```

**Comment by smallflying** [comment]
@endyul 我就是按您上面的流程进行的，另外我在终端运行cd d:\myprojects\LTP & cws_cmdline --threads 3 --input d:\myprojects\LTP\file\test.txt > c:\ltp\output.txt时终端没有任何的log输出，output.txt中也没有内容，我重做一下系统再调试一下。麻烦您了，再遇到问题在想您请教。谢谢！

**Comment by smallflying** [comment]
@endyul 问题已解决，谢谢您的解答！

**Comment by endyul** [comment]
请问是什么原因

**Comment by smallflying** [comment]
@endyul 系统少插件。

**Comment by smallflying** [comment]
@endyul 重做的系统

**Comment by anyanli** [comment]
> @endyul 系统少插件。

你好，我也有同样的问题，请问您是什么系统，具体是少什么插件清楚吗
