### ISSUE TITLE
训练数据

### ISSUE THREAD

**Issue by chqiwang** [HIT-SCIR/ltp#214]
请问你们训练命名实体识别模型用的是什么数据呢？98年的人民日报吗？

**Comment by endyul** [comment]
是的

**Comment by chqiwang** [comment]
请问你们对语料中的命名实体进行了怎样的预处理呢？语料中人名的姓和名是分开的（江/nr 泽民/nr），地名也是（东城区/ns 建国门/ns）你们是直接合并吗？我看你们的系统对于连在一起的多个人名一般只能识别出第一个（比如江泽民李鹏王国栋，只能识别出江泽民），这是为什么呢？

**Comment by endyul** [comment]
我们的语料里姓名是合起来的
连在一起只能识别第一个的情况，应该就是模型没有召回

**Comment by chqiwang** [comment]
一大串姓名都连在一起的情况（江/nr 泽民/nr 李/nr 鹏/nr）你们也是直接一起合起来的吗， 还是说进行一些特殊的处理了？
地名也是直接合并吗？

**Comment by endyul** [comment]
不会合起来的，数据会是`江泽民/nr 李鹏/nr`这样

**Comment by chqiwang** [comment]
请问你们处理的脚本还在吗？我现在想把自己的系统和LTP在人民日报98下做个对比，想把数据的预处理统一一下

**Comment by endyul** [comment]
抱歉，应该没有了。当时是按照北大的标准人工标注的。
您可以尝试一下用自动分词和词性作为标注集，ltp的`otner`进行重新训练来统一一下

**Comment by chqiwang** [comment]
好的 多谢你 还有你们优秀的开源项目

**Comment by endyul** [comment]
不客气:)
