### ISSUE TITLE
windows下用离线的ltp，只能把输入文件的一部分进行分析。

### ISSUE THREAD

**Issue by liupan664021** [HIT-SCIR/ltp#215]
用ltp_test进行测试的。
输出到控制台的xml里面只进行了前几个字的分析。
比如，输入文本是   这是测试文本。
然后返回来只有  这是  两个字的分词和后面的分析。
txt文件和控制台输入都试过了，一样的。
谁能解答一下这是怎么回事吗？
谢谢了！

**Comment by endyul** [comment]
请帖一下使用的命令和完整的结果

**Comment by liupan664021** [comment]
E:\help\ltp-3.3.1\bin\Release>ltp_test --segmentor-model E:\help\ltp-3.3.1\ltp-data-v3.3.1\ltp_data\cws.model --postagger-model E:\help\ltp-3.3.1\ltp-data-v3.3.1\ltp_data\pos.model --ner-model E:\help\ltp-3.3.1\ltp-data-v3.3.1\ltp_data\ner.model --parser-model E:\help\ltp-3.3.1\ltp-data-v3.3.1\ltp_data\parser.model --srl-data E:\help\ltp-3.3.1\ltp-data-v3.3.1\ltp_data\srl\
[INFO] 2017-04-14 21:59:38 Loading segmentor model from "E:\help\ltp-3.3.1\ltp-data-v3.3.1\ltp_data\cws.model" ...
[INFO] 2017-04-14 21:59:40 segmentor model is loaded.
[INFO] 2017-04-14 21:59:40 Loading postagger model from "E:\help\ltp-3.3.1\ltp-data-v3.3.1\ltp_data\pos.model" ...
[INFO] 2017-04-14 21:59:47 postagger model is loaded
[INFO] 2017-04-14 21:59:47 Loading NER resource from "E:\help\ltp-3.3.1\ltp-data-v3.3.1\ltp_data\ner.model"
[INFO] 2017-04-14 21:59:47 NER resource is loaded.
[INFO] 2017-04-14 21:59:47 Loading parser resource from "E:\help\ltp-3.3.1\ltp-data-v3.3.1\ltp_data\parser.model"
[INFO] 2017-04-14 21:59:52 parser is loaded.
[INFO] 2017-04-14 21:59:52 Loading SRL resource from "E:\help\ltp-3.3.1\ltp-data-v3.3.1\ltp_data\srl\"
[INFO] 2017-04-14 21:59:52 SRL resource is loaded.
WARN: Cann't open file! use stdin instead.
TRACE: LTP is built
TRACE: Running 1 thread(s)
这是测试文本。
<?xml version="1.0" encoding="utf-8" ?>
<xml4nlp>
    <note sent="y" word="y" pos="y" ne="y" parser="y" wsd="n" srl="y" />
    <doc>
        <para id="0">
            <sent id="0" cont="这是">
                <word id="0" cont="这是" pos="nh" ne="S-Nh" parent="-1" relate="HED" />
            </sent>
        </para>
    </doc>
</xml4nlp>

你好，麻烦看一下，谢谢。

**Comment by liupan664021** [comment]
E:\help\ltp-3.3.1\bin\Release>ltp_test --segmentor-model E:\help\ltp-3.3.1\ltp-data-v3.3.1\ltp_data\cws.model --postagger-model E:\help\ltp-3.3.1\ltp-data-v3.3.1\ltp_data\pos.model --ner-model E:\help\ltp-3.3.1\ltp-data-v3.3.1\ltp_data\ner.model --parser-model E:\help\ltp-3.3.1\ltp-data-v3.3.1\ltp_data\parser.model --srl-data E:\help\ltp-3.3.1\ltp-data-v3.3.1\ltp_data\srl\
[INFO] 2017-04-14 21:59:38 Loading segmentor model from "E:\help\ltp-3.3.1\ltp-data-v3.3.1\ltp_data\cws.model" ...
[INFO] 2017-04-14 21:59:40 segmentor model is loaded.
[INFO] 2017-04-14 21:59:40 Loading postagger model from "E:\help\ltp-3.3.1\ltp-data-v3.3.1\ltp_data\pos.model" ...
[INFO] 2017-04-14 21:59:47 postagger model is loaded
[INFO] 2017-04-14 21:59:47 Loading NER resource from "E:\help\ltp-3.3.1\ltp-data-v3.3.1\ltp_data\ner.model"
[INFO] 2017-04-14 21:59:47 NER resource is loaded.
[INFO] 2017-04-14 21:59:47 Loading parser resource from "E:\help\ltp-3.3.1\ltp-data-v3.3.1\ltp_data\parser.model"
[INFO] 2017-04-14 21:59:52 parser is loaded.
[INFO] 2017-04-14 21:59:52 Loading SRL resource from "E:\help\ltp-3.3.1\ltp-data-v3.3.1\ltp_data\srl\"
[INFO] 2017-04-14 21:59:52 SRL resource is loaded.
WARN: Cann't open file! use stdin instead.
TRACE: LTP is built
TRACE: Running 1 thread(s)
这是测试文本。
<?xml version="1.0" encoding="utf-8" ?>
<xml4nlp>
    <note sent="y" word="y" pos="y" ne="y" parser="y" wsd="n" srl="y" />
    <doc>
        <para id="0">
            <sent id="0" cont="这是">
                <word id="0" cont="这是" pos="nh" ne="S-Nh" parent="-1" relate="HED" />
            </sent>
        </para>
    </doc>
</xml4nlp>

**Comment by liupan664021** [comment]
E:\help\ltp-3.3.1\bin\Release>ltp_test --segmentor-model E:\help\ltp-3.3.1\ltp-data-v3.3.1\ltp_data\cws.model --postagger-model E:\help\ltp-3.3.1\ltp-data-v3.3.1\ltp_data\pos.model --ner-model E:\help\ltp-3.3.1\ltp-data-v3.3.1\ltp_data\ner.model --parser-model E:\help\ltp-3.3.1\ltp-data-v3.3.1\ltp_data\parser.model --srl-data E:\help\ltp-3.3.1\ltp-data-v3.3.1\ltp_data\srl\
[INFO] 2017-04-14 21:59:38 Loading segmentor model from "E:\help\ltp-3.3.1\ltp-data-v3.3.1\ltp_data\cws.model" ...
[INFO] 2017-04-14 21:59:40 segmentor model is loaded.
[INFO] 2017-04-14 21:59:40 Loading postagger model from "E:\help\ltp-3.3.1\ltp-data-v3.3.1\ltp_data\pos.model" ...
[INFO] 2017-04-14 21:59:47 postagger model is loaded
[INFO] 2017-04-14 21:59:47 Loading NER resource from "E:\help\ltp-3.3.1\ltp-data-v3.3.1\ltp_data\ner.model"
[INFO] 2017-04-14 21:59:47 NER resource is loaded.
[INFO] 2017-04-14 21:59:47 Loading parser resource from "E:\help\ltp-3.3.1\ltp-data-v3.3.1\ltp_data\parser.model"
[INFO] 2017-04-14 21:59:52 parser is loaded.
[INFO] 2017-04-14 21:59:52 Loading SRL resource from "E:\help\ltp-3.3.1\ltp-data-v3.3.1\ltp_data\srl\"
[INFO] 2017-04-14 21:59:52 SRL resource is loaded.
WARN: Cann't open file! use stdin instead.
TRACE: LTP is built
TRACE: Running 1 thread(s)
这是测试文本。
这是结果<?xml version="1.0" encoding="utf-8" ?>
<xml4nlp>
    <note sent="y" word="y" pos="y" ne="y" parser="y" wsd="n" srl="y" />
    <doc>
        <para id="0">
            <sent id="0" cont="这是">
                <word id="0" cont="这是" pos="nh" ne="S-Nh" parent="-1" relate="HED" />
            </sent>
        </para>
    </doc>
</xml4nlp>这是结果

**Comment by endyul** [comment]
用txt的时候是否是utf8编码

**Comment by liupan664021** [comment]
E:\help\ltp-3.3.1\bin\Release>ltp_test --segmentor-model E:\help\ltp-3.3.1\ltp-data-v3.3.1\ltp_data\cws.model --postagger-model E:\help\ltp-3.3.1\ltp-data-v3.3.1\ltp_data\pos.model --ner-model E:\help\ltp-3.3.1\ltp-data-v3.3.1\ltp_data\ner.model --parser-model E:\help\ltp-3.3.1\ltp-data-v3.3.1\ltp_data\parser.model --srl-data E:\help\ltp-3.3.1\ltp-data-v3.3.1\ltp_data\srl\
[INFO] 2017-04-14 21:59:38 Loading segmentor model from "E:\help\ltp-3.3.1\ltp-data-v3.3.1\ltp_data\cws.model" ...
[INFO] 2017-04-14 21:59:40 segmentor model is loaded.
[INFO] 2017-04-14 21:59:40 Loading postagger model from "E:\help\ltp-3.3.1\ltp-data-v3.3.1\ltp_data\pos.model" ...
[INFO] 2017-04-14 21:59:47 postagger model is loaded
[INFO] 2017-04-14 21:59:47 Loading NER resource from "E:\help\ltp-3.3.1\ltp-data-v3.3.1\ltp_data\ner.model"
[INFO] 2017-04-14 21:59:47 NER resource is loaded.
[INFO] 2017-04-14 21:59:47 Loading parser resource from "E:\help\ltp-3.3.1\ltp-data-v3.3.1\ltp_data\parser.model"
[INFO] 2017-04-14 21:59:52 parser is loaded.
[INFO] 2017-04-14 21:59:52 Loading SRL resource from "E:\help\ltp-3.3.1\ltp-data-v3.3.1\ltp_data\srl\"
[INFO] 2017-04-14 21:59:52 SRL resource is loaded.
WARN: Cann't open file! use stdin instead.
TRACE: LTP is built
TRACE: Running 1 thread(s)
这是测试文本。
<?xml version="1.0" encoding="utf-8" ?>
<xml4nlp>
    <note sent="y" word="y" pos="y" ne="y" parser="y" wsd="n" srl="y" />
    <doc>
        <para id="0">
            <sent id="0" cont="这是">
                <word id="0" cont="这是" pos="nh" ne="S-Nh" parent="-1" relate="HED" />
            </sent>
        </para>
    </doc>
</xml4nlp>

**Comment by liupan664021** [comment]
是的吧。

**Comment by endyul** [comment]
为什么close了这个issue，刚才您贴的结果也看不到了

**Comment by liupan664021** [comment]
额。。结果xml贴出来就没有了，要怎么弄。。

**Comment by liupan664021** [comment]
空白

**Comment by endyul** [comment]
use `insert code` in the toolbar above

**Comment by liupan664021** [comment]
很奇怪，刚那个txt好像是ascii的，但是能够显示两个字。我改成了utf8之后，就是乱码了

**Comment by liupan664021** [comment]
`
E:\help\ltp-3.3.1\bin\Release>ltp_test --segmentor-model E:\help\ltp-3.3.1\ltp-data-v3.3.1\ltp_data\cws.model --postagger-model E:\help\ltp-3.3.1\ltp-data-v3.3.1\ltp_data\pos.model --ner-model E:\help\ltp-3.3.1\ltp-data-v3.3.1\ltp_data\ner.model --parser-model E:\help\ltp-3.3.1\ltp-data-v3.3.1\ltp_data\parser.model --srl-data E:\help\ltp-3.3.1\ltp-data-v3.3.1\ltp_data\srl\ --input test2.txt
[INFO] 2017-04-14 22:09:26 Loading segmentor model from "E:\help\ltp-3.3.1\ltp-data-v3.3.1\ltp_data\cws.model" ...
[INFO] 2017-04-14 22:09:26 segmentor model is loaded.
[INFO] 2017-04-14 22:09:26 Loading postagger model from "E:\help\ltp-3.3.1\ltp-data-v3.3.1\ltp_data\pos.model" ...
[INFO] 2017-04-14 22:09:30 postagger model is loaded
[INFO] 2017-04-14 22:09:30 Loading NER resource from "E:\help\ltp-3.3.1\ltp-data-v3.3.1\ltp_data\ner.model"
[INFO] 2017-04-14 22:09:31 NER resource is loaded.
[INFO] 2017-04-14 22:09:31 Loading parser resource from "E:\help\ltp-3.3.1\ltp-data-v3.3.1\ltp_data\parser.model"
[INFO] 2017-04-14 22:09:35 parser is loaded.
[INFO] 2017-04-14 22:09:35 Loading SRL resource from "E:\help\ltp-3.3.1\ltp-data-v3.3.1\ltp_data\srl\"
[INFO] 2017-04-14 22:09:35 SRL resource is loaded.
TRACE: LTP is built
TRACE: Running 1 thread(s)
<?xml version="1.0" encoding="utf-8" ?>
<xml4nlp>
    <note sent="y" word="y" pos="y" ne="y" parser="y" wsd="n" srl="y" />
    <doc>
        <para id="0">
            <sent id="0" cont="这是">
                <word id="0" cont="这是" pos="nh" ne="S-Nh" parent="-1" relate="HED" />
            </sent>
        </para>
    </doc>
</xml4nlp>

TRACE: consume 0.016 seconds.
[INFO] 2017-04-14 22:09:35 segmentor model is released.
[INFO] 2017-04-14 22:09:35 postagger resource is released
[INFO] 2017-04-14 22:09:35 NER resource is released
[INFO] 2017-04-14 22:09:36 Parser is released
[INFO] 2017-04-14 22:09:36 SRL is released

E:\help\ltp-3.3.1\bin\Release>`

**Comment by liupan664021** [comment]
`
E:\help\ltp-3.3.1\bin\Release>ltp_test --segmentor-model E:\help\ltp-3.3.1\ltp-data-v3.3.1\ltp_data\cws.model --postagger-model E:\help\ltp-3.3.1\ltp-data-v3.3.1\ltp_data\pos.model --ner-model E:\help\ltp-3.3.1\ltp-data-v3.3.1\ltp_data\ner.model --parser-model E:\help\ltp-3.3.1\ltp-data-v3.3.1\ltp_data\parser.model --srl-data E:\help\ltp-3.3.1\ltp-data-v3.3.1\ltp_data\srl\ --input test2.txt
[INFO] 2017-04-14 22:09:26 Loading segmentor model from "E:\help\ltp-3.3.1\ltp-data-v3.3.1\ltp_data\cws.model" ...
[INFO] 2017-04-14 22:09:26 segmentor model is loaded.
[INFO] 2017-04-14 22:09:26 Loading postagger model from "E:\help\ltp-3.3.1\ltp-data-v3.3.1\ltp_data\pos.model" ...
[INFO] 2017-04-14 22:09:30 postagger model is loaded
[INFO] 2017-04-14 22:09:30 Loading NER resource from "E:\help\ltp-3.3.1\ltp-data-v3.3.1\ltp_data\ner.model"
[INFO] 2017-04-14 22:09:31 NER resource is loaded.
[INFO] 2017-04-14 22:09:31 Loading parser resource from "E:\help\ltp-3.3.1\ltp-data-v3.3.1\ltp_data\parser.model"
[INFO] 2017-04-14 22:09:35 parser is loaded.
[INFO] 2017-04-14 22:09:35 Loading SRL resource from "E:\help\ltp-3.3.1\ltp-data-v3.3.1\ltp_data\srl\"
[INFO] 2017-04-14 22:09:35 SRL resource is loaded.
TRACE: LTP is built
TRACE: Running 1 thread(s)
<?xml version="1.0" encoding="utf-8" ?>
<xml4nlp>
    <note sent="y" word="y" pos="y" ne="y" parser="y" wsd="n" srl="y" />
    <doc>
        <para id="0">
            <sent id="0" cont="这是">
                <word id="0" cont="这是" pos="nh" ne="S-Nh" parent="-1" relate="HED" />
            </sent>
        </para>
    </doc>
</xml4nlp>

TRACE: consume 0.016 seconds.
[INFO] 2017-04-14 22:09:35 segmentor model is released.
[INFO] 2017-04-14 22:09:35 postagger resource is released
[INFO] 2017-04-14 22:09:35 NER resource is released
[INFO] 2017-04-14 22:09:36 Parser is released
[INFO] 2017-04-14 22:09:36 SRL is released

E:\help\ltp-3.3.1\bin\Release>`

**Comment by liupan664021** [comment]
`<?xml version="1.0" encoding="utf-8" ?>
<xml4nlp>
    <note sent="y" word="y" pos="y" ne="y" parser="y" wsd="n" srl="y" />
    <doc>
        <para id="0">
            <sent id="0" cont="这是">
                <word id="0" cont="这是" pos="nh" ne="S-Nh" parent="-1" relate="HED" />
            </sent>
        </para>
    </doc>
</xml4nlp>`

**Comment by liupan664021** [comment]
对，只有两个字  这是

**Comment by endyul** [comment]
您之前用的txt不是utf-8吧。另外windows的终端编码也不是utf-8的所以出现了这个问题。
ltp的结果也是以utf-8编码输出的，如果您直接输出到windows终端肯定是乱码了。可以重定向到文件里查看

**Comment by liupan664021** [comment]
好的，谢谢！
