### ISSUE TITLE
*.model文件的内部结构不公开？

### ISSUE THREAD

**Issue by hippowon** [HIT-SCIR/ltp#223]
有一个大问题：添加自定义分词不能马上生效。我想改代码实现这个功能，但不知道程序加载的模型的结构。*.model文件的内部结构是不公开的吗？

**Comment by endyul** [comment]
自定义分词是作为分词model之外额外的feature加载进来的。相关代码在`src/segmentor/segmentor.cpp`的`Segmentor::load_lexicon`函数
