### ISSUE TITLE
识别新的NE

### ISSUE THREAD

**Issue by zemu121** [HIT-SCIR/ltp#224]
LTP中只能识别3种NE，如果想识别新的NE，应该如何添加

**Comment by liu946** [comment]
您好，可以在自己标注的多NE的语料上重新训练模型。参考[LTP使用文档-使用训练套件-命名实体识别](http://ltp.readthedocs.io/zh_CN/latest/train.html#otner)

**Comment by zemu121** [comment]
多谢
