### ISSUE TITLE
【求助】实体识别能否在已有的模型基础上增加新实体

### ISSUE THREAD

**Issue by lidawei** [HIT-SCIR/ltp#226]
希望加入自己领域的实体，用otner重新训练模型，模型能够识别自定义实体和ltp的ner.model模型实体。  
因为没有原始的标注语料，有自己领域的数据，训练的模型丢失了开放领域实体识别的能力。如

&lt;sent id="0" cont="中国电子科技大学是一所全国闻名的大学。"&gt;
                &lt;word id="0" cont="中国" pos="ns" ne="B-Ni" parent="3" relate="ATT" /&gt;
                &lt;word id="1" cont="电子" pos="n" ne="E-Ni" parent="2" relate="ATT" /&gt;
                &lt;word id="2" cont="科技" pos="n" ne="B-Ni" parent="3" relate="ATT" /&gt;
                &lt;word id="3" cont="大学" pos="n" ne="E-Ni" parent="4" relate="SBV" /&gt;
                &lt;word id="4" cont="是" pos="v" ne="B-Ni" parent="-1" relate="HED"&gt;
                    &lt;arg id="0" type="A0" beg="0" end="3" /&gt;
                    &lt;arg id="1" type="A1" beg="5" end="10" /&gt;
                &lt;/word&gt;
                &lt;word id="5" cont="一" pos="m" ne="E-Ni" parent="6" relate="ATT" /&gt;
                &lt;word id="6" cont="所" pos="q" ne="B-Ni" parent="10" relate="ATT" /&gt;
                &lt;word id="7" cont="全国" pos="n" ne="E-Ni" parent="8" relate="SBV" /&gt;
                &lt;word id="8" cont="闻名" pos="v" ne="B-Ni" parent="10" relate="ATT"&gt;
                    &lt;arg id="0" type="A0" beg="7" end="7" /&gt;
                &lt;/word&gt;
                &lt;word id="9" cont="的" pos="u" ne="E-Ni" parent="8" relate="RAD" /&gt;
                &lt;word id="10" cont="大学" pos="n" ne="O" parent="4" relate="VOB" /&gt;
                &lt;word id="11" cont="。" pos="wp" ne="S-Ni" parent="4" relate="WP" /&gt;

请问有什么办法可以解决，谢谢

**Comment by liu946** [comment]
您好，请参考 issue #224

**Comment by endyul** [comment]
抱歉，不支持增量的训练。只能分别使用ltp模型和自己训练的模型进行识别

另外ltp的模型支持人名地名机构名，不属于开放域命名实体。

**Comment by lidawei** [comment]
谢谢。

**Comment by zemu121** [comment]
不支持开放领域命名实体？只能识别人名地名机构名？

**Comment by endyul** [comment]
是的

Regards --
On Tue, Jun 20, 2017 at 14:16, zemu121 <notifications@github.com> wrote:
不支持开放领域命名实体？只能识别人名地名机构名？

**Comment by renmengxing099128** [comment]
您好，我想请问一下， 如果使用自己训练的实体识别模型进行识别，那对于后续句法依存模块的输出有影响吗？  因为我目前想把内嵌的NER模块替换为自己的模型， 但是怕影响后续句法依存分析的结果。 希望可以告知， 万分感谢！
