### ISSUE TITLE
算法

### ISSUE THREAD

**Issue by zemu121** [HIT-SCIR/ltp#227]
请问 每一个model训练过程中，具体用到了哪些算法，比如切词，使用CRF++吗？

**Comment by endyul** [comment]
您好，词法分析使用的是结构化感知器。没有使用第三方库，谢谢

**Comment by zemu121** [comment]
parameter.cpp中有与时间相关的参数，用途是什么

**Comment by endyul** [comment]
time表示迭代次数，平均感知器等算法都需要这个

**Comment by zemu121** [comment]
请问平均感知器算法是用来实现什么功能的

**Comment by endyul** [comment]
词法分析部分使用，包括分词、词性、命名实体模块

**Comment by zemu121** [comment]
好的，了解了，多谢

**Comment by zemu121** [comment]
我看过分词的源码之后，得到了以下结论，但不知道是否正确，麻烦帮我判断一下：
训练模型的过程是做一个分类器，对应BIES四种类别；对每个字进行了15种特征的映射，所以分类器的输入为15维特征，输出对应的就是BIES四种状态；
另外，我想不到如何将这个分类器与HMM联系起来，能否解释一下；
