### ISSUE TITLE
语言技术平台3.4版本的ltp-win-x64-Release.zip没办法下载，一直提示“下载失败”

### ISSUE THREAD

**Issue by 240400968** [HIT-SCIR/ltp#228]
能不能提供另外一个可用的下载链接呢？

**Comment by liu946** [comment]
请尝试使用七牛云源
http://osr393crn.bkt.clouddn.com/win_release/ltp-3.4.0-win-x86-Release.zip
http://osr393crn.bkt.clouddn.com/win_release/ltp-3.4.0-win-x64-Release.zip
