### ISSUE TITLE
无法加载SRL model

### ISSUE THREAD

**Issue by HikaruL** [HIT-SCIR/ltp#229]
我是用的是百度云下载的ltp_data, 附截图，不知道如何解决， 谢谢！
![sketch](https://user-images.githubusercontent.com/19523304/27605658-2c9085e2-5b32-11e7-81ea-24cdb867d3a9.png)

**Comment by endyul** [comment]
pyltp代码还没更新到3.4。请用上一个版本的模型

**Comment by HikaruL** [comment]
我用了3.3的ltp， 可以用了，谢谢~
