### ISSUE TITLE
安装失败：*** [thirdparty/dynet/dynet/CMakeFiles/dynet.dir/nodes.cc.o] Error 4

### ISSUE THREAD

**Issue by wwwxmu** [HIT-SCIR/ltp#230]
[ 55%] Building CXX object thirdparty/dynet/dynet/CMakeFiles/dynet.dir/mp.cc.o
[ 55%] Building CXX object thirdparty/dynet/dynet/CMakeFiles/dynet.dir/nodes.cc.o
c++: internal compiler error: 已杀死 (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
thirdparty/dynet/dynet/CMakeFiles/dynet.dir/build.make:542: recipe for target 'thirdparty/dynet/dynet/CMakeFiles/dynet.dir/nodes.cc.o' failed
make[3]: *** [thirdparty/dynet/dynet/CMakeFiles/dynet.dir/nodes.cc.o] Error 4
make[3]: Leaving directory '/home/ubuntu/weiwei/lib/ltp/build'
CMakeFiles/Makefile2:820: recipe for target 'thirdparty/dynet/dynet/CMakeFiles/dynet.dir/all' failed
make[2]: *** [thirdparty/dynet/dynet/CMakeFiles/dynet.dir/all] Error 2
make[2]: Leaving directory '/home/ubuntu/weiwei/lib/ltp/build'
Makefile:129: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/ubuntu/weiwei/lib/ltp/build'
Makefile:9: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by endyul** [comment]
可能由于内存不够

**Comment by wwwxmu** [comment]
需要多在的内存啊，我现在是1g

**Comment by endyul** [comment]
2g吧

**Comment by wwwxmu** [comment]
还真是！谢谢
