### ISSUE TITLE
otcws参数和文件说明可以详细一点吗？

### ISSUE THREAD

**Issue by ReiraLeung** [HIT-SCIR/ltp#232]
otcws的使用各参数的意义和文件的格式完全找不到。
给出的文档也好，readme也好，都是把参数列表一列就什么都不说了，每个文件的意义和格式都没有给出，用起来相当痛苦（到现在也没有跑起来嘤嘤嘤）。
希望能够给出更加详细一点的说明，拜托了。
我用的是customized-learn 这个功能，--reference 和--development后面跟的文件都是什么啊，为什么要两个，--model是生成的模型？新生成的model是在旧的基础上修改还是怎样，，，，？

**Comment by ReiraLeung** [comment]
经过一下午的琢磨，我已经能够成功运行otcws了。虽然现在遇到了新问题。
otcws customized-learn --reference 和--development后面都接人工分词好的句子所在的文件。
--model 后面要接的是生成的新model的位置，--baseline-model则是之前已经有的model。 这4个参数有了就可以正常的执行了。
比如

otcws customized-learn --reference data.txt --development data.txt --model new.model --baseline-model old.model

otcws customized-test是测试用，就是测试一下你刚才的那个新生成model是不是真实有效。
otcws customized-test --input test.txt --model new.model --baseline-model old.model
test.txt是一测试文件，里面的句子是没有分词的完整句子~也就是你要测试的句子。

结果证明训练是有效果的。原来分错的词现在分对了。

然后现在问题又来了，在LTP中，似乎没有办法使用两个model来分词，，，唉，，，训练出来的模型该怎么用啊，，，，

**Comment by ReiraLeung** [comment]
似乎是可以通过 pyltp 中CustomizedSegmentor来使用，
问题是，这儿模块有bug，很严重的bug，，两个模型并不能加载进去，，我看论坛里面很多人提问过这个问题，都没有回复，也没有解决，看来似乎是到此为止了，，，唉

**Comment by Tracy6465** [comment]
问下你data.txt中文本格式是什么样子的？我现在训练完后加载训练的模型分词的错误很高 高到离谱

**Comment by ReiraLeung** [comment]
估计是因为你模型的问题，
好的分词模型好几百兆呢，他示例里面带的分词模型很小，估计就是几个句子训练的结果。
你可以去网上找一个训练好的语料模型

**Comment by ReiraLeung** [comment]
这个确实不准，但是没有那么不准，每一句用空格分开所有的词，一行一句。你为了效果可以把某一句多重复几遍。另外，你的原来的旧模型是不是不太全面，他给的示例模型很弱的，，，最好去找一个全点儿的。

**Comment by y00282200** [comment]
问下 old.model是什么？  是ltp自带的模型库吗？ 我按照你的方式执行，读取训练集文件的时候出abort。

**Comment by y00282200** [comment]
---------------------个性化分词---------------------
CustomizedSegmentor: Model not loaded!

请问你们都碰到过这个问题没？ 
怎么解决的？

**Comment by ReiraLeung** [comment]
是旧的训练好的模型

**Comment by y00282200** [comment]
你好   CustomizedSegmentor: Model not loaded!这个错误你解决了吗

**Comment by ReiraLeung** [comment]
我记得Python 库使用customizedSegmentor就是会出错，很多人都出错。然后最后我只能使用Python 调用命令行。

**Comment by y00282200** [comment]
好吧  3Q！

**Comment by y00282200** [comment]
还请教下，我怎么能把‘’加载double_trigger失败‘’里面的double_trigger按一个词返回，LTP返回的都是double  _   trigger三个结果。用了custermized、自定义分词都没用！！

**Comment by ReiraLeung** [comment]
这个属于陌生词典吧，可惜的是ltp没有做customized 词典这个功能。实在强求的话，建议在代码里加入自己的分词矫正，就是分词以后的调整，自己加一些合并策略或者拆分策略，ltp毕竟是机器学习训练的结果，不能要求很准。

**Comment by y00282200** [comment]
你还用过其他的分词没？ 求推荐

**Comment by ReiraLeung** [comment]
没有了，抱歉，我不是专业的，当时也只是拿来一用。查一查中文分词，应该会get到不少。

**Comment by wukong0214** [comment]
@ReiraLeung   请教一个问题：模型训练命令：“otcws customized-learn --reference data.txt --development data.txt --model new.model --baseline-model old.model”  中的 “otcws”  你是从项目中哪个地方 生成的？ 
源码文件目录：/pyltp/ltp/tools/train 下，只有一个脚本：rock.sh  啊。

**Comment by zhaobinnian** [comment]
请问一下，这个训练，可以自己新增词性标注和命名实体识别吗？还是一定得是他们给定关系的那几种呢
