### ISSUE TITLE
模型檔無法下載

### ISSUE THREAD

**Issue by hanbz** [HIT-SCIR/ltp#233]
請問模型檔案的下載地點可以提供百度網盤之外的地方嗎？
百度網盤的每次下載到一半就會被強制切斷

**Comment by endyul** [comment]
抱歉，暂时还未提供其它下载源。 我们也在调研其它下载源，不知是否大陆地区之外有合适的下载源？

**Comment by icycandy** [comment]
有没有试过用手机版的百度网盘下载，据我观察，手机版要稳定得多。

**Comment by hanbz** [comment]
手機版本也是一樣無法下載，狀況一樣都是跑到70%左右就會斷掉，大陸地區之外的話google drive或是mega都滿不錯的，如果不方便上傳的話我可以協助處理，不過可能要先有ftp之類的方式讓我能取得檔案
