### ISSUE TITLE
ltp_data_v3.4.0中pisrl.model的python调用接口如何使用

### ISSUE THREAD

**Issue by Michael0134** [HIT-SCIR/ltp#235]
SRL 的使用方式有变化吗？无法加载pisrl.model？

**Comment by endyul** [comment]
pyltp暂时还没更新，请先使用上个版本

Regards --
On Mon, Jul 3, 2017 at 18:33, Michael Chen <notifications@github.com> wrote:
SRL 的使用方式有变化吗？无法加载pisrl.model？

**Comment by lileishitou** [comment]
可以有其他方式调用吗， 如java 或者c++调用pisrl.model

**Comment by endyul** [comment]
可以使用c++接口

**Comment by FannyChung** [comment]
最近可以调用3.4的模型，但是我调用语义角色分析的时候，出现：`error: cannot open model:F:\myModel\segModel\ltp_data\pisrl.model/srl.model`.，出错位置是`roles = labeller.label(words, postags, arcs)`，相关提示是`Boost.Python.ArgumentError: Python argument types in
    SementicRoleLabeller.label(SementicRoleLabeller, VectorOfString, VectorOfString, VectorOfParseResult)`，请问现在到底可以用3.4模型吗？

**Comment by liu946** [comment]
你的模型位置 参数是不对的。error: cannot open model:F:\myModel\segModel\ltp_data\pisrl.model/srl.model. 3.4.0 已经换成单文件模型。

**Comment by liu946** [comment]
此issue是和python接口相关的问题，请大家去 （https://github.com/HIT-SCIR/pyltp） 提问。
