### ISSUE TITLE
vs2017 编译源码失败

### ISSUE THREAD

**Issue by xiaxia179** [HIT-SCIR/ltp#236]
具体错误：
版本：VS2017 15.2 Release win32
编译项目dynet 时
错误	C2397	从“unsigned int”转换到“int”需要收缩转换 (编译源文件 C:\Users\XXX\Source\Repos\ltp\thirdparty\dynet\dynet\nodes.cc)	dynet	c:\users\XXX\source\repos\ltp\thirdparty\eigen\unsupported\eigen\cxx11\src\Tensor\TensorDimensions.h	287

**Comment by xiaxia179** [comment]
很抱歉，当时编译失败之后，然后再加上太忙，到了今天有时间才尝试解决问题，说一下我怎么解决的吧：
操作系统版本：windows10 x64 专业版
cmake:3.9.0-rc5
IDE:VS2017 15.2 社区版

编译报错版本：
1、cmke 选择版本的是 vs2017 win32
2、编程，除了dynet的项目，都成功了，都是上面的这个原因，具体原因分析，个人猜测可能是tensor这个库在win32模式下， 可能涉及到硬件模式，所以无法转换

解决：
使用cmake生成vs2017 win64项目之后，无需做任何更改，就能够正常编译通过

**Comment by liu946** [comment]
多谢反馈。

**Comment by realVegetable** [comment]
@xiaxia179 可以讲得具体一点吗，作为一个菜鸡，我看不懂
