### ISSUE TITLE
LTP-server启动时无法同时开启parser和ner

### ISSUE THREAD

**Issue by liu946** [HIT-SCIR/ltp#237]
我认为ltp-server启动（或访问）的时候参数设置部分有设计缺陷。导致想在单次请求中得到parser和ner的结果是不能实现的。如果启动（或访问）使用all参数，又会带来SRL部分的分析耗时。

为兼容之前的接口。建议下版本接口扩展为如下形式。
--last-stage ner|parser

**Comment by endyul** [comment]
同意
