### ISSUE TITLE
dynet 中的 ComputationGragh 对象同时只能存在一个与ltp多线程机制冲突

### ISSUE THREAD

**Issue by liu946** [HIT-SCIR/ltp#238]
如果使用多线程启动ltp-server服务器，有可能出现如下错误。

![72475a3158a38bfd73e744b3af0909fa](https://user-images.githubusercontent.com/7871150/27984674-67777d52-640e-11e7-8f28-f821cb563541.png)

**Comment by neofung** [comment]
遇到同样的问题

**Comment by liu946** [comment]
这个问题是dynet库ComputationGragh对象限制导致的，目前只能先对调用到这个类的模块加锁控制。我们会在下一个版本修复此漏洞。

**Comment by glaryaugus** [comment]
没有修复啊，依旧有这个bug

**Comment by JimXiongGM** [comment]
求修复这个bug
