### ISSUE TITLE
3.4.0版srl模块有问题

### ISSUE THREAD

**Issue by strongdog123** [HIT-SCIR/ltp#239]
![bug-1](https://user-images.githubusercontent.com/7898904/28199285-04ec268c-6897-11e7-8066-278ee267308e.jpg)

您好，我编译了ltp-test，然后从百度云下载了3.4.0版的模型文件，通过下面命令行进行测试：
ltp_test.exe --input input.txt --srl-data pisrl.model > output.txt
就出现了上面的错误。（后debug可知异常抛出在DepSRL.cpp -> LoadResource() -> boost::archive::binary_iarchive ia(in); 函数中）

后来又从七牛网下载了您编译的可执行文件包，仍然有同样的问题。

把这些文件放到linux下去执行，不报错，但是output.txt文件为空。

请问，是我的用法不对吗？

**Comment by xudekuan** [comment]
![image](https://user-images.githubusercontent.com/30224318/28671554-bb9d1d64-730f-11e7-9249-3158a65bd3a4.png)

**Comment by xudekuan** [comment]
I got this error message for 3.4.0 when I used the "all" option for --last-stage and the output was zero, but for "dp" option, it was OK.
The "all" option was OK for ltp-3.3.2-win-x64-Release,.

**Comment by albertwy** [comment]
![20170914152902](https://user-images.githubusercontent.com/17995697/30417193-83a3d42e-98f4-11e7-8e4a-fb9f7625ac39.png)
这个需要额外注意一下，你应该加上参数
`--srl-data ltp_data/pisrl.model`
for example：
`./ltp_test --threads 2 --input sentence.txt --srl-data ltp_data/pisrl.model > result.xml`

**Comment by albertwy** [comment]
到dp能通过的原因是程序没运行到需要srl model那一块。所以可以正确运行

**Comment by FannyChung** [comment]
@albertwy  你好，我把程序输出定位到了pisrl，但是也是半路出现程序终止的通告，请问能怎么办呢？
![image](https://user-images.githubusercontent.com/5433467/33826360-ac2149ea-de9f-11e7-8118-475f8e6a791a.png)
我的命令行是：`ltp_test –input huxike.txt –format json -–thread 2 --srl-data ltp_data/pisrl.model > result.xml`，前面几个模型都加载成功了。

**Comment by liu946** [comment]
问题可能是由于模型不能在windows下通用导致的，我们已经给出了win下srl的模型。请windows用户重新下载、替换模型尝试。地址可以在 ltp.ai 中找到

**Comment by xudekuan** [comment]
@liu946 谢谢您的解答，我下载了新的srl模型，在win7、win8试过，都不行，依然是上面的错误。

**Comment by liu946** [comment]
LTP docker版本已经发布了。 实在是不能编译通过的同学可以参考 https://github.com/HIT-SCIR/ltp#%E6%96%B0%E9%97%BB 使用。

**Comment by xudekuan** [comment]
谢谢您的耐心回答。请问，docker版本可以在win下使用吗？

**Comment by hscspring** [comment]
@xudekuan 可以，也只有 docker 暂时没问题，模型的确是有问题的
