### ISSUE TITLE
srl_cmdline problem

### ISSUE THREAD

**Issue by xudekuan** [HIT-SCIR/ltp#241]
![image](https://user-images.githubusercontent.com/30224318/28624897-38894a32-724d-11e7-91b0-06ff0e8fe079.png)
Is this a bug?
When a use the default setting, it doesn't work, when a use 'ltp-data/srl.model' or 'ltp-data/srl', it still does not work.

**Comment by liu946** [comment]
This is a typo mistake, please use `./srl_cmdline --pisrl-model /path/to/ltp_data/pisrl.model`

**Comment by xudekuan** [comment]
![image](https://user-images.githubusercontent.com/30224318/28650332-b823016a-72ad-11e7-835c-1ac6534ba61b.png)
thank you very much for your reply, but when I try your command, I still does not work, and the Error message is given in the above.

**Comment by xudekuan** [comment]
This is the command 
srl_cmdline.exe  --input input/4.txt  --pirsl-model ltp_data/pisrl.model >input/5.txt

**Comment by xudekuan** [comment]
或许	d	10	ADV
，	wp	1	WP
严同	nh	10	SBV
已	d	10	ADV
在	p	10	ADV
这	r	7	ATT
忙碌	a	8	ATT
中	nd	5	POB
，	wp	5	WP
学习	v	0	HED
着	u	10	RAD
人生	n	10	VOB
。	wp	10	WP
this is the data in 4.txt

**Comment by xudekuan** [comment]
![image](https://user-images.githubusercontent.com/30224318/28650518-edbe48ce-72ae-11e7-9058-a26692b5391b.png)

**Comment by liu946** [comment]
same as #239

**Comment by liu946** [comment]
The parser index should be start at index=0 such as index(ROOT)=-1 and index(“或许”)=0. You should try to decrease the third column by 1.

**Comment by xudekuan** [comment]
Thank you very much for your prompt reply. I have tried to decrease the 3rd column by 1 but it still failed, and the message was the same. I doubt that it might be due to the pisrl.model.

**Comment by xudekuan** [comment]
When i used other commandlines, it said that "Model is loaded", but this message didn't appear for srl_commandline and then the error message appeard.  Icompared with pisrl.model in ltp3.4.0 and srl.model in ltp3.3.1 and found that they were exactly the same in size and content.

**Comment by liu946** [comment]
The pisrl.model with md5 "7c31be2573b9eaa13def19698d21ae6c". You can check yours and please tell us where you download the model.

**Comment by xudekuan** [comment]
The md5 is exactly the same as yours.
I downloaded it from baiyun cloud 
https://pan.baidu.com/share/link?shareid=1988562907&uk=2738088569#list/path=%2Fltp-models

**Comment by xudekuan** [comment]
![image](https://user-images.githubusercontent.com/30224318/28659548-7b0c010c-72e2-11e7-9ab9-add5b59ccc4d.png)

**Comment by xudekuan** [comment]
![image](https://user-images.githubusercontent.com/30224318/28659574-8e575c16-72e2-11e7-96a1-d4b4d21f61b9.png)

**Comment by xudekuan** [comment]
The zip file was what I downloaded.

**Comment by xudekuan** [comment]
The other commandlines are all ok, and I used the output of the former stage as the input of the latter command.
![image](https://user-images.githubusercontent.com/30224318/28659911-9ce79cc2-72e3-11e7-91b2-a4c9b81f41cc.png)

**Comment by xudekuan** [comment]
For cws, pos and par, models have all been loeded and analyses are all ok, but for srl, no model is loaded and no result.

**Comment by liu946** [comment]
The model is right. The md5 of v3.3.1 srl.model is "8c6fa3705a778daa636c996d82ca17aa" and srl part use an directory of files as its model in the last version. The program run fine on our local environment and you can check other settings. The right output we can give is down below.
<img width="1047" alt="2017-07-27 4 03 11" src="https://user-images.githubusercontent.com/7871150/28660338-1c2e8738-72e5-11e7-8a83-10f684cd9f32.png">

**Comment by xudekuan** [comment]
Is your system Win8? I used win8, but it says msvcp140.dll is missing, so I downloaded one, it still didn't work, later I downloade a vc_redist.x64.exe and installed, the other three commandline worked well excet the srl one.

**Comment by xudekuan** [comment]
When I use the lpt_test.exe and let use  the "ltp_test.exe  --input input/1.txt --last-stage srl >input/3.txt"  option, it said "failed to load srl resource"
![image](https://user-images.githubusercontent.com/30224318/28670328-c129f298-730a-11e7-81f9-d552605c6320.png)

**Comment by xudekuan** [comment]
the other models were successfully loaded.

**Comment by xudekuan** [comment]
又换了一台机器，依然是不能运行slr.

**Comment by memeda** [comment]
（我用中文啦）
@xudekuan  因为 @liu946 没有Win的机器，所以委托我测试了一下。这个问题在win10上重现了，所以这确定是一个bug，bug定位到`pisrl.model`的反序列化部分，而这个模型的序列化、反序列化用的是binary模式，这里可能是问题的来源。后续再跟进。

**Comment by liu946** [comment]
OK，感谢 @memeda 。用text_iarchive/text_oarchive保存模型要大太多了。不过好像dynet新版本脱离了用boost存储模型了。下个版本更新dynet就应该能够解决了。

**Comment by xudekuan** [comment]
非常感谢！

**Comment by albertwy** [comment]
我今天在测试ltp-3.4.0的pisrl_cmdline时，也遇到程序无法正常结束的问题。
dep.txt是由par_cmdline【MD5：7c31be2573b9eaa13def19698d21ae6c】直接生成的。我在dep.txt文件末尾加一个空格，就可以正常运行了。
![image](https://user-images.githubusercontent.com/17995697/30358764-4266e49e-980c-11e7-8572-d0dc0d8a6261.png)
另：
help里的错误还是没有更改。

**Comment by xudekuan** [comment]
可是我测试了，还是不行。

**Comment by xudekuan** [comment]
[Uploading 1.txt…]()
[Uploading 2.txt…]()
[Uploading 3.txt…]()

**Comment by xudekuan** [comment]
[Uploading 1.txt…]()
[Uploading 2.txt…]()

[Uploading 4.txt…]()
这是我的依次次的文件

**Comment by xudekuan** [comment]
[3.txt](https://github.com/HIT-SCIR/ltp/files/1298525/3.txt)

**Comment by xudekuan** [comment]
[1.txt](https://github.com/HIT-SCIR/ltp/files/1298528/1.txt)
[2.txt](https://github.com/HIT-SCIR/ltp/files/1298527/2.txt)
[3.txt](https://github.com/HIT-SCIR/ltp/files/1298526/3.txt)
[4.txt](https://github.com/HIT-SCIR/ltp/files/1298529/4.txt)
这是我的依次的文件

**Comment by xudekuan** [comment]
如果方便的话，您能把您修改后的dep.txt上传吗？

**Comment by albertwy** [comment]
[dep.txt](https://github.com/HIT-SCIR/ltp/files/1299800/dep.txt)
[dep.txt](https://github.com/HIT-SCIR/ltp/files/1299805/dep.txt)

前一个是直接生成的，后一个我加了个空格。测试结果与之前一样，前一个不行，后一个可以。

**Comment by albertwy** [comment]
![20170913225015](https://user-images.githubusercontent.com/17995697/30384141-23fff588-9869-11e7-9534-803857710496.png)

你的4.txt测试在我这是没问题的。是不是系统的事？我不是windows。

**Comment by xudekuan** [comment]
请问您用的是什么系统。我用的是win8.

**Comment by xudekuan** [comment]
您的两个文件，在我机器上测试都不行。

**Comment by albertwy** [comment]
Linux version 4.9.0-deepin5-amd64 (yangbo@deepin.com) (gcc version 6.2.0 20161103 (Debian 6.2.0-11) ) #1 SMP PREEMPT Deepin 4.9.8-5 (2017-05-02)

太客气了，用你就行。我是Deepin系统，Linux的一个发行版。很抱歉，没能解决你的问题。

**Comment by xudekuan** [comment]
非常感谢。我装了Ubuntu，等试一下不知是否可以。

**Comment by hindsights** [comment]
我也遇到过调用时卡在srl_dosrl里的问题，后来我把heads数组里的值都减去1，再调用就正常了，感觉像是srl_dosrl里对heads的索引起点跟前面几步的不一样

**Comment by xudekuan** [comment]
请问，把heads数组里的值都减去1，具体怎么实现？

**Comment by hindsights** [comment]
for (int i = 0; i < heads.size(); ++i) {
   heads[i]--;
}
参考examples/srl.cpp代码：
  words.push_back("一把手");  postags.push_back("n"); nes.push_back("O"); parse.push_back(make_pair(2,"SBV"));
  words.push_back("亲自");    postags.push_back("d"); nes.push_back("O"); parse.push_back(make_pair(2,"ADV")); 
  words.push_back("过问");    postags.push_back("v"); nes.push_back("O"); parse.push_back(make_pair(-1,"HED"));
  words.push_back("。");      postags.push_back("wp");nes.push_back("O"); parse.push_back(make_pair(2,"WP"));
heads数组里的索引是-1代表root，而parser_parse返回的heads数组里是以0表示root的索引
在我的电脑上运行srl_dosrl时会卡住，内存占用急剧上升，最后程序出错
尝试把heads里的索引减1后，运行正常，很快就输出了结果
ltp_test则运行正常，分析其代码，发现在XML4NLP::SetParsesToSentence函数中也有将heads索引减一的操作
int XML4NLP::SetParsesToSentence(const std::vector<int> & heads,
                                 const std::vector<std::string> & deprels,
                                 int global_sid) {
  // decreasing vecHead index
  std::vector<int> d_heads;
  for (int i = 0; i < heads.size(); ++ i) {
    d_heads.push_back( heads[i] - 1 );
    // std::cout << d_heads[i] << " " << deprels[i] << std::endl;
  }

**Comment by xudekuan** [comment]
@hindsights 您的用的是什么系统？我用win8 64位，依然是不行。

**Comment by hindsights** [comment]
我用的是mac。你可以用ltp_test试一下，看它的中间数据跟你的有什么差别

**Comment by xudekuan** [comment]
我用的是win8。
