### ISSUE TITLE
调用ltp-server，希望返回的是xml的格式

### ISSUE THREAD

**Issue by wangyi1234** [HIT-SCIR/ltp#243]
调用ltp-server，希望返回的是xml的格式，data段里设置‘x’:'y'之后，对应的输入格式's’是怎样的？

**Comment by wangyi1234** [comment]
问题解决了。新版3.4.0的ltp-server里面默认输出的不是xml格式的。改用了3.3.1就好了。

**Comment by endyul** [comment]
在3.4.0之后默认返回格式是json，请求的时候使用参数f=json或者f=xml来指定返回格式

**Comment by FannyChung** [comment]
@endyul 你好，请问是在ltp_server命令参数中增加还是在传递url参数的时候增加？

**Comment by endyul** [comment]
@FannyChung 请求里增加
