### ISSUE TITLE
pyltp依存句法求助

### ISSUE THREAD

**Issue by licunlin2012** [HIT-SCIR/ltp#244]
各位老师好，我在使用pyltp进行中文句法分析后，想获取弧头和弧尾，但是pyltp中只有head和relation两个弧相关信息，不知道能否帮忙解决？
比如：系统->流畅，通过pyltp（arc.head）只能获取流畅，我想要同时获取系统，即我想获取整条弧的弧头和弧尾。
   希望得到帮助，万分感谢！

**Comment by endyul** [comment]
依存句法的结果是以root为根节点的树结构，您可以通过遍历树来获取

**Comment by licunlin2012** [comment]
能说详细点吗？我用python的for循环来遍历生成的弧，不知您说的以root为根节点的树怎么遍历？

**Comment by xudekuan** [comment]
同求^^^

**Comment by endyul** [comment]
句法分析结果每个arc就是对应句子里每个词的，arc.head是这个词的父节点

**Comment by licunlin2012** [comment]
已解决，谢谢！

**Comment by xudekuan** [comment]
@licunlin2012  能否具体分享一下您的解决方案？^^^……

**Comment by licunlin2012** [comment]
@xudekuan 根据官网给的例子，可以得到弧头，弧尾就是endyul老师说的那样“句法分析结果每个arc就是对应句子里每个词的，arc.head是这个词的父节点”

**Comment by xudekuan** [comment]
@licunlin2012 那么，请问，怎么可以通过遍树来获取呢？

**Comment by licunlin2012** [comment]
不知道，我没通过遍历树获取

**Comment by xudekuan** [comment]
能方便共享一下您是通过什么方法获取的吗？

**Comment by licunlin2012** [comment]
@xudekuan 上面说过了，你仔细研究下。

**Comment by hscspring** [comment]
按照老师的说法：  
>句法分析结果每个 arc 就是对应句子里每个词的，arc.head是这个词的父节点

那么，arc 按顺序排下来就是每个词，arc.head 是这个词的父节点。  
看起来好像是这样：

弧头 --> 弧尾|依存关系|词性|命名实体
--|--|--|--
总理 --> 国务院|ATT|ni|S-Ni
李克强 --> 总理|ATT|n|O
调研 --> 李克强|SBV|nh|S-Nh
时 --> 调研|ATT|v|O
外高桥 --> 上海|ATT|ns|B-Ns
调研 --> 外高桥|VOB|ns|E-Ns
提出 --> 时|ADV|n|O
。 --> 提出|HED|v|O
提出 --> ，|WP|wp|O
提出 --> 支持|COO|v|O
探索 --> 上海|SBV|ns|S-Ns
探索 --> 积极|ADV|a|O
支持 --> 探索|VOB|v|O
机制 --> 新|ATT|a|O
探索 --> 机制|VOB|n|O
提出 --> 。|WP|wp|O


不过和官方给的部分地方不太一样。不知道是不是哪儿搞错了。  

Code：  
```
for i in range(len(words)):
    print("%s --> %s|%s|%s|%s" % (words[int(arcs[i].head)-1], words[i], \
arcs[i].relation, postags[i], netags[i]))
```

**Comment by xudekuan** [comment]
可能数字那里，和网上的不一样，一个从0开始，一个从1开始。试一下加减1，看出来什么结果。

**Comment by hscspring** [comment]
@xudekuan 减了 1 的，否则结果更加不乐观~  
可能需要麻烦 @endyul 老师看看。

**Comment by xudekuan** [comment]
加1试试？

**Comment by xudekuan** [comment]
你把 
words[i]和
words[int(arcs[i].head)-1]
调换位置试试。

**Comment by hscspring** [comment]
@xudekuan 这又不是试出来的……而且加 1 明显超出列表了。  
我猜例子应该是手动调整了下，或者可能是最优的结果。  
等老师回复吧。

**Comment by endyul** [comment]
@hscspring 这个是正常结果。因为现在的模型相比文档示例中的有更新，所以个别弧可能会和文档中的示例不一致。另外，减一后的索引中，-1是ROOT节点，所以你第8行那里应该是ROOT->提出

**Comment by xudekuan** [comment]
你的第二列，就是箭头后面的，是弧头还是弧尾？

**Comment by sijiasen** [comment]
今天也遇到这个问题了，分享一个供参考看能不能用。
[(words[arc.head-1],arc.relation,words[i])  for i,arc in enumerate(arcs)]
