### ISSUE TITLE
如何增加可以识别的命名实体类型？

### ISSUE THREAD

**Issue by Tomato-Fish** [HIT-SCIR/ltp#245]
在使用PyLTP，命名实体识别目前可以识别人名、地名、机构名三种类型，希望可以支持更多的类型。

调用LTP的开发人员可以通过什么方式 识别出更多的命名实体类型吗？

谢谢！

**Comment by Tomato-Fish** [comment]
在[语言云的命名实体识别简介里](http://www.ltp-cloud.com/intro/#ner_how)，看到说

“用户可以很容易将实体类型拓展成品牌名、软件名等实体类型。”

但是没能找通过什么方式

**Comment by Tomato-Fish** [comment]
是这个吗？
[命名实体识别训练套件otner用法](http://ltp.readthedocs.io/zh_CN/latest/train.html#otner)

**Comment by JewelYueng** [comment]
@Tomato-Fish 您好，我也遇到了同样的问题，请问您这个问题解决了吗，可以说一下解决方法吗？
