### ISSUE TITLE
semantic dependency parsing model

### ISSUE THREAD

**Issue by lileishitou** [HIT-SCIR/ltp#246]
你好， 如何使用依存语义分析，  ltp 中有相关的API或者算法吗？

**Comment by lileishitou** [comment]
目前只有语义角色标注API，   sdp相关的在http://www.ltp-cloud.com/intro/   有说明，但是没有相关的model和API支撑。

**Comment by lileishitou** [comment]
ok

**Comment by lileishitou** [comment]
请教下  关于 转移语义依存图做语义依存分析有哪些相关的训练预料？

**Comment by endyul** [comment]
麻烦 @HITalexwang 回答一下

**Comment by lileishitou** [comment]
ok

**Comment by HITalexwang** [comment]
目前ltp中用的训练语料是SemEval 2016 Task 9的两部分训练数据合并构成的。
