### ISSUE TITLE
反应个问题

### ISSUE THREAD

**Issue by licunlin2012** [HIT-SCIR/ltp#249]
语言云的在线演示功能，经常性的崩溃，想看个例子都不行，好几天了都是这样，这两个月不知道碰到多少种这种情况了。希望及时处理！
![123](https://user-images.githubusercontent.com/20137919/29362941-86ddac22-82c0-11e7-8739-4862065a3fb1.png)

**Comment by xudekuan** [comment]
是，经常崩溃，有时候只能连上几秒钟。

**Comment by xikakera** [comment]
请问 这个问题能不能解决? 一天好像只有几秒用能用的样子

**Comment by liu946** [comment]
感谢反馈。最近LTP-cloud在线平台在进行数据库的备份清理工作，可能导致访问有些问题。目前已经完成清理，请再尝试使用。出现分析失败也可能是超过了服务器最大的访问限制，此时可以再次点击分析按钮重试。
