### ISSUE TITLE
[Bug] head shift +1 compared to previous version

### ISSUE THREAD

**Issue by rudaoshi** [HIT-SCIR/ltp#253]
2->0(LAD)
8->1(ATT)
5->2(LAD)
5->3(ATT)
2->4(COO)
7->5(LAD)
5->6(COO)
0->7(HED)

the head is 0->7, conflict with the word at position 0. Make it back to -1, please, as in previous version.

other ids in head are increased by 1. Incompatible to previous codes.

**Comment by rudaoshi** [comment]
2->0(LAD)
8->1(ATT)
5->2(LAD)
5->3(ATT)
2->4(COO)
7->5(LAD)
5->6(COO)
0->7(HED)

the head is 0->7, conflict with the word at position 0. Make it back to -1, please, as in previous version.

**Comment by liu946** [comment]
How did you get the result, from cmd_line output, ltp_server, or the web service?

**Comment by rudaoshi** [comment]
by using the c++ programming interface.
