### ISSUE TITLE
编译项目时出现cc1plus: error: unrecognized command line option "-std=c++11"

### ISSUE THREAD

**Issue by 450586509** [HIT-SCIR/ltp#254]
我的g++ --version 为：
g++ (GCC) 4.4.7 20120313 (Red Hat 4.4.7-17)

可以在不升级g++的情况下，修改这个Bug吗

**Comment by liu946** [comment]
可以尝试在cmake中临时去掉该参数。但如果是编译器不支持c++11导致的问题，修改之后也是无法通过编译的。（因为依赖的 dynet 中用到了C++11语法和特性）这种情况下如果还想“在不升级g++的情况下，修改这个Bug”，就需要把源码中所有C++11语法写成原生语法。

**Comment by kobemajian** [comment]
同样的问题，该如何解决呢？
使用内建 specs。
g++ --version 为：
COLLECT_GCC=g++
目标：x86_64-unknown-linux-gnu
线程模型：posix
gcc 版本 4.9.0 (GCC)

**Comment by kobemajian** [comment]
**# 已解决**
这里可能是因为存在多个gcc版本，且系统默认的gcc版本是低版本的。

使用find / -name gcc命令查找，发现多个目录存在gcc：
/usr/lib/gcc
/usr/local/lib/gcc
/usr/local/bin/gcc
/usr/local/libexec/gcc
/usr/bin/gcc

执行/usr/bin/gcc --version查看版本：
gcc (GCC) 4.4.7-4
/usr/local/bin/gcc --version：
gcc (GCC) 4.8.2
发现多个版本的gcc。

此时：
mv /usr/bin/gcc /usr/bin/gcc4.4.7

ln -s /usr/local/bin/gcc /usr/bin/gcc

mv /usr/bin/g++ /usr/bin/g++4.4.7

ln -s /usr/local/bin/g++ /usr/bin/g++

mv /usr/bin/cc /usr/bin/cc4.4.7

ln -s /usr/local/bin/cc /usr/bin/cc

mv /usr/bin/c++ /usr/bin/c++4.4.7

ln -s /usr/local/bin/c++ /usr/bin/c++
