### ISSUE TITLE
srl_dll.h 在ltp4j中生成有误，不能编译成功

### ISSUE THREAD

**Issue by snakecy** [HIT-SCIR/ltp#256]
ltp4j-master/jni/srl_jni.cpp:2:25: fatal error: ltp/SRL_DLL.h: No such file or directory
 #include "ltp/SRL_DLL.h"
                         ^
compilation terminated.
make[2]: *** [CMakeFiles/srl_jni.dir/jni/srl_jni.cpp.o] Error 1
make[1]: *** [CMakeFiles/srl_jni.dir/all] Error 2
make: *** [all] Error 2

最新版生成的是srl_dll.h里面有较大不同

**Comment by liu946** [comment]
ltp4j暂时不支持3.4.0版LTP
