### ISSUE TITLE
分词错误

### ISSUE THREAD

**Issue by zanghyu** [HIT-SCIR/ltp#265]
对于有无标点符号是分词会出现不同。
如：
雪花不是应该对哈啤嘛
分词结果为：雪花/不/是/应该/对/哈/啤/嘛
雪花不是应该对哈啤嘛。
分词结果为：雪花/不/是/应该/对/哈啤/嘛/。

**Comment by liu946** [comment]
模型是按照概率进行分词的，这种情况是有可能出现的，也不能做到100%正确。
