### ISSUE TITLE
解决方案生成失败

### ISSUE THREAD

**Issue by JaneWangle** [HIT-SCIR/ltp#269]
在提问之前，请确认以下几点:
- [ ] 由于您的问题可能与前任问题重复，在提交issue前，请您确认您已经搜索过之前的问题

## 问题*类型*
解决方案生成失败 
## 出错*场景*
错误	C3861	“convert”: 找不到标识符	srl_srl_static_lib	g:\lectures\计算语言学\ltp-master\ltp-master\src\srl\include\extractor\Converter.h	
## 代码片段
virtual void run() {
      unsigned num = origin_data_ref->size();
      debug.debug("Convert '%s' to '%s' start. total %u %s items", T1::getClassName().c_str(), T2::getClassName().c_str(), num, T1::getClassName().c_str());
      base::ProgressBar bar(num);
      beforeConvert();
      for (unsigned i = 0; i < num; i++) {
        convert((*origin_data_ref)[i]);
        if (bar.updateLength(i + 1))
          debug.info("(%d)%s is converted %d data generate.", i + 1, bar.getProgress(i + 1).c_str(), data.size());
      }
      afterConvert();
      debug.debug("Convert '%s' to '%s' finish. generate %u %s items", T1::getClassName().c_str(), T2::getClassName().c_str(), data.size(), T2::getClassName().c_str());
    }
## 出错*场景*
错误	C2061	语法错误: 标识符“index”	srl_pi_train	G:\Lectures\计算语言学\ltp-master\ltp-master\src\srl\common\extractor\ConverterDataToSrlPiSample.h	
## 代码片段
inline Word convertLineToWord(vector<string> & line) {
    // 0  1   2   3   4 5 6 7 8 9 0   11  1213      14
    // 4	有人	有人	有人	r	r	_	_	5	5	SBV	SBV	Y	有人.01	A1	_	_	_	_	_	_	_
    int index = lexical_cast<int>(line[0]) - 1;
    int parent = lexical_cast<int>(line[8]) - 1;
    vector<string> labels;
    // 14 位置开始论元标号
    for (int j = 14 ; j < line.size(); ++j) {
      labels.push_back(line[j]);
	}
    Word word(index, line[1], line[4], parent, line[10] ,(index <= parent ? "before" : "after"), line[12], labels);
    return word;
  }
## 出错*场景*
错误	C2259	“ConverterDataToSrlPiSample”: 不能实例化抽象类	srl_pi_train	g:\lectures\计算语言学\ltp-master\ltp-master\src\srl\pi\process\TrainSrlPi.h
## 代码片段
void initSample(vector<SrlPiSample> & samples, string file) {
    vector<DataFileName> fileName = {file};
    extractor::ConverterMultiLineFileReader fileReader;
    fileReader.init(fileName);
    fileReader.run();

    ConverterDataToSrlPiSample conv_toSample;
    conv_toSample.init(fileReader.getResult());
    conv_toSample.run();
    samples = conv_toSample.getResult();
  }
## 出错*场景*
错误	LNK1104	无法打开文件“..\..\..\lib\Debug\libsrl.lib”	srl_cmdline	G:\Lectures\计算语言学\ltp-master\ltp-master\build\src\console\LINK
## 如何复现这一错误
用CMake成功构建了项目及解决方案，但是右键解决方案点击生成报错，报了45个错误 

## 运行环境
Win10系统 Visual Studio 2015

## 期望结果
不要报错

**Comment by liu946** [comment]
尝试一下项目路径中不要使用中文。

**Comment by JaneWangle** [comment]
刚试了改成英文路径，还是会报同样的错误

**Comment by liu946** [comment]
看到有很多报错信息。编译已经出现问题是吗？能否提供第一条编译报错信息呢？

**Comment by JaneWangle** [comment]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C2061	语法错误: 标识符“index”	srl_srl_train	G:\Lectures\Computational Linguistics\ltp-master\ltp-master\src\srl\common\extractor\ConverterDataToSrlPiSample.h	36

**Comment by JaneWangle** [comment]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK1104	无法打开文件“..\..\..\lib\Debug\libsrl.lib”	srl_cmdline	G:\Lectures\Computational Linguistics\ltp-master\ltp-master\build\src\console\LINK	1	
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK1104	无法打开文件“..\..\..\lib\Debug\libsrl.lib”	ltp_test	G:\Lectures\Computational Linguistics\ltp-master\ltp-master\build\src\console\LINK	1

**Comment by liu946** [comment]
这个文件（G:\Lectures\Computational Linguistics\ltp-master\ltp-master\src\srl\common\extractor\ConverterDataToSrlPiSample.h）是跟线上版本相同没有被改动过吗？能否给出 git status 结果？

**Comment by JaneWangle** [comment]
我是直接Download下来的，没有改动

**Comment by liu946** [comment]
C2061 编译器给出的解释是：编译器发现标识符不应在此。 请确保identifier使用它之前被声明。（https://msdn.microsoft.com/zh-cn/library/yha416c7）而index标识符被声明在第30行。

**Comment by JaneWangle** [comment]
或者您能看看是不是我CMake的过程是不是有问题
1、这是下载的源码
![image](https://user-images.githubusercontent.com/30456653/33833004-1e8a3b22-deb9-11e7-99c2-c3306ca4afd0.png)
2、用CMake Configure
![image](https://user-images.githubusercontent.com/30456653/33833112-7b11ece6-deb9-11e7-9ca1-fe9d5a0f2af6.png)
3、Configure结果
![image](https://user-images.githubusercontent.com/30456653/33833225-f902a884-deb9-11e7-8414-fa548ced74f6.png)
4、继续Configure
![image](https://user-images.githubusercontent.com/30456653/33833241-0bd99cec-deba-11e7-8231-96b23eac33ec.png)
5、Generate
![image](https://user-images.githubusercontent.com/30456653/33833279-1bb80022-deba-11e7-81a0-08863c13140a.png)

**Comment by green750924** [comment]
![image](https://user-images.githubusercontent.com/39914335/40923148-9b0d4556-6846-11e8-9c74-9df9f0023667.png)
