### ISSUE TITLE
vs 2015社区版编译utf-8 的 带有中文注释的C++源文件会出错！！！惊悚

### ISSUE THREAD

**Issue by jackycaf** [HIT-SCIR/ltp#271]
在提问之前，请确认以下几点:
- [ ] 由于您的问题可能与前任问题重复，在提交issue前，请您确认您已经搜索过之前的问题

## 其他

Please ensure your issue adheres to the following guidelines:
- [ ] Search previous issues before making a new one, as yours may be a duplicate.

**Comment by liu946** [comment]
请按照issue模板提供相关信息。
