### ISSUE TITLE
可否提供把增量模型合并到基础模型的工具或接口？

### ISSUE THREAD

**Issue by BoatingZeng** [HIT-SCIR/ltp#276]
情景：我有基础模型，有增量语料库A，训练出增量模型A，现在又多了增量语料库B，希望在基础模型和增量模型A的基础上训练。那么，如果可以把增量模型A和基础模型合并成一个大模型，就可以继续下去了。以后还可以再把B合并进去，训练C。

**Comment by zhaobinnian** [comment]
同问，除了分词，其他模型都不提供再原有模型的基础上再进行训练吗
