### ISSUE TITLE
安装pyltp0.2.1失败

### ISSUE THREAD

**Issue by ZhikuoChen** [HIT-SCIR/ltp#277]
## 运行环境 win10操作系统 python3.6.3
报错:error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
c:\users\chenzhikuo\appdata\local\temp\pip-build-p9xe2kc8\pyltp\ltp\src\srl\include\extractor\Converter.h(32): error C3861: 'convert': identifier not found

**Comment by AwsomeThomas** [comment]
我在安装的时候也有这种情况，但是好像不影响使用。

**Comment by liu946** [comment]
本仓库issue只接受 C++部分相关问题，pyltp问题请到相应仓库提出。感谢。
