### ISSUE TITLE
ltp3.4在 win7 x64环境，vs2017下构建失败

### ISSUE THREAD

**Issue by qqyifeng** [HIT-SCIR/ltp#278]
vs2017用release编译，x64编译
共45错误，159警告
第一条错误;
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C3861	“convert”: 找不到标识符	srl_srl_static_lib	g:\qtfile\20171227\ltp-3.4.0\src\srl\include\extractor\Converter.h	32	

严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK1181	无法打开输入文件“..\..\..\lib\Release\libsrl.lib”	srl_cmdline	G:\QTfile\20171227\ltp-3.4.0\20171227BUILD\src\console\LINK	1	

严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C2061	语法错误: 标识符“index”	srl_pi_train	G:\QTfile\20171227\ltp-3.4.0\src\srl\common\extractor\ConverterDataToSrlPiSample.h	36	

严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C2059	语法错误:“return”	srl_pi_train	G:\QTfile\20171227\ltp-3.4.0\src\srl\common\extractor\ConverterDataToSrlPiSample.h	37	

严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C2238	意外的标记位于“;”之前	srl_pi_train	G:\QTfile\20171227\ltp-3.4.0\src\srl\common\extractor\ConverterDataToSrlPiSample.h	37	

严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C2628	“ConverterDataToSrlPiSample”后面接“void”是非法的(是否忘记了“;”?)	srl_pi_train	G:\QTfile\20171227\ltp-3.4.0\src\srl\common\extractor\ConverterDataToSrlPiSample.h	40	

严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C2065	“j”: 未声明的标识符	srl_pi_train	G:\QTfile\20171227\ltp-3.4.0\src\srl\common\extractor\ConverterDataToSrlPiSample.h	34	

严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C2061	语法错误: 标识符“index”	srl_pi_train	G:\QTfile\20171227\ltp-3.4.0\src\srl\common\extractor\ConverterDataToSrlPiSample.h	36	

严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C2059	语法错误:“return”	srl_pi_train	G:\QTfile\20171227\ltp-3.4.0\src\srl\common\extractor\ConverterDataToSrlPiSample.h	37	

这个ltp3.4现在不能在cmake之后，不能在VS2017下编译吗？

**Comment by mrkdian** [comment]
win10 x64，vs2015 同样的错误

**Comment by liu946** [comment]
在之前已经修改过此问题。@mrkdian 您是否与现仓库master代码相同呢？尤其可以检查一下 src/srl/include/extractor/Converter.h 是否相同，同时尝试修改一下词文件的编码看是否可以解决此问题。

**Comment by mrkdian** [comment]
@liu946 thanks，删去有警告的源代码文件的中文注释后，生成成功
