### ISSUE TITLE
某些情况，分词无视了 "."

### ISSUE THREAD

**Issue by InhabaTewi** [HIT-SCIR/ltp#281]
## 问题*类型*
分词功能问题

## 出错*场景*
“分词系统感觉自己特别的笨．”
运行这句话得出的结果将        “”笨 .“” 作为一个名词处理
## 如何复现这一错误
分词和标签标注功能运行上述例句
## 期望结果
笨和 . 分开

**Comment by InhabaTewi** [comment]
另外，，笨算是名词吗

**Comment by liu946** [comment]
训练语料都是正常新闻文本，句号使用的是中文“。”。故没有学到"."的信息导致。这个模型没有办法处理。可以通过自己训练模型或者预、后处理解决。

**Comment by ReactiveCJ** [comment]
不仅仅是这个情况，ltp分词经常会将标点符号，数字，跟汉字分到一起。
>帐号 <-	如果需要修改个人 邮箱、手机号码、登录密码 等信息，可以点击左下角 头像 > 我的设置 > 帐号安全 进入帐号安全设置页面进行修改。
