### ISSUE TITLE
pyltp0.2.1进行评论数据处理时出现内存占用过多的问题

### ISSUE THREAD

**Issue by zhangyudong0215** [HIT-SCIR/ltp#284]
## 问题*类型*
内存占用异常，模型运行一段时间之后内存占用突然大幅度增加。

## 出错*场景*
版本0.2.1/0.2.0 模型3.4.0
利用pyltp包的分词、词性标注、命名实体识别、依存句法分析、语义角色标注功能处理网页抓取的评论数据。在实际运行的时候我们还对数据进行了一定的预处理，比如分句、去除特殊符号之类的。初始载入模型时内存占用仅数G，但是经测验发现每次处理完20-30个content的内容之后，处理速度减慢且内存占用大幅度上升，python程序占用内存以超过每秒0.5G的速度上涨(从20G上升最后在接近90G的时候被kill掉)，且在内存溢出之前均未见增长停止。

之后我们尝试了以下的代码片段，发现问题相同且普遍存在与0.2.0和0.2.1版本的pyltp包。

但是如果对数据集进行切片，只对十个左右的content进行处理，内存占用最高不到10G，且能够顺利跑通。

## 代码片段
# coding: utf-8
import pandas as pd
import numpy as np
from pandas import Series, DataFrame
from pyltp import NamedEntityRecognizer #命名实体
from pyltp import Segmentor #分词
from pyltp import Postagger #词性标注
from pyltp import Parser    #依存句法
from pyltp import SementicRoleLabeller  #语义角色
from os import path

class LTP_word():
    ''' 
    docstring for parser_word
    deal处理文本，返回词表、词性及依存关系,语义，命名实体五个值
    release释放缓存
    '''
    def __init__(self, model_path):
        self.model_path = model_path
        self.segmentor = Segmentor()  # 分词初始化实例
        self.segmentor.load_with_lexicon(path.join(self.model_path, 'cws.model'), path.join(self.model_path, 'user_dict.txt'))
        self.postagger = Postagger() # 词性标注初始化实例
        self.postagger.load(path.join(self.model_path, 'pos.model') ) # 加载模型
        self.recognizer = NamedEntityRecognizer() # 命名实体识别初始化实例
        self.recognizer.load(path.join(self.model_path, 'ner.model'))
        self.parser = Parser() # 依存句法初始化实例 s
        self.parser.load(path.join(self.model_path, 'parser.model'))  # 加载模型
        self.labeller = SementicRoleLabeller() # 语义角色标注初始化实例
        self.labeller.load(path.join(self.model_path, 'pisrl.model'))
    def deal(self, text):  #把所有该要使用的东西都提取出来
        words =self.segmentor.segment(text)    # 分词 
        postags = self.postagger.postag(words)  # 词性标注
        netags = self.recognizer.recognize(words, postags)  #命名实体
        arcs = self.parser.parse(words, postags)  # 句法分析
        roles = self.labeller.label(words, postags, arcs)  # 语义角色标注
        return words, postags, arcs, roles, netags
    def release(self):
        self.segmentor.release()
        self.postagger.release()
        self.recognizer.release()
        self.parser.release()
        self.labeller.release()
        
data = pd.read_excel('/home/ydzhang/SRSieve_Pre/datasets_test/抓取评论.xlsx')['content']
data.head()  # 输入的数据为excel中的评论内容所在的列
ltp = LTP_word('/home/ydzhang/ltp_data_3_4_0/ltp_data_v3.4.0')
data.map(ltp.deal)

## 如何复现这一错误
尝试过多份数据，均出现了类似的错误，内存占用在pyltp处理二十到三十个句子之后急速增加。

## 运行环境
ubuntu 16.04
2 * E5-2470
96G
python3.6.3 / intelpython 3.6.3        

请问各位老师，问题究竟出在哪里，是模型不匹配还是我们使用pyltp包的方式错误？或者说内存占用确实会出现上述情况？
非常感谢！

**Comment by liu946** [comment]
按照您的叙述，可能存在python内存泄露的状况出现。问题中的content是指的什么呢？是段落个数吗？请问您每次调用接口分析的句子是多长呢？

**Comment by zhangyudong0215** [comment]
非常感谢您的回复！
每一个content都是字符串，内容如“评论集元素举例”，这就是其中一个content的全部内容。我们在调用接口之前会对这个content进行一些文本去重、去除特殊字符的处理，然后用pyltp里的SentenceSplitter.split进行分句，最后在对分出来的每个句子调用接口分析。
希望这些对于您有帮助！

**Comment by zhangyudong0215** [comment]
我今天把ltp的各个处理部分全部拆开来运行，导致内存泄漏的应该是语义角色标注功能。其他四部分运行效率很高、内存占用也没有异常。

**Comment by liu946** [comment]
可以尝试使用C++版本。

**Comment by chengming1993722** [comment]
我用的时候也存在这个问题  这个问题该怎么解决 是语义角色标注引起的内存泄漏吗

**Comment by zhangyudong0215** [comment]
目前看来只有语意角色标注可能有点问题, 其他功能都能够正常使用, 所以我现在用的是最新版的句法分析, 如果一定要用语义角色标注的话就用0.1.9.1版本pyltp.

**Comment by yongyuan923** [comment]
我在win7 64位Python3.6.3中运行的pyltp0.9.1.1，分词、词性标注、命名实体识别、句法分析都能正常使用，语义标注不能使用（已经按官网的提示安装了win下的版本），准备在Ubuntu下试试。请问Ubuntu下语义标注能正常使用？谢谢！

**Comment by zhangyudong0215** [comment]
我都是在ubuntu中使用的, 没有用过windows版本.   0.1.9.1的pyltp各部分功能使用应该都没问题.

**Comment by yongyuan923** [comment]
# 代码：
#读取文件
file=open("F:/cs/8.txt",'r',encoding='utf8')
s=file.read().encode('utf-8').strip()
print(type(s))
#分句
sent=SentenceSplitter.split(s)
print('\n'.join(sent))
#print(type(sent))

#分词
words = segmentor.segment(sent) # 分词
words_list=list(words)
print ('\t'.join(words_list))
# 出现的问题
在代码中分句了，再分词。分词的引用分词的后的sent就一直有报这种错误。请问您有遇到吗？望回复，谢谢！
 words = segmentor.segment(sent) # 分词
Boost.Python.ArgumentError: Python argument types in
    Segmentor.segment(Segmentor, VectorOfString)
did not match C++ signature:
    segment(struct Segmentor {lvalue}, class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)

**Comment by zhangyudong0215** [comment]
你把分句结果sent直接用来分词了

**Comment by yongyuan923** [comment]
谢谢您的回复！
对，这两天都卡在这个问题上，今天我把代码优化了。
现在可以实现分句，再对每句进行分词，词性标注，句法分析。
不过我是win7上实现的，所以语义标注还未能实现。还要等Ubuntu装好了才可以。
