### ISSUE TITLE
docker下加载失败

### ISSUE THREAD

**Issue by keirlee** [HIT-SCIR/ltp#285]
在执行docker load -i ltp_3_4_0.tar时，报错，貌似是hash值不对。我是用的阿里云centos，1G内存，输出如下：
833649a3e04c: Loading layer  115.5MB/115.5MB
a6a01ad8b53f: Loading layer  15.87kB/15.87kB
d2bb1fc88136: Loading layer  14.85kB/14.85kB
2bbb3cec611d: Loading layer  5.632kB/5.632kB
8600ee70176b: Loading layer  3.072kB/3.072kB
14b790afa702: Loading layer  2.379GB/2.379GB
invalid diffID for layer 5: expected "sha256:14b790afa70271835f3e17407a47e703faf34bf38913e6db3e485951a5c1aee4", got "sha256:e8132ba5ae3a0ae9b7d4d6daf8fc458aaea4cd08a36a2c07e8a2ea415510336f"

**Comment by liu946** [comment]
由于文件较大，您下载的文件错误导致的。我们更新了更小的image，同时更新了Dockerfile的构建方式，请参考新的文档。

**Comment by liu946** [comment]
https://github.com/HIT-SCIR/ltp/blob/master/Dockerfile
