### ISSUE TITLE
文档——编程接口部分图片丢失，能否更新一下？

### ISSUE THREAD

**Issue by yaleimeng** [HIT-SCIR/ltp#286]
## 问题*类型*
http://ltp.readthedocs.io/zh_CN/latest/api.html 文档里面关于Visual Studio设置include、lib、依赖项等地方没有详细说明，而是以图片取代。
但是目前图片已经丢失，无法正常加载。

## 其他
希望作者能对文档进行一下更新。

**Comment by liu946** [comment]
已补。
