### ISSUE TITLE
error C3861: 'convert': identifier not found

### ISSUE THREAD

**Issue by starbaby01** [HIT-SCIR/ltp#289]
windows 8.1系统，已安装VC++ BUILD TOOLS，下载pyltp 0.2.1解压到本地硬盘后，源码安装。
执行命令：python setup.py install
安装过程提示如下错误：
```
d:\data\pyltp-0.2.1\ltp\src\srl\include\extractor\Converter.h(35): error C3861: 'convert': identifier not found
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
```
请问这个问题怎么解决，查了其他.h文件，没有convert

**Comment by liu946** [comment]
可能是windows下编码出错导致的。可以尝试一下修改该文件编码为unicode。

**Comment by liu946** [comment]
已被最新的提交解决。

**Comment by smartsl** [comment]
Converter.h是UTF-8编码，里面又包含中文，Visual Studio不识别，删掉那两行中文注释，或者整个文件转成UTF-16编码即可

**Comment by UPC-LiuHuanyu** [comment]
> [注：我发此条回复时依然有此问题]
> Converter.h是UTF-8编码，里面又包含中文，Visual Studio不识别，删掉那两行中文注释，或者整个文件转成UTF-16编码即可

谢谢大兄弟 找到那两条中文注释了，删除之后安装成功了
