### ISSUE TITLE
有哪位朋友在mac sierra编译3.4.0版本成功吗？编译到thirdparty出错

### ISSUE THREAD

**Issue by lowpair** [HIT-SCIR/ltp#290]
在提问之前，请确认以下几点:
- [ ] 由于您的问题可能与前任问题重复，在提交issue前，请您确认您已经搜索过之前的问题
中英文都已搜索过。

## 问题*类型*

mac sieera上编译时失败。

## 代码片段
In file included from /Users/unm/other/ltp-3.4.0/thirdparty/eigen/unsupported/Eigen/CXX11/Tensor:143:
/Users/unm/other/ltp-3.4.0/thirdparty/eigen/unsupported/Eigen/CXX11/src/Tensor/TensorStorage.h:39:7: error: 
      class template partial specialization is not more specialized than the
      primary template [-Winvalid-partial-specialization]
class TensorStorage<T, FixedDimensions, Options_>
      ^
/Users/unm/other/ltp-3.4.0/thirdparty/eigen/unsupported/Eigen/CXX11/src/Tensor/TensorStorage.h:34:63: note: 
      template is declared here
template<typename T, typename Dimensions, int Options_> class TensorStorage;
                                                              ^
1 error generated.
make[3]: *** [thirdparty/dynet/dynet/CMakeFiles/dynet.dir/cfsm-builder.cc.o] Error 1
make[2]: *** [thirdparty/dynet/dynet/CMakeFiles/dynet.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [all] Error 2

## 运行环境

mac sierra

**Comment by li1191863273** [comment]
同样错误，求解

**Comment by li1191863273** [comment]
cmake version 3.10.2

**Comment by ycsqyq** [comment]
在做git submodule init 和git submodule update 之前有git checkout neoltp4j分支吗？可以尝试一下，我之前也是编译不成功，现在ok了

**Comment by cobacha** [comment]
有人解决了吗？

**Comment by magicdict** [comment]
需要修改源代码 tensorstorage.h 文件。

**Comment by jiaeyan** [comment]
同问，遇到相同问题。

**Comment by AIwem** [comment]
有没有编译好的文件共享下？谢谢各位大神

**Comment by stevenyesz** [comment]
我也出行同样的问题，我是 mac 10.14.2 版本。
[解决方案]
修改文件 tensorStorage.h 34行，
用 template<typename T, typename Dimensions, int Options_, typename empty = void> class TensorStorage;

替换原来的
template<typename T, typename Dimensions, int Options_> class TensorStorage;

再次执行 make 就 ok。

**Comment by jiaziberry** [comment]
> 我也出行同样的问题，我是 mac 10.14.2 版本。
> [解决方案]
> 修改文件 tensorStorage.h 34行，
> 用 template<typename T, typename Dimensions, int Options_, typename empty = void> class TensorStorage;
> 
> 替换原来的
> template<typename T, typename Dimensions, int Options_> class TensorStorage;
> 
> 再次执行 make 就 ok。

我用了您说的方法，可是还是不行，得到以下信息。

error: unable to open output file
      'build/temp.macosx-10.9-x86_64-3.7/src/pyltp.o': 'Operation not permitted'
1 error generated.
error: command 'clang++' failed with exit status 1
