### ISSUE TITLE
在用Java调用ltp接口时要不要先启动一个本地的ltp服务？

### ISSUE THREAD

**Issue by glaryaugus** [HIT-SCIR/ltp#292]
我把jar包和dll文件加入程序里运行不报错也没结果。是要先启动一个ltp服务吗？还有如果是要先启动一个服务，怎么指定这个服务的地址和端口呢，示例java代码中没有连接服务的代码。求解

**Comment by liu946** [comment]
ltp4j中的代码不需要ltp服务。

**Comment by glaryaugus** [comment]
用maven编译ltp4j时执行mvn -Dmaven.test.skip=true
报：
[ERROR] Failed to execute goal com.github.maven-nar:nar-maven-plugin:3.5.0:nar-v
alidate (default-nar-validate) on project ltp4j: Could not launch cmd.exe /X /C
"link /?": Error while executing process. Cannot run program "link": CreateProce
ss error=2, 系统找不到指定的文件。 -> [Help 1]

怎么解决呢？

**Comment by glaryaugus** [comment]
在linux上编译ltp4j报这个错误
[ERROR] Failed to execute goal com.github.maven-nar:nar-maven-plugin:3.5.0:nar-compile (default-nar-compile) on project ltp4j: NAR: Include path not found: com.github.maven_nar.IncludePath@6de6faa6 -> [Help 1]

**Comment by glaryaugus** [comment]
编译完了、要把ltp-master改名字成ltp，然后放到ltp4j-master的src/main/c++/下面，然后编译就行了，对g++版本还有要求

**Comment by liu946** [comment]
git submodel 应该会正常命名并放到指定位置的。g++需要支持C++11。

**Comment by glaryaugus** [comment]
奇怪、在linux上编译的jar包用不了。而且想问一下，用linux编译的，它的c++代理程序的目录应该指定到哪一级？我指定了好几个目录都报错了。
