### ISSUE TITLE
请问ltp是否有新词发现功能，假如要用于特定领域，如何有效的生成领域词典

### ISSUE THREAD

**Issue by yuye2133** [HIT-SCIR/ltp#293]
在提问之前，请确认以下几点:
- [x] 由于您的问题可能与前任问题重复，在提交issue前，请您确认您已经搜索过之前的问题

## 其他

Please ensure your issue adheres to the following guidelines:
- [x] Search previous issues before making a new one, as yours may be a duplicate.

**Comment by liu946** [comment]
目前没有此功能。关于 “如何有效的生成领域词典”，可以参考相关论文进行尝试。
