### ISSUE TITLE
ltp4j在eclipse中可以使用，但打成jar包之后就报错

### ISSUE THREAD

**Issue by glaryaugus** [HIT-SCIR/ltp#294]
一直报：
Exception in thread "main" java.lang.UnsatisfiedLinkError: no segmentor_jni in java.library.path
的错误，请问怎么解决呢。

而且打进去的ltp4j.jar好像也没起作用，因为会报java.lang.NoClassDefFoundError的错误，我是直接打开lotp4j.jar,把class文件直接拷进程序中才不报错的。但第一个错误一直有，不知道怎么解决。

**Comment by glaryaugus** [comment]
在eclipse中用了ltp4j的程序，可以打成jar包运行吗？

**Comment by xsy0rival** [comment]
请问你是怎么把ltp4j编译成jar包的？

**Comment by glaryaugus** [comment]
我在windows上编译失败了，在linux上编译成功了，但linux上的jar包和.so文件没用。所以最后在CSDN下的。
链接在这：https://download.csdn.net/download/weixin_40029454/10313019

**Comment by glaryaugus** [comment]
你如果想自己试着编译，编译文档在这：http://ltp4j.readthedocs.io/en/neoltp4j/install.html

**Comment by xsy0rival** [comment]
非常感谢你的答复，我是跟着文档做的，一直到后面mvn时出错，提示缺少maven插件，所以我去下了。发现还是没用，就有点搞不懂了，我再试试吧！

发送自 Windows 10 版邮件应用

发件人: glaryaugus
发送时间: 2018年4月2日 10:12
收件人: HIT-SCIR/ltp
抄送: xsy0rival; Comment
主题: Re: [HIT-SCIR/ltp] ltp4j在eclipse中可以使用，但打成jar包之后就报错 (#294)

你如果想自己试着编译，编译文档在这：http://ltp4j.readthedocs.io/en/neoltp4j/install.html
