### ISSUE TITLE
401 error: unauthorized

### ISSUE THREAD

**Issue by estelll** [HIT-SCIR/ltp#295]
已注册，也受到了api_key。
复制粘贴的官网的python代码，用的python3所以稍稍对代码做了点更改：
`if __name__ == '__main__':
    url_get_base = "http://api.ltp-cloud.com/analysis/"
    args = { 
        'api_key' : '邮件发给我的API KEY',
        'text' : '我是中国人。',
        'pattern' : 'dp',
        'format' : 'plain'
    }
    data = urllib.parse.urlencode(args)
    result = urllib.request.urlopen(url_get_base, data.encode()) # POST method
    content = result.read().strip()
    print(content)`

但是报了401 error：
`401: UNAUTHORIZED`

**Comment by liu946** [comment]
有时因为网络原因，后端通信出现问题导致注册失败。现已更新数据库，你可以再次尝试。
