### ISSUE TITLE
NER识别问题（未达到期望结果）

### ISSUE THREAD

**Issue by ycsqyq** [HIT-SCIR/ltp#296]
在提问之前，请确认以下几点:
- [yes ] 由于您的问题可能与前任问题重复，在提交issue前，请您确认您已经搜索过之前的问题

## 问题*类型*

NER识别问题
## 出错*场景*

分析公告标题“上海家化：国浩律师（上海）事务所关于上海家化联合股份有限公司2015年股权激励计划部分限制性股票回购并注销及部分股票期权注销的法律意见书”没有达到预期结果，
预期输出：
国浩律师（上海）事务所
上海家化联合股份有限公司
实际输出：
上海家化联合股份有限公司
## 代码片段
public static void main(String[] args) {
        NER ner = null;
        Segmentor segmentor = null;
        Postagger postagger = null;
        try {
            Long s1 = System.currentTimeMillis();
            ner = new NER();
            segmentor = new Segmentor();
            postagger = new Postagger();
            if (ner.create("model/ner.model") < 0
                    || segmentor.create("model/cws.model") < 0
                    || postagger.create("model/pos.model") < 0) {
                System.err.println("load failed");
                return;
            }
            System.out.println("库加载完毕" + (System.currentTimeMillis() - s1));
            s1 = System.currentTimeMillis();
            String str = "上海家化：国浩律师（上海）事务所关于上海家化联合股份有限公司2015年股权激励计划部分限制性股票回购并注销及部分股票期权注销的法律意见书";
            List<String> words = segmentorStr(segmentor, str);
            System.out.println("分词完毕" + (System.currentTimeMillis() - s1));
            List<String> tags = postaggerWords(postagger, words);
            List<String> ners = nerWords(ner, words, tags);
            List<String> entityList = jointNer(words, ners);
            entityList.forEach(System.out::println);
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            if (ner != null) {
                ner.release();
            }
            if (segmentor != null) {
                segmentor.release();
            }
            if (postagger != null) {
                postagger.release();
            }
        }
    }

    

    public static List<String> segmentorStr(Segmentor segmentor, String str) {
        List<String> words = new ArrayList<>();
        int size = segmentor.segment(str, words);
        return words;
    }

    public static List<String> postaggerWords(Postagger postagger, List<String> words) {
        List<String> tags = new ArrayList<>();
        int size = postagger.postag(words, tags);
        return tags;
    }

    public static List<String> nerWords(NER ner, List<String> words, List<String> tags) {
        List<String> ners = new ArrayList<>();
        int size = ner.recognize(words, tags, ners);
        return ners;
    }

    public static List<String> jointNer(List<String> words, List<String> ners) {
        List<String> nerEntityList = new ArrayList<>();
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < words.size(); i++) {
            String ner = ners.get(i);
            if (ner.equals("O")) {
                continue;
            }
            String word = words.get(i);
            String[] neArray = ner.split("-");
            if (neArray[1].equals("Ni")) {
                sb.append(word);
                if (neArray[0].equals("E") || neArray[0].equals("S")) {
                    nerEntityList.add(sb.toString());
                    sb = new StringBuilder();
                }

            }
        }
        return nerEntityList;
    }
## 如何复现这一错误

直接运行main方法
## 运行环境

mac os version 10.12.6
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
## 期望结果

国浩律师（上海）事务所
上海家化联合股份有限公司
## 其他
请大佬们给予解答，谢谢！

**Comment by liu946** [comment]
参阅 http://ltp.ai/faq.html

**Comment by ycsqyq** [comment]
@liu946 您好，在常见问题或issues中没有找到类似这个问题的答案，请指教

**Comment by liu946** [comment]
LTP使用的都是概率模型，不能百分之百的正确识别所有命名实体。

**Comment by glxe** [comment]
现在命名实体可以自定义词典么？
