### ISSUE TITLE
语义结果对应词语输出错误

### ISSUE THREAD

**Issue by yongyuan923** [HIT-SCIR/ltp#299]
## *语义结果对应词语输出错误*

==========语义角色标注==========
[dynet] random seed: 2790205779
[dynet] allocating memory: 2000MB
[dynet] memory allocation done.
7 TMP:(0,6)A1:(9,14)
7 TMP:(国务院总理李克强)A1:(研上海外高桥时)   #与在线语言云所标注的不一致
9 A1:(10,10)
9 A1:(上海)

## 出错*场景*
  print(role.index, "".join(
        ["%s:(%s)" % (arg.name, input_str[arg.range.start:arg.range.end+2]) for arg in role.arguments]))#输出的记过与想要的不符合
# 代码片段

 做语义角色标注
print('='*10+'语义角色标注'+'='*10)
srl_model_path = os.path.join(LTP_DATA_DIR, 'pisrl.model')  

from pyltp import SementicRoleLabeller
labeller = SementicRoleLabeller() # 初始化实例
labeller.load(srl_model_path)  # 加载模型

arcs 使用依存句法分析的结果
roles = labeller.label(words, postags, arcs)  # 语义角色标注

 打印结果
for role in roles:
    print (role.index, "".join(
        ["%s:(%d,%d)" % (arg.name, arg.range.start, arg.range.end) for arg in role.arguments]))
    print(role.index, "".join(
        ["%s:(%s)" % (arg.name, input_str[arg.range.start:arg.range.end+2]) for arg in role.arguments]))
labeller.release()  # 释放模型

## 运行环境

win7 
Python3.6
 pyltp0.2.1
 lpt3.4.0

## 期望结果

7 TMP:(0,6)A1:(9,14)
7 TMP:(国务院总理李克强调研上海外高桥时)A1:(支持上海积极探索新机制) 
9 A1:(10,10)
9 A1:(上海)

请问，这输出对应词语的语句该怎么写，才能输出最终期望的结果。谢谢，望回复！

**Comment by liu946** [comment]
请问分析的整句话是什么？

**Comment by yongyuan923** [comment]
谢谢您的回复！
国务院总理李克强调研上海外高桥时提出，支持上海积极探索新机制。

**Comment by liu946** [comment]
输出应该就是 7 TMP:(0,6)A1:(9,14) 9 A1:(10,10) 没错啊。如下。
![2018-04-03 3 07 19](https://user-images.githubusercontent.com/7871150/38234527-b8e9b068-3750-11e8-9f2c-21823d38e1bb.png)
每行第一个数字表示谓词索引，后面每个论元内部是论元包含的词的索引。

**Comment by yongyuan923** [comment]
嗯嗯，输出的索引是对的。就是输出每个论元内部索引所对应的词的时候，就不对了。
==========语义角色标注==========
[dynet] random seed: 942249560
[dynet] allocating memory: 2000MB
[dynet] memory allocation done.
7 TMP:(0,6)A1:(9,14)
7 TMP:(国务院总理李克强)A1:(研上海外高桥时)**——就是输出索引所对应的词这里不对。**
9 A1:(10,10)
9 A1:(上海)**——这里输出就是对的**
[Finished in 4.4s]

**Comment by liu946** [comment]
这部分不是LTP输出的包含的结果啊。是你们程序自己索引出的结果啊。

**Comment by yongyuan923** [comment]
谢谢！嗯，LTP输出的结果是正确的。
我是想输出索引对应的词，所以想问问有没有同学知道这个输出句该怎么写，才正确输出。

**Comment by liu946** [comment]
哦，是这样。下面的写法，可以满足你的要求。其中words是pyltp的 example/example.py 中的分词器返回。
```
for role in roles:
    print(role.index, "".join(
            ["%s:(%d,%d)" % (arg.name, arg.range.start, arg.range.end) for arg in role.arguments]))
    print(role.index,"".join(
            ["%s:(%s)" % (arg.name, ''.join(words[arg.range.start:arg.range.end + 1])) for arg in role.arguments]))

```
输出为：
```
国务院	总理	李克强	调研	上海	外高桥	时	提出	，	支持	上海	积极	探索	新	机制	。
ni	n	nh	v	ns	ns	n	v	wp	v	ns	a	v	a	n	wp
2:ATT	3:ATT	4:SBV	7:ATT	6:ATT	4:VOB	8:ADV	0:HED	8:WP	8:COO	13:SBV	13:ADV	10:VOB	15:ATT	13:VOB	8:WP
S-Ni	O	S-Nh	O	B-Ns	E-Ns	O	O	O	O	S-Ns	O	O	O	O	O
7 TMP:(0,6)A1:(9,14)
7 TMP:(国务院总理李克强调研上海外高桥时)A1:(支持上海积极探索新机制)
9 A1:(10,10)
9 A1:(上海)
```

**Comment by yongyuan923** [comment]
谢谢您！
