### ISSUE TITLE
语义依存图会加入进来吗？

### ISSUE THREAD

**Issue by yaleimeng** [HIT-SCIR/ltp#301]
http://ltp.ai/ 在线演示中的语义依存树、图似乎是新功能，有加入ltp仓库的计划吗？

**Comment by liu946** [comment]
目前这部分不打算开源。抱歉。

**Comment by yaleimeng** [comment]
好的，明白了。谢谢。

**Comment by ericxsun** [comment]
@liu946 能分享下语义依存图的算法逻辑吗？谢谢

**Comment by liu946** [comment]
@ericxsun  可以参考一下 https://mp.weixin.qq.com/s/QvHTUAicgf257wQwkRn3cQ
