### ISSUE TITLE
访问ltp服务器报错404

### ISSUE THREAD

**Issue by glaryaugus** [HIT-SCIR/ltp#302]
软件环境：CentOS Linux release 7.2.1511 (Core)
软件包：ltp-3.4.0.tar.gz

启动命令：./bin/ltp_server --port 6666 --thread 4 & 
测试命令：curl -d "s=我爱北京" "http://10.135.3.21:6666/ltp"
   报错如下：HTTP/1.1 404 Not Found
                     Content-Length: 30
                     Connection: close

**Comment by liu946** [comment]
是否可以提供一下程序日志。

**Comment by liu946** [comment]
@snow0102 请更新到最新版本，重新编译。
