### ISSUE TITLE
关于ltp_server的参数不可用

### ISSUE THREAD

**Issue by zhangxuejing201609** [HIT-SCIR/ltp#306]
您好，我想问一下，ltp_server的参数比如 --last-stage 为什么没有起作用 当我设置--last-stage为 ws
命令如下： ./bin/ltp_server --last-stage ws   但是在调用时，会有错误
postag(): in LTP::postag, failed to init a postagger
ner(): in LTP::ner, failed to perform postag preprocess
srl(): in LTP::srl, failed to perform ner preprocess

为什么还会提示关于其他模型的问题呢

**Comment by liu946** [comment]
确认一下ltp的版本或者拼写错误等问题。我们使用此参数正常运行，不能复现你的问题。
