### ISSUE TITLE
docker 运行ltp 如何使用外部词典

### ISSUE THREAD

**Issue by kyjo2014** [HIT-SCIR/ltp#307]
按照文档使用docker window运行tlp。并设置了词典所在盘为共享盘。
运行命令
`docker run -d -p 8080:12345 ltp/ltp /ltp_server --last-stage all --segmentor-lexicon I:/dic.txt`
但是分词效果没有变化。
词典内容：
安全气囊  n nz 
错误分词效果：
```
 <sent id="0" cont="安全气囊">
                <word id="0" cont="安全" />
                <word id="1" cont="气囊" />
            </sent>
```
期待分词效果：
```
 <sent id="0" cont="安全气囊">
                <word id="0" cont="安全气囊" />
          
            </sent>
```

**Comment by liu946** [comment]
http://ltp.ai/faq.html
