### ISSUE TITLE
docker cannot start sever

### ISSUE THREAD

**Issue by ghost** [HIT-SCIR/ltp#311]
## question type

docker start fail

## inside the docker

root@0bc654d8c8dc:/# ./ltp_server --log-level 0 --port 12345                   
[INFO] 2018-05-30 09:28:52 Loading segmentor model from "ltp_data/cws.model" ...
[INFO] 2018-05-30 09:28:53 segmentor model is loaded.t 12345 --thread 2 --last-st
[INFO] 2018-05-30 09:28:53 Loading postagger model from "ltp_data/pos.model" ...
[INFO] 2018-05-30 09:28:54 postagger model is loaded
[INFO] 2018-05-30 09:28:54 Loading NER resource from "ltp_data/ner.model"
[INFO] 2018-05-30 09:28:54 NER resource is loaded.
[INFO] 2018-05-30 09:28:54 Loading parser resource from "ltp_data/parser.model"
[INFO] 2018-05-30 09:28:54 parser is loaded.
[INFO] 2018-05-30 09:28:54 Loading srl resource from "ltp_data/pisrl.model"
[dynet] random seed: 810983242
[dynet] allocating memory: 2000MB
Killed

## outside the docker
bogon:ltp silcon$ docker run -p 8080:12345 ltp/ltp /ltp_server --last-stage all
[INFO] 2018-05-30 09:42:22 Loading segmentor model from "ltp_data/cws.model" ...
[INFO] 2018-05-30 09:42:23 segmentor model is loaded.
[INFO] 2018-05-30 09:42:23 Loading postagger model from "ltp_data/pos.model" ...
[INFO] 2018-05-30 09:42:23 postagger model is loaded
[INFO] 2018-05-30 09:42:23 Loading NER resource from "ltp_data/ner.model"
[INFO] 2018-05-30 09:42:23 NER resource is loaded.
[INFO] 2018-05-30 09:42:23 Loading parser resource from "ltp_data/parser.model"
[INFO] 2018-05-30 09:42:24 parser is loaded.
[INFO] 2018-05-30 09:42:24 Loading srl resource from "ltp_data/pisrl.model"
[dynet] random seed: 1309473413
[dynet] allocating memory: 2000MB
bogon:ltp silcon$

**Comment by Guoli-Lyu** [comment]
I have encounter the exactly same error. My case maybe a little different.

Inside the bash shell of the docker, the server exits complaining **Illegal instruction**.

```bash
root@0b17c9551742:/# /ltp_server --port 12345 --log-level 0 all
[INFO] 2018-09-05 06:54:32 Loading segmentor model from "ltp_data/cws.model" ...
[INFO] 2018-09-05 06:54:32 segmentor model is loaded.
[INFO] 2018-09-05 06:54:32 Loading postagger model from "ltp_data/pos.model" ...
[INFO] 2018-09-05 06:54:33 postagger model is loaded
[INFO] 2018-09-05 06:54:33 Loading NER resource from "ltp_data/ner.model"
[INFO] 2018-09-05 06:54:33 NER resource is loaded.
[INFO] 2018-09-05 06:54:33 Loading parser resource from "ltp_data/parser.model"
[INFO] 2018-09-05 06:54:33 parser is loaded.
[INFO] 2018-09-05 06:54:33 Loading srl resource from "ltp_data/pisrl.model"
[dynet] random seed: 2816297491
[dynet] allocating memory: 2000MB
Illegal instruction
```
