### ISSUE TITLE
请问老师，“训练依存句法模型报错：Assertion `index >= 0 && index < size()' failed.” 如何解决啊？

### ISSUE THREAD

**Issue by wukong0214** [HIT-SCIR/ltp#312]
## 源码下载到本机，依存句法分析训练套件nndepparser
 如下执行：
/ltp/ltp/tools/train$ ./nndepparser learn --embedding /home/*/ltp/ltp/tools/train/sample/parser/example.bin --model nndpp.model --reference /home/*/ltp/ltp/tools/train/sample/parser/example-train.conll   --development /home/*/ltp/ltp/tools/train/sample/parser/example-train.conll --verbose

## 出错*场景*
[WARNING] 2018-06-05 20:55:52 decoder: not initialized, please check if the root dependency relation is correct set by --root.
....
[INFO] 2018-06-05 20:55:52 #: generated training samples for 10% sentences.
[INFO] 2018-06-05 20:55:52 #: generated 16 training samples.
[INFO] 2018-06-05 20:55:52 #: start to load embedding ...
[INFO] 2018-06-05 20:55:52 #: loaded 20% embeddings.
....
[INFO] 2018-06-05 20:55:52 #: loaded 100% embeddings.
[INFO] 2018-06-05 20:55:52 #: loaded 110% embeddings.
[INFO] 2018-06-05 20:55:52 report: 1 embedding is loaded.
[INFO] 2018-06-05 20:55:52 classifier: E(50,24)
.....
[INFO] 2018-06-05 20:55:52 classifier: saved(200,149)
....
[INFO] 2018-06-05 20:55:52 classifier: fix embedding = false
[INFO] 2018-06-05 20:55:52 report: classifier is initialized.
nndepparser: /home/*/ltp/ltp/thirdparty/eigen/Eigen/src/Core/DenseCoeffsBase.h:425: Eigen::DenseCoeffsBase<Derived, 1>::Scalar& Eigen::DenseCoeffsBase<Derived, 1>::operator()(Eigen::Index) [with Derived = Eigen::Matrix<double, -1, 1>; Eigen::DenseCoeffsBase<Derived, 1>::Scalar = double; Eigen::Index = long int]: Assertion `index >= 0 && index < size()' failed.
已放弃 (核心已转储)

请问老师  我哪个地方配置出错？依存句法模型不能自己训练吗？

**Comment by liu946** [comment]
需要指定root参数。

**Comment by liu946** [comment]
看样子你的训练数据有问题，其中有索引位置超过了句子长度。
