### ISSUE TITLE
启动LTP-server出错。

### ISSUE THREAD

**Issue by shaohua1977** [HIT-SCIR/ltp#325]
在提问之前，请确认以下几点:
- [x] 由于您的问题可能与前任问题重复，在提交issue前，请您确认您已经搜索过之前的问题

## 问题*类型*

无法启动
## 出错*场景*

启动ltp-server时

## 代码片段
[INFO] 2018-10-29 09:30:40 Loading segmentor model from "ltp_data/cws.model" ...
[INFO] 2018-10-29 09:30:42 segmentor model is loaded.
[INFO] 2018-10-29 09:30:42 Loading postagger model from "ltp_data/pos.model" ...
[INFO] 2018-10-29 09:30:49 postagger model is loaded
[INFO] 2018-10-29 09:30:49 Loading NER resource from "ltp_data/ner.model"
[INFO] 2018-10-29 09:30:49 NER resource is loaded.
[INFO] 2018-10-29 09:30:49 Loading parser resource from "ltp_data/parser.model"
[INFO] 2018-10-29 09:30:56 parser is loaded.
[INFO] 2018-10-29 09:30:56 Loading srl resource from "ltp_data/pisrl.model"
[dynet] random seed: 2117113883
[dynet] allocating memory: 2000MB
[dynet] memory allocation done.
terminate called after throwing an instance of 'boost::archive::archive_exception'
  what():  incompatible native format - size of long
Aborted (core dumped)

## 如何复现这一错误

运营这一句的时候出现错误：
/home/ubuntu/ltp-3.4.0/bin/ltp_server --port 9090 --threads 10

## 运行环境

 Ubuntu 16.04.5 LTS (GNU/Linux 4.16.4-041604-generic x86_64)

## 期望结果

这是什么情况？怎么解决？

**Comment by AlongWY** [comment]
模型加载失败，请检查模型
