### ISSUE TITLE
docker对中文返回404error

### ISSUE THREAD

**Issue by jimmy-walker** [HIT-SCIR/ltp#326]
## 问题*类型*

利用docker中的LTP的测试命令：curl -d "s=他点头表示同意我的意见。&f=xml&t=all" http://192.168.99.100:8080/ltp
返回错误：
HTTP/1.1 404 Not Found
Content-Length: 30
Connection: close

Error 404: Not Found
Not Found
## 出错*场景*

只有在中文时出错，英文时运行正常：curl -d "s=hello world&f=xml&t=all" http://192.168.99.100:8080/ltp
猜测是由于在docker终端和cmd终端的编码问题。
但是更改cmd编码为utf-8后，仍然对中文的输入，出现相同问题。
## 运行环境

windows 7 64位
## log 
[INFO] 2018-10-30 08:10:36 Loading segmentor model from "ltp_data/cws.model" ...
[INFO] 2018-10-30 08:10:36 segmentor model is loaded.
[INFO] 2018-10-30 08:10:36 Loading postagger model from "ltp_data/pos.model" ...
[INFO] 2018-10-30 08:10:37 postagger model is loaded
[INFO] 2018-10-30 08:10:37 Loading NER resource from "ltp_data/ner.model"
[INFO] 2018-10-30 08:10:37 NER resource is loaded.
[INFO] 2018-10-30 08:10:37 Loading parser resource from "ltp_data/parser.model"
[INFO] 2018-10-30 08:10:37 parser is loaded.
[INFO] 2018-10-30 08:10:37 Loading srl resource from "ltp_data/pisrl.model"
[dynet] random seed: 461465297
[dynet] allocating memory: 2000MB
[dynet] memory allocation done.
[INFO] 2018-10-30 08:10:39 srl resource is loaded.
[INFO] 2018-10-30 08:10:39 Resources loading finished.
[INFO] 2018-10-30 08:10:39 Start listening on port [12345]...
[WARNING] 2018-10-30 08:31:25 Failed string validation check

## 期望结果
请问如何解决中文问题呢？大家是怎么使得中文保持utf8输入的？

**Comment by AIwem** [comment]
同问，现在都用不了

**Comment by zhyongwei** [comment]
直接通过程序用post方法调用即可。英文可以正常处理说明服务安装没有问题，可能是字符编码或其他问题导致的404错误。
