### ISSUE TITLE
LTP-cloud注册页面404

### ISSUE THREAD

**Issue by LittlePrettyLiars** [HIT-SCIR/ltp#328]
在提问之前，请确认以下几点:
- [ ] 由于您的问题可能与前任问题重复，在提交issue前，请您确认您已经搜索过之前的问题

## 其他

Please ensure your issue adheres to the following guidelines:
- [ ] Search previous issues before making a new one, as yours may be a duplicate.

**Comment by AlongWY** [comment]
该页面的注册功能已经删除了，所以无法进行注册
