### ISSUE TITLE
关于依存句法分析训练套件nndepparser的embedding文件

### ISSUE THREAD

**Issue by yy8623977** [HIT-SCIR/ltp#329]
**问题类型**
依存句法训练一直报错

 **出错场景**
训练时出现的错误如下: 
[INFO] 2018-11-22 16:21:45 eval: start evaluating ...
[WARNING] 2018-11-22 16:21:45 decoder: not initialized, please check if the root dependency relation is correct set by --root.
[WARNING] 2018-11-22 16:21:45 unknown transition in transform(int&): -1
[WARNING] 2018-11-22 16:21:45 unknown transition in transit: 0-0
段错误

**代码片段**
训练的代码如下: 
./nndepparser learn \
--embedding /home/huan.he/LTP/ltp-3.4.0/tools/train/sample/parser/example.bin \
--model /home/huan.he/LTP/ltp-3.4.0/tools/train/myDp.model \
--reference /home/huan.he/LTP/ltp-3.4.0/tools/train/sample/parser/example-train.conll \
--development /home/huan.he/LTP/ltp-3.4.0/tools/train/sample/parser/example-train.conll \
--verbose

其中embedding和reference丶development三个文件都是下载下来的源文件

**如何复现这一错误**
按上面讲的方法可以复现这一错误

**运行环境**
centos7    ltp-3.4.0版本

**期望结果**
期望能训练成功

**其他**
embedding词向量文件是怎么训练出来的, 用的什么工具和什么方法

**Comment by pzf2019** [comment]
你的根的依存关系不是ROOT，应当改为具体的你的标记，比如HED
