### ISSUE TITLE
如何在./tools/train/ 中编译生成./otcws文件

### ISSUE THREAD

**Issue by Fireboyar** [HIT-SCIR/ltp#338]
在提问之前，请确认以下几点:
- [x] 由于您的问题可能与前任问题重复，在提交issue前，请您确认您已经搜索过之前的问题

## 其他

Please ensure your issue adheres to the following guidelines:
- [x] Search previous issues before making a new one, as yours may be a duplicate.

**Comment by Fireboyar** [comment]
now  i found the method

**Comment by MioYvo** [comment]
@Fireboyar 请问如何解决哒？
