### ISSUE TITLE
命名实体识别是使用biLstm+CRF吗？

### ISSUE THREAD

**Issue by glshi** [HIT-SCIR/ltp#339]
命名实体识别是使用biLstm+CRF吗？

**Comment by mockingbird-gan** [comment]
不是，这个平台的作者在论文里说是用最大熵模型，附上论文供查询：Wanxiang Che, Zhenghua Li, Ting Liu. LTP: A Chinese Language Technology Platform. In Proceedings of the Coling 2010:Demonstrations. 2010.08, pp13-16, Beijing, China.
