### ISSUE TITLE
使用ltp sever时，如何设置参数返回xml格式的结果

### ISSUE THREAD

**Issue by wangshuo6699** [HIT-SCIR/ltp#340]
在提问之前，请确认以下几点:
- [ ] 由于您的问题可能与前任问题重复，在提交issue前，请您确认您已经搜索过之前的问题

## 其他

Please ensure your issue adheres to the following guidelines:
- [ ] Search previous issues before making a new one, as yours may be a duplicate.

**Comment by zhyongwei** [comment]
“f=xml”表示返回xml格式的结果，“f=json”表示返回json格式的结果。
