### ISSUE TITLE
一类分词错误改如何解决：”套得住钻裙底的咸猪手吗“ 的分词结果为 “套 的 住钻 裙 底 的 咸猪手 吗”

### ISSUE THREAD

**Issue by yangxipeng** [HIT-SCIR/ltp#341]
一类分词错误改如何解决：”套得住钻裙底的咸猪手吗“ 的分词结果为 “套 的 住钻 裙 底 的 咸猪手 吗”
将住和钻合并到一起了，这个有办法解决吗

**Comment by AlongWY** [comment]
ltp4已经解决了你这个错误？ltp3可以尝试加词表
