### ISSUE TITLE
docker镜像安装失败

### ISSUE THREAD

**Issue by stevewyl** [HIT-SCIR/ltp#344]
## 问题*类型*
docker镜像build失败

## 出错*场景*
使用Dockerfile构造docker镜像的时候连续三次出现源代码make错误
第一行出错的代码
ltp/thirdparty/eigen/Eigen/src/Core/arch/AVX512/PacketMath.h:663:56: error: expected ',' or ';' before '__m256'

## 如何复现这一错误
附上安装的打印信息 https://gist.github.com/stevewyl/6626c5006746864895099c7bc77f2756

## 运行环境
CentOS Linux release 7.4.1708

## 其他
直接下载镜像文件的时候网页出现 {"error":"no such domain"}错误

**Comment by stevewyl** [comment]
未知原因，在另外一台服务器上build成功

**Comment by danielwonght** [comment]
我也遇到了这个问题，在本地build镜像的时候是可以过的，但是在服务器上就出问题。请问找到具体原因了吗？
