### ISSUE TITLE
python没有返回结果

### ISSUE THREAD

**Issue by Lanme** [HIT-SCIR/ltp#348]
linux系统，python：3.5，pyltp版本(pip install pyltp：pyltp.cpython-35m-x86_64-linux-gnu.so)

分词代码：

> from pyltp import Segmentor
segmentor = Segmentor()  # 初始化实例
segmentor.load("./nlp/ltp_data/3.3.0/ltp_data/cws.model")  # 加载模型
words = segmentor.segment("元芳你怎么看")  # 分词
print ("|".join(words))
segmentor.release()  # 释放模型

运行结果：
没有报错，也没有返回任何结果。

**Comment by AlongWY** [comment]
欢迎使用4.0版本
