### ISSUE TITLE
Web演示界面和使用pyltp以及web api得到的结果不同。

### ISSUE THREAD

**Issue by MingxuanLiu** [HIT-SCIR/ltp#351]
在提问之前，请确认以下几点:
- [√] 由于您的问题可能与前任问题重复，在提交issue前，请您确认您已经搜索过之前的问题

## 问题*类型*

使用pyltp和web api进行分词和http://ltp.ai/demo.html上面的结果不同，请问演示界面使用的模型是哪个版本的模型？

**Comment by HaodongBAI** [comment]
我也有类似的问题，感觉网站上的更加准确

**Comment by webryan** [comment]
请问 网站版本用的 模型和代码是哪个版本？

**Comment by AlongWY** [comment]
欢迎使用4.0版本，之前的模型应该是讯飞接口，使用了更大规模语料进行训练
