### ISSUE TITLE
ltp4.0 暂时不支持Python3.6及以下版本

### ISSUE THREAD

**Issue by Zhi-lin** [HIT-SCIR/ltp#357]
出现如下问题：TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

请更新到python3.7及以上

**Comment by zhangmianhongni** [comment]
这个不支持python3.6是在是太恶心了，实际项目落地很少有这么高版本的，难道就是为了个语法糖不向下兼容么

**Comment by AlongWY** [comment]
新版本已经支持 Python 3.6 和 Pytorch 1.2.0
