### ISSUE TITLE
ltp4在pypi上安装有问题

### ISSUE THREAD

**Issue by wykdg** [HIT-SCIR/ltp#358]
刚想试一下ltp4，缺乏安装说明
在pip上安装
pip install ltp
ERROR: Could not find a version that satisfies the requirement torch==1.5.0 (from ltp) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch==1.5.0 (from ltp)

直接 pip install -r requirements.txt也有问题。
希望能进一步完善，谢谢

**Comment by wykdg** [comment]
自行解决了

**Comment by AlongWY** [comment]
我们通常是先使用conda安装pytorch，然后再安装ltp4的

**Comment by wykdg** [comment]
明白，我也这么装装上了
