### ISSUE TITLE
自动下载的模型载入失败/载入自己下载的模型

### ISSUE THREAD

**Issue by shm007g** [HIT-SCIR/ltp#363]
我下载了tiny.tgz 和small.tgz 放到cache目录还是无法用。

看源码，要用一个hash的名字。

**Comment by shm007g** [comment]
查看transformers/file_util.py 文件的`url_to_filename`可以得到tiny模型的url可以获得下载后的hash名称
'10d3ebbc187d33375530f67752e143f8693eab038ce2c611df93c969cd69d857'，然后改tiny.tgz为这个就可以加载了。

**Comment by shm007g** [comment]
附代码
```
import ltp.ltp
import transformers.file_utils

url_map = ltp.ltp.model_map
print(url_map)
for k, v in url_map.items():
    print(k, v, transformers.file_utils.url_to_filename(v))
```

**Comment by chendh16** [comment]
我也遇到这个问题 请问下载到的cache目录是哪个？

**Comment by carfly** [comment]
在 ~/.cache/torch/ltp 目录

-Wanxiang (http://ir.hit.edu.cn/~car/)

**Comment by carfly** [comment]
> 我下载了tiny.tgz 和small.tgz 放到cache目录还是无法用。
> 
> 看源码，要用一个hash的名字。

可以在创建LTP对象的时候指定：
ltp = LTP("解压后的文件夹名")

**Comment by shm007g** [comment]
> > 我下载了tiny.tgz 和small.tgz 放到cache目录还是无法用。
> > 看源码，要用一个hash的名字。
> 
> 可以在创建LTP对象的时候指定：
> ltp = LTP("解压后的文件夹名")

不行的,比如我把small.tgz解压到`/Users/shm/Downloads/ltp_data_4`，然后
- 写 `ltp = LTP("/Users/shm/Downloads/ltp_data_4/small", local_files_only=True)` 会出 `IsADirectoryError: [Errno 21] Is a directory: '/Users/shm/Downloads/ltp_data_4/small'`. 
-  写`ltp = LTP("/Users/shm/Downloads/ltp_data_4/small/ltp.model", local_files_only=True)`会报错 `AttributeError: 'LTP' object has no attribute 'tokenizer'`. 

不读源码真没法加载。。。

**Comment by HugeDog** [comment]
同样遇到了模型加载问题，我查看源码修改了部分代码以确保可以运行。
### 已知问题
1. 加载预训练模型参数无法对齐（4.0.9版本更新fix了该bug，不过我没有测试，我的版本是4.0.8）
    >修改ltp/ltp.py
    >```
    >line123: self.model.load_state_dict(ckpt['model'], strict=False)
    >```
2. 预训练模型资源无法找到
    >修改ltp/models/multi_task_model.py
    >```
    >line44: self.pretrained = self.create_pretrained('hfl/chinese-electra-small-discriminator', config=config, freeze=freeze)
    >```

**Comment by shm007g** [comment]
6月19日更新的ltp==4.0.3.post1，比较方便本地加载模型了。ltp = LTP(模型目录)
