### ISSUE TITLE
请问 LTP 4.0 有没有 visualize dependency, NER, SRL 等的功能？

### ISSUE THREAD

**Issue by logan-siyao-peng** [HIT-SCIR/ltp#364]
你好，我看教程中有一些语法和语义的可视化图片。请问这些parser results 有没有自带的输出可视化结果的功能？谢谢了。

**Comment by carfly** [comment]
我们提供了在线的可视化功能：http://ltp.ai/demo.html

-Wanxiang (http://ir.hit.edu.cn/~car/)
