### ISSUE TITLE
本地加载模型问题

### ISSUE THREAD

**Issue by shm007g** [HIT-SCIR/ltp#369]
@carfly 提到可以
> 可以在创建LTP对象的时候指定：
ltp = LTP("解压后的文件夹名")

但是我操作下来是不行的：比如我把small.tgz解压到`/Users/shm/Downloads/ltp_data_4`，然后
- 写 `ltp = LTP("/Users/shm/Downloads/ltp_data_4/small", local_files_only=True)` 会出 `IsADirectoryError: [Errno 21] Is a directory: '/Users/shm/Downloads/ltp_data_4/small'`. 看源码ltp.py-80行是`torch.load(path, map_location=self.device)`所以需要写模型地址而不是目录。
-  写`ltp = LTP("/Users/shm/Downloads/ltp_data_4/small/ltp.model", local_files_only=True)`会报错 `AttributeError: 'LTP' object has no attribute 'tokenizer'`，看源码ltp.py-80行猜测是少了一行`self.tokenizer = AutoTokenizer.from_pretrained(resolved_archive_path, use_fast=True)`
- 写 `resolved_archive_path = "/Users/shm/Downloads/ltp_data_4/small/ltp.model"
ltp = LTP(resolved_archive_path)
ltp.tokenizer = AutoTokenizer.from_pretrained(resolved_archive_path, use_fast=True)`，会报一个utf-8的编码错误～～

随便一试就是错误 ;(  不晓得是我火星了还是啥

**Comment by carfly** [comment]
更新ltp到最新版本试试。

**Comment by shm007g** [comment]
@carfly 更新到 `ltp==4.0.3.post1`可以使用，之前新安装的`ltp-4.0.2`不行，这2天就发布新版本了 ;)

**Comment by mengdodo** [comment]
老兄，这个问题解决没，readme说是
```
其中 path 可接受的路径为下载下来的模型或者解压后的文件夹路径
```
看源代码怎么是到具体文件 
```
/python3.8/site-packages/ltp/frontend.py

if path in model_map or is_remote_url(path) or os.path.isfile(path):
```
难道是就不能本地加载模型，只能别名拉取吗
