### ISSUE TITLE
batch处理的时候，分词会引入空字符

### ISSUE THREAD

**Issue by Nipi64310** [HIT-SCIR/ltp#376]
![image](https://user-images.githubusercontent.com/31469418/86356593-19639500-bc9f-11ea-9e68-c08a2a72a705.png)
可以看到分词得到的结果，会有字段为空，从最后2个文本可以看到文本末尾并没有空格
这样会影响后续句法分析的结果，参见第1条文本

**Comment by carfly** [comment]
谢谢反馈！不过看起来不是batch的问题，好像是句尾问号的问题。我们尽快处理。

-Wanxiang (http://ir.hit.edu.cn/~car/)

**Comment by Nipi64310** [comment]
> 问题，好像是句尾问

把出问题的句子拿出来，单独分词，得到的结果是正常的, 。
问题复现可以用这个list   ['200斤能支撑吗','可以tui广你家产品么？','邮政单号麻烦给我一下']   第一个句子会出问题。

**Comment by carfly** [comment]
好的，尽快搞定！

-Wanxiang (http://ir.hit.edu.cn/~car/)
