### ISSUE TITLE
pyltp-LTP3.4版本在ARM64架构上编译后，句法依存分析出来的结果是不一样的

### ISSUE THREAD

**Issue by zhangmianhongni** [HIT-SCIR/ltp#378]
pyltp-LTP3.4版本在ARM64架构上编译后，句法依存分析出来的结果是不一样的，LTP4.0有在ARM架构上测试过么，无论是LTP3.4还是LTP4.0能出一个ARM能正确使用的版本么

**Comment by AlongWY** [comment]
如果可以在 arm 平台正确安装 pytorch，我想应该是可以正确使用的，不过这个想法还没有验证过
