### ISSUE TITLE
LTP4.0.4版本与demo得出不一样的结果，请问如何能获取demo版本代码？

### ISSUE THREAD

**Issue by jiaziberry** [HIT-SCIR/ltp#381]
感谢前辈的努力工作。@carfly @AlongWY 

我已在Pycharm里通过pip下载了最新的ltp4.0.4版本，可是在跑数据的时候出现了一些偏误。在与ltp demo版核对时发现两个版本给出的数据不一样。详情请参见附件。 对我来说，demo版本更准确一些。所以请问如何能获取demo版本代码或者结果呢？
万分感谢！

**LTP demo 结果**

<img width="497" alt="WechatIMG4890" src="https://user-images.githubusercontent.com/62764856/87225558-e5b2fa00-c385-11ea-8c4e-835263a6bf0b.png">

**ltp4.0.4的结果：**

['你', '对', '历史', '有', '点', '认识']
['r', 'p', 'n', 'v', 'q', 'v']
SDP
0 5 AGT
1 2 mRELA
2 5 CONT
3 5 mDEPD
4 5 MEAS
5 -1 Root
DEP
0 5 SBV
1 5 ADV
2 1 POB
3 5 ADV
4 5 ATT
5 -1 HED
('认识', 'ADV')

**Comment by AlongWY** [comment]
我们的demo使用的是base模型，你那边可否检查一下

**Comment by jiaziberry** [comment]
> 我们的demo使用的是base模型，你那边可否检查一下

嗯嗯，果然可以了，非常非常感谢！你们咋这么优秀呢！
