### ISSUE TITLE
【Q】更新的4.0.5版本pip安装时好像有问题

### ISSUE THREAD

**Issue by Fourha** [HIT-SCIR/ltp#384]
win10系统，使用pip install ltp==4.0.5在pytorch环境下安装最新版的ltp时出现报错，不知道是什么原因呢？

**ERROR:** `Could not find a version that satisfies the requirement pygtrie==2.3.3tqdm (from ltp==4.0.5) (from versions: 0.9.1, 0.9.2, 0.9.3, 1.0, 1.1, 1.2, 2.0, 2.1, 2.2, 2.3, 2.3.2, 2.3.3)`

**ERROR**:` No matching distribution found for pygtrie==2.3.3tqdm (from ltp==4.0.5)`

**Comment by Fourha** [comment]
检查了tqdm和pygtrie，都是符合requirement文件要求的版本

**Comment by carfly** [comment]
setup.py文件有个小问题，马上能解决。

**Comment by Fourha** [comment]
> setup.py文件有个小问题，马上能解决。
谢谢~，请问现在的4.0.5.post1版本可以pip安装了吗？刚才试了一下pip install ltp==4.0.5.post1好像还不能正常使用
**ERROR**:` Could not find a version that satisfies the requirement ltp==4.0.5.post1 (from versions: 4.0.2, 4.0.3, 4.0.3.post1, 4.0.4, 4.0.5)`
**ERROR**: `No matching distribution found for ltp==4.0.5.post1`

**Comment by Fourha** [comment]
已经用源码安装成功了，谢谢~~(●'◡'●)~~

**Comment by Cathy-t** [comment]
同样在win10下使用pip安装，出现以下问题：

ERROR: Command errored out with exit status 1:
     command: 'g:\vgmt\venv\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Cathy\\AppData\\Local\\Temp\\pip-install-xf1kopf0\\cytoolz\\setup
.py'"'"'; __file__='"'"'C:\\Users\\Cathy\\AppData\\Local\\Temp\\pip-install-xf1kopf0\\cytoolz\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('
"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Cathy\AppData\Local\Temp\pip-record-e8co4g3s\install-record.txt' --sing
le-version-externally-managed --compile --install-headers 'g:\vgmt\venv\include\site\python3.7\cytoolz'
         cwd: C:\Users\Cathy\AppData\Local\Temp\pip-install-xf1kopf0\cytoolz\
    Complete output (59 lines):
    [1/5] Cythonizing cytoolz/utils.pyx
    [2/5] Cythonizing cytoolz/dicttoolz.pyx
    [3/5] Cythonizing cytoolz/functoolz.pyx
    [4/5] Cythonizing cytoolz/itertoolz.pyx
    [5/5] Cythonizing cytoolz/recipes.pyx
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\cytoolz
    copying cytoolz\compatibility.py -> build\lib.win-amd64-3.7\cytoolz
    copying cytoolz\utils_test.py -> build\lib.win-amd64-3.7\cytoolz
    copying cytoolz\_signatures.py -> build\lib.win-amd64-3.7\cytoolz
    copying cytoolz\_version.py -> build\lib.win-amd64-3.7\cytoolz
    copying cytoolz\__init__.py -> build\lib.win-amd64-3.7\cytoolz
    creating build\lib.win-amd64-3.7\cytoolz\curried
    copying cytoolz\curried\exceptions.py -> build\lib.win-amd64-3.7\cytoolz\curried
    copying cytoolz\curried\operator.py -> build\lib.win-amd64-3.7\cytoolz\curried
    copying cytoolz\curried\__init__.py -> build\lib.win-amd64-3.7\cytoolz\curried
    copying cytoolz\dicttoolz.pyx -> build\lib.win-amd64-3.7\cytoolz
    copying cytoolz\functoolz.pyx -> build\lib.win-amd64-3.7\cytoolz
    copying cytoolz\itertoolz.pyx -> build\lib.win-amd64-3.7\cytoolz
    copying cytoolz\recipes.pyx -> build\lib.win-amd64-3.7\cytoolz
    copying cytoolz\utils.pyx -> build\lib.win-amd64-3.7\cytoolz
    copying cytoolz\cpython.pxd -> build\lib.win-amd64-3.7\cytoolz
    copying cytoolz\dicttoolz.pxd -> build\lib.win-amd64-3.7\cytoolz
    copying cytoolz\functoolz.pxd -> build\lib.win-amd64-3.7\cytoolz
    copying cytoolz\itertoolz.pxd -> build\lib.win-amd64-3.7\cytoolz
    copying cytoolz\recipes.pxd -> build\lib.win-amd64-3.7\cytoolz
    copying cytoolz\utils.pxd -> build\lib.win-amd64-3.7\cytoolz
    copying cytoolz\__init__.pxd -> build\lib.win-amd64-3.7\cytoolz
    creating build\lib.win-amd64-3.7\cytoolz\tests
    copying cytoolz\tests\dev_skip_test.py -> build\lib.win-amd64-3.7\cytoolz\tests
    copying cytoolz\tests\test_compatibility.py -> build\lib.win-amd64-3.7\cytoolz\tests
    copying cytoolz\tests\test_curried.py -> build\lib.win-amd64-3.7\cytoolz\tests
    copying cytoolz\tests\test_curried_toolzlike.py -> build\lib.win-amd64-3.7\cytoolz\tests
    copying cytoolz\tests\test_dev_skip_test.py -> build\lib.win-amd64-3.7\cytoolz\tests
    copying cytoolz\tests\test_dicttoolz.py -> build\lib.win-amd64-3.7\cytoolz\tests
    copying cytoolz\tests\test_docstrings.py -> build\lib.win-amd64-3.7\cytoolz\tests
    copying cytoolz\tests\test_doctests.py -> build\lib.win-amd64-3.7\cytoolz\tests
    copying cytoolz\tests\test_embedded_sigs.py -> build\lib.win-amd64-3.7\cytoolz\tests
    copying cytoolz\tests\test_functoolz.py -> build\lib.win-amd64-3.7\cytoolz\tests
    copying cytoolz\tests\test_inspect_args.py -> build\lib.win-amd64-3.7\cytoolz\tests
    copying cytoolz\tests\test_itertoolz.py -> build\lib.win-amd64-3.7\cytoolz\tests
    copying cytoolz\tests\test_none_safe.py -> build\lib.win-amd64-3.7\cytoolz\tests
    copying cytoolz\tests\test_recipes.py -> build\lib.win-amd64-3.7\cytoolz\tests
    copying cytoolz\tests\test_serialization.py -> build\lib.win-amd64-3.7\cytoolz\tests
    copying cytoolz\tests\test_signatures.py -> build\lib.win-amd64-3.7\cytoolz\tests
    copying cytoolz\tests\test_tlz.py -> build\lib.win-amd64-3.7\cytoolz\tests
    copying cytoolz\tests\test_utils.py -> build\lib.win-amd64-3.7\cytoolz\tests
    running build_ext
    building 'cytoolz.dicttoolz' extension
    系统找不到指定的路径。
    creating build\temp.win-amd64-3.7
    creating build\temp.win-amd64-3.7\Release
    creating build\temp.win-amd64-3.7\Release\cytoolz
    cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ig:\vgmt\venv\include -IC:\Users\Cathy\AppData\Local\Programs\Python\Python37\include -IC:\Users\Cathy\AppData\Local\Programs\Python\Pyt
hon37\include /Tccytoolz/dicttoolz.c /Fobuild\temp.win-amd64-3.7\Release\cytoolz/dicttoolz.obj
    error: command 'cl.exe' failed: No such file or directory
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'g:\vgmt\venv\scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Cathy\\AppData\\Local\\Temp\\pip
-install-xf1kopf0\\cytoolz\\setup.py'"'"'; __file__='"'"'C:\\Users\\Cathy\\AppData\\Local\\Temp\\pip-install-xf1kopf0\\cytoolz\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(
__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Cathy\AppData\Local\Temp\pip-record-e8
co4g3s\install-record.txt' --single-version-externally-managed --compile --install-headers 'g:\vgmt\venv\include\site\python3.7\cytoolz' Check the logs for full command output.

请问是什么原因呢？

**Comment by carfly** [comment]
看起来是没有找到 cl.exe，可能需要安装Visual Studio。

-Wanxiang (http://ir.hit.edu.cn/~car/)

**Comment by Cathy-t** [comment]
好的，谢谢，请问有版本的兼容要求么？

**Comment by carfly** [comment]
试一下最新版本吧。

-Wanxiang (http://ir.hit.edu.cn/~car/)

**Comment by Cathy-t** [comment]
安装了2019的Visual Studio后，仍然是出现了同样的问题，无法安装成功。

**Comment by carfly** [comment]
如果还不行，那就试试用Anaconda3吧。

-Wanxiang (http://ir.hit.edu.cn/~car/)

**Comment by Cathy-t** [comment]
嗯嗯，我最后把我电脑上Visual Studio的版本梳理了一下，装上了，之前可能装的有点儿乱，谢谢啦~
