### ISSUE TITLE
分词引入额外的空格

### ISSUE THREAD

**Issue by JiaweiSheng** [HIT-SCIR/ltp#386]
您好！
在对以下句子进行分词时,
_"在2016年,中南文化又以4.5亿元现金完成了对版权运营公司北京新华先锋文化传媒有限公司的全资收购"_
分词结果
_[['在', '2016年', ',', '中南', '文化', '又', '以', '4 . 5亿', '元', '现金', '完成', '了', '对', '版权', '运营', '公司', '北京', '新华', '先锋', '文化', '传媒', '有限公司', '的', '全资', '收购']]_
可以看到，'4 . 5亿'引入了新的空格，而原文中没有这个空格，这给将分词结果向原文对齐带来了问题，您看一下

**Comment by airaria** [comment]
我也遇到了类似的问题，比如：
"高德菲·哈罗德·哈代在《一个数学家的自白》一书中表明他相信单单是美学上的意义"
分词结果
[["高德菲 ·哈罗德 ·哈代", ... ]]
在符号"·"前引入了额外的空格，的确会给对齐带来一些麻烦

**Comment by AlongWY** [comment]
这个问题是为了在两个英文单词之间插入空格而设计的，未考虑到这种情况，我们将很快解决该问题
