### ISSUE TITLE
ltp4.0版本使用cuda加速存在显存无法释放的问题。

### ISSUE THREAD

**Issue by NicolasCookie** [HIT-SCIR/ltp#387]
我使用的是LTP的批量cuda加速函数，第一次跑1w没问题。但是发现每次跑完一轮，显卡的显存无法释放，再跑两轮显存就爆了，你们有遇到过这种问题的吗？

|   0  GeForce RTX 208...  Off  | 00000000:3B:00.0 Off |                  N/A |
| 33%   40C    P8    22W / 250W |  10896MiB / 10989MiB |      0%      Default

from ltp import LTP,
ltp = LTP('tiny', device='cuda')

**Comment by AlongWY** [comment]
你是否进行了多次初始化ltp或者对hidden进行了保留？

**Comment by NicolasCookie** [comment]
感谢。又测试了一下，是我的疏忽造成的问题。
