### ISSUE TITLE
请问下训练和fine-tune的examples吗？

### ISSUE THREAD

**Issue by MrRace** [HIT-SCIR/ltp#389]
请问有
1. 基于自己语料进行训练的example代码吗? 比如 基于自己本地语料训练形如`Tiny(v2)`的模型。
2. 基于自己的语料进行fine-tune的example代码吗？
谢谢！

**Comment by AlongWY** [comment]
即将发布

**Comment by AlongWY** [comment]
已经发布了自己训练的 example，暂时没有 finetune 的 example

**Comment by pactera-song** [comment]
> 已经发布了自己训练的 example，暂时没有 finetune 的 example
请问支持fine-tune吗

**Comment by AlongWY** [comment]
当然，你直接接入自己的数据训练就行了，ltp载入模型的逻辑都是开源的，freeze pretrained的参数可以保证其他任务指标不降，其他的和你正常finetune没啥区别

**Comment by pactera-song** [comment]
> 当然，你直接接入自己的数据训练就行了，ltp载入模型的逻辑都是开源的，freeze pretrained的参数可以保证其他任务指标不降，其他的和你正常finetune没啥区别

多谢回复
