### ISSUE TITLE
one bug?

### ISSUE THREAD

**Issue by zshy1205** [HIT-SCIR/ltp#391]
测试代码如下
`
from ltp import LTP

data_dir = '../data/'

ltp = LTP('/local/download/ltp4_v2_base.model')# 默认自动下载并加载 Small 模型
txts = ["随着十·一长假的结束"]
words, hidden = ltp.seg(txts)
postags = ltp.pos(hidden)
print(words)
`
输出如下：
[['随着', '十 ·一', '长假', '的', '结束']]
输出结果在“十一”那个word里面多了一个空格，请问这是一个bug吗？

**Comment by AlongWY** [comment]
该问题已经在最新版本中解决 #386

**Comment by zshy1205** [comment]
感谢~
