### ISSUE TITLE
onnx时间问题？

### ISSUE THREAD

**Issue by Nipi64310** [HIT-SCIR/ltp#393]
hello 请问为什么相同的数据,1个batch, batch_size=256，fastltp要1.3s+, ltp确只需要130+ms
![image](https://user-images.githubusercontent.com/31469418/88910189-aa259480-d28e-11ea-850c-6d53c9c180de.png)
![image](https://user-images.githubusercontent.com/31469418/88910256-c6c1cc80-d28e-11ea-8d6b-850896c1db4b.png)

**Comment by AlongWY** [comment]
主要是 onnx 分词之后取完hidden之后还要再送回到 GPU，之后如果能保证全部都在 GPU 里面，应该就会更快了，现在IO是瓶颈，CPU onnx 会更快一点
