### ISSUE TITLE
分词时意外退出

### ISSUE THREAD

**Issue by wjx-git** [HIT-SCIR/ltp#397]
安装方式： pip install ltp

环境：ubuntu 20.4,      anaconda 5.2.0,      pycharm 2020.1.3,     python 3.6,    pytorch  1.4

问题描述：
`ltp = LTP()`
 `seg, hidden = ltp.seg(["他叫汤姆去拿外衣。"])`

报错：Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

但是下列代码运行正常，
`ltp = LTP()`
`sents = ltp.sent_split(["他叫汤姆去拿外衣。", "汤姆生病了。他去了医院。"])`
`print(sents)`

该怎么解决？？？

上述是在虚拟机上的ubuntu系统操作，切换到win10系统，ltp 能正常使用，且环境一致。

**Comment by AlongWY** [comment]
python 版本 / pytorch 版本？

**Comment by wjx-git** [comment]
> python 版本 / pytorch 版本？

python 3.6
pytorch 1.4.0

**Comment by AlongWY** [comment]
是否是PyQt或者内存不足的问题？

**Comment by wjx-git** [comment]
内存不足原因。
8g内存，居然跑不了实例！！
debug发现是output = input.mutal(weight.t()) 这一行爆内存。
input size: (1, 11, 128)
weight size: (256, 128)
