### ISSUE TITLE
分詞結果

### ISSUE THREAD

**Issue by kk12837** [HIT-SCIR/ltp#399]
你好，

我用了以下 句子去做分析，在 3.4的 DOCKER 和 http://ltp.ai/demo.html 的結果不一樣。

'8月13日本港新增69宗新冠肺炎確診個案，65宗屬本地感染，衞生防護中心公布最新確診患者居住大廈，包括半山區豫苑、北角港濤軒、何文田峰景軒、紅磡黃埔花園、美孚新邨6期等'

請問如何 令到它們一樣呢？

謝謝

**Comment by AlongWY** [comment]
ltp.ai 部署的是 ltp4 base model，目前docker版本未更新到4.0版本
