### ISSUE TITLE
batch时报错

### ISSUE THREAD

**Issue by Damcy** [HIT-SCIR/ltp#401]
`ltp.seg()`对输入的list有什么限制吗？
在跑大批量的数据时，batch从2-10都会中断报错。只有batch为1的时候才能正常跑完。
单测过一个batch，是没问题。
报错是list out of range
猜想是不是内部会对batch做concat还是啥。

**Comment by AlongWY** [comment]
你可以坚持一下每个句子前后是不是有空格之类的东西

**Comment by Damcy** [comment]
恩，我去检查以下。使用seg接口，也会丢失句子中原本的空格信息。
这个issue先关闭了。
