### ISSUE TITLE
调用分词报错“Missing key(s) in state_dict: "pretrained.embeddings.position_ids”

### ISSUE THREAD

**Issue by chuanhuayang** [HIT-SCIR/ltp#403]
官方demo，运行报下面的错误，有人遇到过吗

    LTP_PATH = "/mnt/d/ltp_base"
    ltp = LTP(path = LTP_PATH) # 其中 tiny-tgz-extracted 是 tiny.tgz 解压出来的文件夹
    segment, _ = ltp.seg(["他叫汤姆去拿外衣。"])
    # [['他', '叫', '汤姆', '去', '拿', '外衣', '。']]

RuntimeError: Error(s) in loading state_dict for SimpleMultiTaskModel:
	Missing key(s) in state_dict: "pretrained.embeddings.position_ids".

**Comment by pactera-song** [comment]
同样的问题，不知道为什么一样的代码居然运行不过

**Comment by about608504** [comment]
我也遇到了一样的问题

**Comment by cl011** [comment]
修改源码ltp.py 验证可以解决. 
self.model.load_state_dict(ckpt['model']) => self.model.load_state_dict(ckpt['model'], strict=False)

**Comment by cl011** [comment]
> 修改源码ltp.py 验证可以解决.
> self.model.load_state_dict(ckpt['model']) => self.model.load_state_dict(ckpt['model'], strict=False)



> 官方demo，运行报下面的错误，有人遇到过吗
> 
> ```
> LTP_PATH = "/mnt/d/ltp_base"
> ltp = LTP(path = LTP_PATH) # 其中 tiny-tgz-extracted 是 tiny.tgz 解压出来的文件夹
> segment, _ = ltp.seg(["他叫汤姆去拿外衣。"])
> # [['他', '叫', '汤姆', '去', '拿', '外衣', '。']]
> ```
> 
> RuntimeError: Error(s) in loading state_dict for SimpleMultiTaskModel:
> Missing key(s) in state_dict: "pretrained.embeddings.position_ids".



修改源码ltp.py 验证可以解决.
self.model.load_state_dict(ckpt['model']) => self.model.load_state_dict(ckpt['model'], strict=False)

**Comment by AlongWY** [comment]
这个问题是由于 huggingface/transformers 更新了模型的结构导致的，增加了一个带有默认值的position_ids，现在已经更新修复了

**Comment by chuanhuayang** [comment]
3Q，问题已解决
