### ISSUE TITLE
sdp会自动删除一部分信息，和在线效果不符

### ISSUE THREAD

**Issue by appleyuchi** [HIT-SCIR/ltp#407]
代码如下:
https://paste.ubuntu.com/p/VTChmNMvPS/
数据集data.csv只有一个comment的column
这个column下面只有一个单元格
https://paste.ubuntu.com/p/W9W6ZSHgfD/

故障：
"那少女"在上述数据集中出现多次，但是sdp只会显示一次，把其他的都自动删除了，求问是怎么回事？
谢谢 ！
我的微信是appleyuchi
求技术支持下，谢谢！

**Comment by appleyuchi** [comment]
希望sdp不要去重要如何设置啊？

**Comment by appleyuchi** [comment]
希望sdp不要去重,
要如何设置啊？
谢谢

**Comment by AlongWY** [comment]
数据太长了？

**Comment by appleyuchi** [comment]
> 数据太长了？

求帮忙看下，拜托了。。。。。。
是免费版的有限制吗？
谢谢您

**Comment by AlongWY** [comment]
不是免费版的有限制，而是 bert 类的transformers都有512个最大字符长度的限制，然后我们的web demo运行的是base模型

**Comment by appleyuchi** [comment]
参考这里进行分句:
https://github.com/HIT-SCIR/ltp/blob/master/docs/quickstart.rst
