### ISSUE TITLE
在包含某些字符时，基于已分词抽取hidden会出错

### ISSUE THREAD

**Issue by wjmzjx** [HIT-SCIR/ltp#408]
**ltp.seg(lemmas, is_preseged=True)**
对已分词结果抽取hidden时，若包含字符（如半角空格'\u200c\u200c，还有\ue456\ue647等），获取的新hidden2是有bug的
我并未改动分词情况，只是将ltp.seg()的分词结果lemmas传回了ltp.seg(_, is_preseged=True)

而hidden2字典中word_input和word_length长度不匹配会导致后续的 ltp.dep(hidden2)报错

**代码：**
```
sentence = ['带有各种逻辑谬误的‌‌“五毛语录‌‌”：']

ltp = LTP(path="model/LTP4.0.0/base")
lemmas,hidden = ltp.seg(sentence)
print('lemmas1: ',lemmas)
lemmas2,hidden2 = ltp.seg(lemmas, is_preseged=True)
print('lemmas2: ',lemmas)

print('word_input\t','word_length\t''word_cls_input')
print(hidden['word_input'].size(),hidden['word_length'],hidden['word_cls_input'].size())
print(hidden2['word_input'].size(),hidden2['word_length'],hidden2['word_cls_input'].size())
```

**输出：**
lemmas1:  [['带有', '各种', '逻辑', '谬误', '的', '\u200c\u200c“', '五毛', '语录', '\u200c\u200c”', '：']]
lemmas2:  [['带有', '各种', '逻辑', '谬误', '的', '\u200c\u200c“', '五毛', '语录', '\u200c\u200c”', '：']]
word_input	 word_length	word_cls_input
torch.Size([1, 10, 768]) [10] torch.Size([1, 11, 768])
torch.Size([1, 8, 768]) [10] torch.Size([1, 9, 768])

**报错的代码如下：**
```
sentence = ['带有各种逻辑谬误的‌‌“五毛语录‌‌”：']

ltp = LTP(path="model/LTP4.0.0/base")
lemmas,hidden = ltp.seg(sentence)
print('lemmas1: ',lemmas)
lemmas2,hidden2 = ltp.seg(lemmas, is_preseged=True)
print('lemmas2: ',lemmas)

print('word_input\t','word_length\t''word_cls_input')
print(hidden['word_input'].size(),hidden['word_length'],hidden['word_cls_input'].size())
print(hidden2['word_input'].size(),hidden2['word_length'],hidden2['word_cls_input'].size())

# 此处报错 
ddd = ltp.dep(hidden2)
print('dep2: ',ddd)
```

**报错信息：**
lemmas1:  [['带有', '各种', '逻辑', '谬误', '的', '\u200c\u200c“', '五毛', '语录', '\u200c\u200c”', '：']]
lemmas2:  [['带有', '各种', '逻辑', '谬误', '的', '\u200c\u200c“', '五毛', '语录', '\u200c\u200c”', '：']]
word_input	 word_length	word_cls_input
torch.Size([1, 10, 768]) [10] torch.Size([1, 11, 768])
torch.Size([1, 8, 768]) [10] torch.Size([1, 9, 768])
Traceback (most recent call last):
  File "E:/Ss_working/Python_workSpace/entity_group/test.py", line 19, in <module>
    ddd = ltp.dep(hidden2)
  File "E:\gl\sf\envs\python36\lib\site-packages\ltp\ltp.py", line 40, in wrapper
    return func(*args, **kwargs)
  File "E:\gl\sf\envs\python36\lib\site-packages\ltp\ltp.py", line 364, in dep
    dep_arc_fix = eisner(dep_arc, hidden['word_cls_mask']).unsqueeze_(-1).expand_as(dep_arc)
  File "E:\gl\sf\envs\python36\lib\site-packages\ltp\utils\eisner.py", line 55, in eisner
    backtrack(p_i[i], p_c[i], heads, 0, length, True)
  File "E:\gl\sf\envs\python36\lib\site-packages\ltp\utils\eisner.py", line 65, in backtrack
    r = p_c[i, j]
IndexError: index 10 is out of bounds for dimension 1 with size 9

Process finished with exit code 1

**请问这种问题应该如何解决？只能依靠前期预处理时将可能会导致这一情况的字符去除吗？**

**Comment by AlongWY** [comment]
这些都是不可见字符，可以使用正则表达式等方式去除

```python
import re

from ltp import LTP

if __name__ == '__main__':
    sentence = ['带有各种逻辑谬误的‌‌“五毛语录‌‌”：']

    sentence = [re.sub(r'[\u200c]+', '', sent) for sent in sentence]

    ltp = LTP('base')
    lemmas, hidden = ltp.seg(sentence)
    print('lemmas1: ', lemmas)
    lemmas2, hidden2 = ltp.seg(lemmas, is_preseged=True)
    print('lemmas2: ', lemmas)

    print('word_input\t', 'word_length\t''word_cls_input')
    print(hidden['word_input'].size(), hidden['word_length'], hidden['word_cls_input'].size())
    print(hidden2['word_input'].size(), hidden2['word_length'], hidden2['word_cls_input'].size())

    # 此处报错
    ddd = ltp.dep(hidden2)
    print('dep2: ', ddd)
```

**Comment by wjmzjx** [comment]
感谢回复，

请问 模型支持哪些字符投喂？

以下正则的字符可以正确投喂，
	√ 中文 ：\u4e00-\u9fa5
	√ 全角符号：\u3000-\u303f\ufb00-\ufffd
	√ 半角符号： \u0020-\u00ff
	日文韩文不支持

**Comment by AlongWY** [comment]
在下载模型时候有个vocab.txt，这是模型支持的字符列表，我们使用的模型为中文electra https://github.com/ymcui/Chinese-ELECTRA，所以支持的字符以此为准

**Comment by wjmzjx** [comment]
另外我也很好奇，虽然是不可见字符，但是不进行ltp.seg(lemmas, is_preseged=True)的话，是不会出现错误的。

也就是说ltp.seg(lemmas, is_preseged=False)可以避免的问题，ltp.seg(lemmas, is_preseged=True)无法避免

所以，大佬，会不会是is_preseged=True的时候word_idx没给对
