### ISSUE TITLE
请问SRL的数据输入形式

### ISSUE THREAD

**Issue by BellaLiu112** [HIT-SCIR/ltp#410]
科学	_	O	B-ARG0	B-ARG0	O
发展观	_	O	I-ARG0	I-ARG0	O
绝对	_	O	B-ARGM-ADV	B-ARGM-ADV	O
不	_	O	B-ARGM-ADV	B-ARGM-ADV	O

请问有详细的说明吗？动词标志放在哪里？
找的Conll的工具生成的样本如下：
Some	-	B-ARG1	B-ARG1	B-ARG1	B-ARG0
``	-	I-ARG1	I-ARG1	I-ARG1	I-ARG0
circuit	-	I-ARG1	I-ARG1	I-ARG1	I-ARG0
breakers	-	I-ARG1	I-ARG1	I-ARG1	I-ARG0
''	-	I-ARG1	I-ARG1	I-ARG1	I-ARG0
installed	install	B-V	I-ARG1	I-ARG1	I-ARG0
after	-	B-ARGM-TMP	I-ARG1	I-ARG1	I-ARG0
the	-	I-ARGM-TMP	I-ARG1	I-ARG1	I-ARG0
October	-	I-ARGM-TMP	I-ARG1	I-ARG1	I-ARG0
1987	-	I-ARGM-TMP	I-ARG1	I-ARG1	I-ARG0
crash	-	I-ARGM-TMP	I-ARG1	I-ARG1	I-ARG0
failed	fail	O	B-V	I-ARG1	O
their	-	O	B-ARG2	I-ARG1	O
first	-	O	I-ARG2	I-ARG1	O
test	-	O	I-ARG2	I-ARG1	O
,	-	O	O	O	O
traders	-	O	O	B-ARG0	O
say	say	O	O	B-V	O
,	-	O	O	O	O
unable	-	O	B-ARGM-PRD	B-ARG1-CRD	O
to	-	O	I-ARGM-PRD	I-ARG1-CRD	O
cool	cool	O	I-ARGM-PRD	I-ARG1-CRD	B-V
the	-	O	I-ARGM-PRD	I-ARG1-CRD	B-ARG1
selling	-	O	I-ARGM-PRD	I-ARG1-CRD	I-ARG1
panic	-	O	I-ARGM-PRD	I-ARG1-CRD	I-ARG1
in	-	O	I-ARGM-PRD	I-ARG1-CRD	I-ARG1
both	-	O	I-ARGM-PRD	I-ARG1-CRD	I-ARG1
stocks	-	O	I-ARGM-PRD	I-ARG1-CRD	I-ARG1
and	-	O	I-ARGM-PRD	I-ARG1-CRD	I-ARG1
futures	-	O	I-ARGM-PRD	I-ARG1-CRD	I-ARG1
.	-	O	O	O	O

请问这样正确吗？我用这个格式跑train的srl失败了，错误是没有生成样本。找了很多资料，还是不太理解，希望能回复，谢谢！

**Comment by BellaLiu112** [comment]
ltp/data/fields/text.py 这里的 preprocess函数的47行，这个api的有个参数return_attention_masks 查了应该是 return_attention_mask，这里会报错

**Comment by BellaLiu112** [comment]
数据第二列动词用 Y标记就行了，后面的列 动词用tag O 补齐吗？

**Comment by AlongWY** [comment]
```
颁奖	_	B-ARG1	O	O	O
典礼	_	I-ARG1	O	O	O
在	_	B-ARGM-LOC	O	O	O
瑞典	_	I-ARGM-LOC	O	O	O
皇家	_	I-ARGM-LOC	O	O	O
学院	_	I-ARGM-LOC	O	O	O
举行	Y	O	O	O	O
，	_	O	O	O	O
高行健	_	O	B-ARG0	O	O
和	_	O	I-ARG0	O	O
```

第二列是动词，后面的列使用O标记即可

**Comment by BellaLiu112** [comment]
感谢！

**Comment by Floret1349** [comment]
> Conll

请问这个Conll工具在哪里可以找到呢？
