### ISSUE TITLE
关于分词、实体识别与依存句法分析联合的问题

### ISSUE THREAD

**Issue by Gavingx** [HIT-SCIR/ltp#412]
有这么个情况：假如我想对某个句子进行分词、实体识别、依存句法分析。
分词结果: ["我“，”很“，“崇拜”，”史蒂芬“，”乔布斯“]
实体识别：[("Nh", 3, 4)]
根据实体修正分词结果：["我", "很", "崇拜", "史蒂夫乔布斯"]
依存分析：ltp.dep(hidden)
但这里有个问题：这里的hidden是 ["我“，”很“，“崇拜”，”史蒂芬“，”乔布斯“]的分词结果的hidden， 但我实际需要的是
["我", "很", "崇拜", "史蒂夫乔布斯"]的hidden，两个hidden不一样，只能自己对hidden作处理吗(比如说在dim=1上求平均)？ 还是说有其他的方式？

**Comment by AlongWY** [comment]
事实上我们在训练的时候只采用了第一个字作为整个词语的表示，也就是说，你应该把最后一个词语剔除掉

**Comment by Gavingx** [comment]
> 事实上我们在训练的时候只采用了第一个字作为整个词语的表示，也就是说，你应该把最后一个词语剔除掉

可以剔除除第一个词的任何一个词吧，为什么是最后一个词？

**Comment by teddyliu01** [comment]
> 事实上我们在训练的时候只采用了第一个字作为整个词语的表示，也就是说，你应该把最后一个词语剔除掉

也就是说，"史蒂夫乔布斯" 和 "史蒂夫" 没有任何区别，后面 ”乔布斯“ 反而会引起一些偏差？

**Comment by AlongWY** [comment]
只是我们训练时仅仅采用了每个词的第一个字作为整个词语词义的表示，由于预训练模型本身会捕捉词语的上下文信息，所以 @Gavingx 的表述也没什么问题，只是预测时应该遵循训练时的策略。关于 @teddyliu01 所说的问题，说完全没有区别肯定是不可能的，毕竟句子不一样，后面的乔布斯可能会导致一些偏差，但是问题不大。
