### ISSUE TITLE
无法复现分词F1

### ISSUE THREAD

**Issue by botissue** [HIT-SCIR/ltp#415]
您好，感谢老师们的工作。我尝试按ltp官网上所述人民日报数据集的split训练hfl/chinese-electra-base-discriminator：

> 人民日报1998年2月-6月(后10%数据作为开发集)作为训练数据，1月作为测试数据。

得到的F1为98.2，与公布的98.7有较大出入，甚至不如贵校公布的论文中tiny的98.4。论文中说

> People’sDaily dataset2, which contains 305,041 sentences for training, 5,000 sentences for validation and 7,500 sentences for testing

```
wc -l *.txt                  
   22564 199801.txt
   21357 199802.txt
   24562 199803.txt
   24957 199804.txt
   24739 199805.txt
   24410 199806.txt
  142589 total
```

可人民日报1月份有大约2万个句子，怎么会恰好有7500这个整数呢？
请问这是为什么？

**Comment by botissue** [comment]
我还注意到ltp的分词结果中，姓和名是合并的，而人民日报是分开的。我尝试合并人民日报中的姓名重新训练，依然只有98.2。这些迹象好奇怪，恳请老师指教

**Comment by AlongWY** [comment]
已经收到你的反馈，我当时做实验使用的是LTP 3之前的训练数据和通报结果，之后将对数据集进行核验
