### ISSUE TITLE
词性标注所用语料真的是人民日报吗？

### ISSUE THREAD

**Issue by botissue** [HIT-SCIR/ltp#416]
老师您好，

我注意到ltp4的词性标注集打印出来有27个：

['n', 'v', 'wp', 'u', 'd', 'a', 'm', 'p', 'r', 'ns', 'c', 'q', 'nt', 'nh', 'nd', 'j', 'i', 'b', 'ni', 'nz', 'nl', 'z', 'k', 'ws', 'o', 'h', 'e']

这应该是863标注集吧，不是人民日报。人民日报的词性（[参考这个表格](https://github.com/hankcs/HanLP/blob/1.x/data/dictionary/other/TagPKU98.csv)）有42个：

['v', 'n', 'c', 'ns', 'nr', 'j', 'nt', 'w', 't', 'u', 'vn', 'b', 'f', 'm', 'vd', 'r', 'p', 'd', 'q', 'a', 'Ng', 'l', 'ad', 'i', 'z', 's', 'nz', 'an', 'Ag', 'k', 'Vg', 'y', 'nx', 'o', 'Tg', 'e', 'Dg', 'h', 'Rg', 'Mg', 'Bg', 'Yg']

我自己统计了98年6个月的人民日报，的确是42个。标注集对不上，请问这是为什么呢？

PS 我同样未能用ltp4复现文档所说98.5%的准确率

**Comment by carfly** [comment]
没错，我们将人民日报的标注集映射到了863的

-Wanxiang (http://ir.hit.edu.cn/~car/)

**Comment by botissue** [comment]
谢谢车老师，我再去做实验
