### ISSUE TITLE
安装失败了这啥意思啊

### ISSUE THREAD

**Issue by laplace11** [HIT-SCIR/ltp#419]
![image](https://user-images.githubusercontent.com/26244761/96103987-e1f5bd00-0f0a-11eb-9c90-6e66b5ffb307.png)

**Comment by bluebottle-jp** [comment]
我也遇到了这个问题，请问你的问题解决了吗

**Comment by AlongWY** [comment]
这是pytorch安装失败了，可以先用conda安装下pytorch
