### ISSUE TITLE
关于中英混的实现

### ISSUE THREAD

**Issue by zshy1205** [HIT-SCIR/ltp#424]
LTP开发者你们好。
  实际测试发现LTP关于中英混的效果很好，包括词性标注。请问这块是怎么样的实现思路呢？有没有参考资料给一下~

**Comment by AlongWY** [comment]
这部分可以参考我们公布的论文哈

**Comment by zshy1205** [comment]
论文出了吗？没看到呀

**Comment by AlongWY** [comment]
@article{che2020n,
  title={N-LTP: A Open-source Neural Chinese Language Technology Platform with Pretrained Models},
  author={Che, Wanxiang and Feng, Yunlong and Qin, Libo and Liu, Ting},
  journal={arXiv preprint arXiv:2009.11616},
  year={2020}
}

**Comment by zshy1205** [comment]
十分感谢。
