### ISSUE TITLE
依存句法分析出现如下错误，如何解决？

### ISSUE THREAD

**Issue by bluebottle-jp** [HIT-SCIR/ltp#427]
![L`~ Q3EJ~TRR__3UXIWT_(3](https://user-images.githubusercontent.com/70835264/97101186-2be25e00-16d6-11eb-96d1-21e071cc59ff.png)
![DT5VA`~8P_ {PZU(VS%NVTD](https://user-images.githubusercontent.com/70835264/97101189-3270d580-16d6-11eb-903e-a4a08bc0ad64.png)

**Comment by bluebottle-jp** [comment]
![Uploading L`~]Q3EJ~TRR__3UXIWT_(3 (1).png…]()

**Comment by bluebottle-jp** [comment]
![L`~ Q3EJ~TRR__3UXIWT_(3](https://user-images.githubusercontent.com/70835264/97101204-651ace00-16d6-11eb-9267-e12b0335cbc0.png)

**Comment by AlongWY** [comment]
可否说明一下使用的pytorch版本

**Comment by bluebottle-jp** [comment]
你好，我的版本是cpu版本 1.1.0




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Along"<notifications@github.com&gt;; 
发送时间: 2020年10月25日(星期天) 晚上8:16
收件人: "HIT-SCIR/ltp"<ltp@noreply.github.com&gt;; 
抄送: "1215524871"<1215524871@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [HIT-SCIR/ltp] 依存句法分析出现如下错误，如何解决？ (#427)





 
可否说明一下使用的pytorch版本

**Comment by AlongWY** [comment]
应该是 pytorch 版本太低了不支持，1.1.0版本没有进行过测试，你可以升级到1.3.0或者1.4.0以上
