### ISSUE TITLE
requirement.txt 下面 transformers 的版本必须是是3.2 有什么特殊原因么？

### ISSUE THREAD

**Issue by johnsonice** [HIT-SCIR/ltp#428]
transformers==3.2.0 跟transformers 最新版有冲突。 安装是会自动降级transformers。 有什么特殊原因必须固定在3.2 版本么？由于版本原因会导致transformers 里面一些example 无法运行

**Comment by AlongWY** [comment]
没有特殊原因，当时开发的时候最新版本是3.2.0，为了维护环境的一致性，所以是3.2.0，测试了3.4之后会升级的
