### ISSUE TITLE
error: segmentation fault( core dumped)

### ISSUE THREAD

**Issue by gabornj** [HIT-SCIR/ltp#432]
I install ltp4 as stated https://blog.csdn.net/baoyan2015/article/details/107489390
the error occured as :
>>> from ltp import LTP
>>> ltp = LTP(path="tiny")
Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 36.2M/36.2M [00:26<00:00, 1.38MB/s]
Segmentation fault (core dumped)

what should i do?

**Comment by hy295322781** [comment]
I have the same problem.

**Comment by renqingcolin** [comment]
I have the same problem.

**Comment by AlongWY** [comment]
maybe the cuda version is not be supported by your card or nvidia driver?
