### ISSUE TITLE
性能问题

### ISSUE THREAD

**Issue by xumeng123** [HIT-SCIR/ltp#436]
首先，非常感谢作者的辛苦付出和开源。然而我们在使用4.0版本的过程中发现实体识别的结果不是很好，从数据统计上来看，不如3.4版本。尤其是将很多的地名地址以及其他词识别成了组织机构，真诚希望能在其他领域多测试测试，一起让这个工具变得更好。

**Comment by AlongWY** [comment]
我们增加了在UD和Ontonotes上训练的模型，可以测试一下
