### ISSUE TITLE
metaclass conflict

### ISSUE THREAD

**Issue by JiaCheng-Huang** [HIT-SCIR/ltp#437]
简单的示例
```
from ltp import LTP
ltp = LTP()
sents = ltp.sent_split(["他叫汤姆去拿外衣。", "汤姆生病了。他去了医院。"])
```
运行报错：
> Traceback (most recent call last):
>   File "/Users/dylan/PycharmProjects/Demo/Test.py", line 1, in <module>
>     from ltp import LTP
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ltp/__init__.py", line 7, in <module>
>     from .data import Dataset
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ltp/data/__init__.py", line 7, in <module>
>     from .fields import Field
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ltp/data/fields/__init__.py", line 83, in <module>
>     from .label import LabelField
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ltp/data/fields/label.py", line 12, in <module>
>     from ltp.data.dataset import Dataset
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ltp/data/dataset/__init__.py", line 5, in <module>
>     from .dataset import rationed_split, RandomShuffler, Dataset
>   File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ltp/data/dataset/dataset.py", line 14, in <module>
>     class Dataset(torch.utils.data.dataset.Dataset, metaclass=Registrable):
> TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

环境：
Python3.6.3，LTP4.0.9，MacOS Catalina 11.15.7

**Comment by AlongWY** [comment]
应该是 pytorch 版本太新了，降级到 1.6 即可
