### ISSUE TITLE
依存句法分析结果不完整

### ISSUE THREAD

**Issue by MachineWei** [HIT-SCIR/ltp#442]
- ltp 4.0.10版本
- LTP 4.0 base 和 small模型均有该问题
text = '今天天气不错'
seg, hidden = ltp.seg([text])
*[['今天', '天气', '不错']]*
dep = ltp.dep(hidden)
*[[(1, 3, 'ADV'), (2, 3, 'SBV')]]*
dep结果缺了一个

**Comment by AlongWY** [comment]
4.0.10 版本的依存句法有点问题，但是新的 4.1 是没问题的
