### ISSUE TITLE
AttributeError: 'Version' object has no attribute 'major'

### ISSUE THREAD

**Issue by ZXJ-DSA** [HIT-SCIR/ltp#445]
环境：
python 3.7.0  
torch 1.7.0+cu101  
transformers 3.2.0

源代码：
from ltp import LTP
ltp = LTP()
seg, hidden = ltp.seg(["他叫汤姆去拿外衣。"])
pos = ltp.pos(hidden)
ner = ltp.ner(hidden)
srl = ltp.srl(hidden)
dep = ltp.dep(hidden)
sdp = ltp.sdp(hidden)

报错如下：
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-17b174c1e5da> in <module>()
      1 from ltp import LTP
      2 ltp = LTP()
----> 3 seg, hidden = ltp.seg(["他叫汤姆去拿外衣。"])
      4 pos = ltp.pos(hidden)
      5 ner = ltp.ner(hidden)

~\Anaconda3\lib\site-packages\ltp\frontend.py in wrapper(*args, **kwargs)
     42     def wrapper(*args, **kwargs):
     43         with torch.no_grad():
---> 44             return func(*args, **kwargs)
     45 
     46     return wrapper

~\Anaconda3\lib\site-packages\ltp\frontend.py in seg(self, inputs, truncation, is_preseged)
    211         """
    212 
--> 213         if transformers_version.major >= 3 and transformers_version.major > 1:
    214             kwargs = {'is_split_into_words': is_preseged}
    215         else:

AttributeError: 'Version' object has no attribute 'major'

**Comment by AlongWY** [comment]
应该是 python 的 packaging 包版本太低了，试试执行下列命令 `pip install pip -U`

**Comment by ZXJ-DSA** [comment]
感谢！确实是这个原因，用命令`pip install --upgrade packaging`成功解决问题。
