### ISSUE TITLE
句法依存存在游离成分的问题

### ISSUE THREAD

**Issue by glacierck** [HIT-SCIR/ltp#447]
ltp：4.1.0
mod：small （base没这问题）
解析内容：维持腾讯买入评级
问题：“腾讯买入评级”中的任意成员没有与核心成分“维持”链接，游离在外。
有图有真相:
![image](https://user-images.githubusercontent.com/21599896/100962770-f431c600-355f-11eb-93ef-ec1b21f24938.png)
![image](https://user-images.githubusercontent.com/21599896/100962806-06abff80-3560-11eb-8f9e-87aaae3e7159.png)

**Comment by AlongWY** [comment]
可以把 fast 解码关闭试一下

**Comment by glacierck** [comment]
> 可以把 fast 解码关闭试一下，fast 解码不保证一定输出一棵树

fast=false后确实解决了问题。但这是精度问题吗？难道不是程序逻辑问题？不应该保证任意成分反向总能回到root吗？即使路径标签不正确。
![image](https://user-images.githubusercontent.com/21599896/100971980-eafe2480-3572-11eb-82a5-74569d67e73a.png)

**Comment by AlongWY** [comment]
小模型性能不够，直接使用 argmax 解码没有约束必然会有很大的误差，大模型学习的足够好，可以不使用规则约束
