### ISSUE TITLE
安装过程中没有报错，但是导入包时提示 module 'tensorflow_core.keras.activations' has no attribute 'swish'

### ISSUE THREAD

**Issue by lixuanhng** [HIT-SCIR/ltp#450]
使用 pip install ltp 的命令进行安装，安装过程没有报错；

安装完毕后使用 from ltp import LTP 时发生报错，报错信息如下：

AttributeError: module 'tensorflow_core.keras.activations' has no attribute 'swish'

报错位置为python3.7/site-packages/transformers/activations_tf.py in <module>，不知道是什么原因造成的，看了一下tensorflow.keras.activations.swish是存在的

环境配置如下：

python=3.7
transformers=3.5.1
tensorflow=2.1

还请多多指教，谢谢！

**Comment by AlongWY** [comment]
这应该是pytorch没有安装？另外LTP并不依赖tensorflow

**Comment by DinghaoXi** [comment]
我也是这样的问题，是pytorch环境

**Comment by AlongWY** [comment]
尝试把tensorflow卸载掉吧
