### ISSUE TITLE
使用最新源码跑最新Base-v3模型，得到的SDP效果与在线DEMO的SDP不一致

### ISSUE THREAD

**Issue by orientedlin** [HIT-SCIR/ltp#451]
## 问题描述
最新base-v3模型在SDP上表现效果，与在线demo展示不一致。句子长度正常。请问是什么原因？
另外请问CCL2020语义分析的数据集在何处可以获得？
十分感谢！

## 样例
1. text = 小明和小胖走路进场，坐到厨师对面的桌子处
    - 在线demo：
        ![image](https://user-images.githubusercontent.com/23066480/102005972-04178a00-3d58-11eb-8756-268f74179045.png)
    - 源码base-v3效果(graph = True)：
        （AGT关系丢失）
        sdp = [[(2, 3, 'mRELA'), (4, 0, 'Root'), (5, 4, 'eSUCC'), (6, 5, 'mPUNC'), (7, 5, 'eSUCC'), (8, 7, 'mDEPD'), (9, 10, 'FEAT'), (10, 9, 'SCO'), (10, 12, 'LOC'), (11, 9, 'mDEPD'), (11, 10, 'mDEPD'), (12, 7, 'LOC'), (12, 13, 'FEAT'), (13, 7, 'LOC')]]
        - SDP分析结果 : 
            SRL EDGE 小胖 -> mRELA : 和
            SRL EDGE ROOT -> Root : 走路
            SRL EDGE 走路 -> eSUCC : 进场
            SRL EDGE 进场 -> mPUNC : ， ; eSUCC : 坐
            SRL EDGE 坐 -> mDEPD : 到 ; LOC : 桌子 ; LOC : 处
            SRL EDGE 对面 -> FEAT : 厨师 ; mDEPD : 的
            SRL EDGE 厨师 -> SCO : 对面 ; mDEPD : 的
            SRL EDGE 桌子 -> LOC : 对面
            SRL EDGE 处 -> FEAT : 桌子
    - 源码base-v3效果（graph=False）
        （AGT位置不同）
        - SDP分析结果
            SRL EDGE 走路 -> AGT : 小明 ; AGT : 小胖 ; eSUCC : 进场
            SRL EDGE 小胖 -> mRELA : 和
            SRL EDGE ROOT -> Root : 走路
            SRL EDGE 进场 -> mPUNC : ， ; eSUCC : 坐
            SRL EDGE 坐 -> mDEPD : 到 ; LOC : 处
            SRL EDGE 对面 -> FEAT : 厨师 ; mDEPD : 的
            SRL EDGE 桌子 -> LOC : 对面
            SRL EDGE 处 -> FEAT : 桌子
2. text = 楚蝉担心的皱眉
    - 在线demo：
        ![image](https://user-images.githubusercontent.com/23066480/102006718-3a580800-3d5e-11eb-80ed-62f73c428f3c.png)
    - 源码base-v3效果 （graph=True）
        （两个ROOT）
        - SDP分析结果 : 
            SRL EDGE 担心 -> AGT : 楚蝉 ; mDEPD : 的 ; CONT : 眉
            SRL EDGE ROOT -> Root : 担心 ; Root : 皱
            SRL EDGE 皱 -> EXP : 眉
    - 源码base-v3效果（graph=False）
        （和图中不一致）
        - SDP分析结果
            SRL EDGE 担心 -> AGT : 楚蝉 ; mDEPD : 的
            SRL EDGE 皱 -> rCONT : 担心 ; EXP : 眉
            SRL EDGE ROOT -> Root : 皱

## 代码
```python
from ltp import LTP
ltp = LTP("./base.tgz")  # 为2020.12.13从网站上下载的最新模型，下载地址：http://39.96.43.154/ltp/v3/base.tgz
seg, hidden = ltp.seg([text])
graph_sdp = ltp.sdp(hidden, graph=True)
tree_sdp = ltp.sdp(hidden,graph=False)
```

**Comment by AlongWY** [comment]
在线的SDP解码是Graph和Tree混合解码，具体可以看一下4.0.X的源码
