### ISSUE TITLE
分完词的结果丢失了空格

### ISSUE THREAD

**Issue by dancinghui** [HIT-SCIR/ltp#454]
seg,hidden = ltp.seg(["作者：刘俊\u3000（来源：广州日报）"])
分完词的结果为：
[['作者', '：', '刘俊', '（', '来源', '：', '广州', '日报', '）']]
\u3000这个字符不见了，会给与原文对齐造成困难

**Comment by AlongWY** [comment]
目前的行为是分词之后对每个词语进行 strip()，你可以自行修改代码来改变此行为
