### ISSUE TITLE
SRL指标计算问题

### ISSUE THREAD

**Issue by ZiJianZhao** [HIT-SCIR/ltp#455]
你好，我在CPB2.0数据集合上随机采样了两千条数据，计算了一下SRL的Fscore，结果显示比报告的结果要低10点左右，我估计应该是我的计算方式有问题，所以想请教一下，我的计算如下：

对于给定的句子，我把gold label和pred label都表示了一个tuple的集合，这个tuple的形式如下（谓词-论元组作为一个元素）：
`(predicate_id, (role, role_begin_id, role_end_id))`
之后把每个tuple当做一个独立的元素，然后对整个测试集合计算Fscore。
```
class Fscore(object):

    def __init__(self, tag='Fscore'):
        self.tag = tag
        self.TP = 0.
        self.FP = 0.
        self.FN = 0.

    def update_tp_fp_fn(self, pred_classes, gold_classes):
        for p in pred_classes:
            if p in gold_classes:
                self.TP += 1
            else:
                self.FP += 1
        for g in gold_classes:
            if g not in pred_classes:
                self.FN += 1

    def output_fscore(self):
        if self.TP == 0:
            precision, recall, fscore = 0., 0., 0.
        else:
            precision = 100 * self.TP / (self.TP + self.FP)
            recall = 100 * self.TP / (self.TP + self.FN)
            fscore = 100 * 2 * self.TP / (2 * self.TP + self.FN + self.FP)

        print("Precision: {:.2f}; Recall: {:.2f}; Fscore: {:.2f}".format(
            precision, recall, fscore
        ))
        return fscore
```
请问这种方式有问题吗？您的计算方式是什么？谢谢。

**Comment by AlongWY** [comment]
我们用的是seqeval这个包对f1值进行的计算，具体您可以看一下源码的实现

**Comment by ZiJianZhao** [comment]
嗯，我主要想知道我这种组织元素的方式对不对？`(predicate_id, (role, role_begin_id, role_end_id))`
因为seqeval算f1应该是要求gold和pred是对齐的列表，那么对于整个SRL任务，同时预测predicate和argument而言，对于一个输入的句子，分词之后长度为N，那么对应的predicate-argument矩阵为N*N，其中很多行由于该词不是predicate，对应的都是O；那些对应是谓词的行则有O也有Arg0之类的标签，那么您在用seqeval计算的时候，是所有这些行都用了吗？

**Comment by AlongWY** [comment]
所有行都使用了，但gold这部分必然是没有值存在的

**Comment by ZiJianZhao** [comment]
好的，谢谢。对于不是predicate的行，gold这部分没有值存在具体是什么意思啊？是指这一行gold是一个长度为N的值全部为O的列表吗？然后这个列表和pred的结果列表也都会作为一个pair加入到seqeval的fscore计算中？
