### ISSUE TITLE
seg分词时 tokenized.encodings为none

### ISSUE THREAD

**Issue by glacierck** [HIT-SCIR/ltp#456]
ltp 4.1.1
transformers 3.5.1
torch  1.4.0
torchvision   0.5.0

tokenized对象均存在，encodings属性在win个人版没问题。
部署到win2012就为None。

![image](https://user-images.githubusercontent.com/21599896/102451326-33d5d300-4073-11eb-88e5-1d46a259b5fa.png)

**Comment by glacierck** [comment]
一路降级ltp到4.0.9之后可以正常分词了。。。

**Comment by glacierck** [comment]
再次夹B，结论
ltp==4.1.1
transformers >=3.2.0，<=3.3.0

**Comment by AlongWY** [comment]
我在macos下进行开发，没有成功复现你这个问题

**Comment by weiziyao1130** [comment]
> 一路降级ltp到4.0.9之后可以正常分词了。。。

遇到了同样的问题，降版本后解决了，非常感谢！

**Comment by freshbirdDD** [comment]
> 再次夹B，结论
> ltp==4.1.1
> transformers >=3.2.0，<=3.3.0

结论可靠, 谢谢
