### ISSUE TITLE
单独下载的模型文件怎么加载？加载错误

### ISSUE THREAD

**Issue by LYU2026** [HIT-SCIR/ltp#458]
```py 文件
from ltp import LTP
ltp = LTP()
# ltp = LTP(path = "small.tgz|small") #small.tgz是单独下载的模型文件，small是解压的路径
sents = ltp.sent_split(["他叫汤姆去拿外衣。", "汤姆生病了。他去了医院。"])
```
我把small.tgz文件放在这个py文件同路径下，也解压缩到这个路径
文件路径：
|--test.py
|--small.tgz
|--small/

但是源文件的ltp/frontend.py line 117报错。我放在一个虚拟机上的，没有网

**Comment by zhaokanghuiasd** [comment]
@LYU2026 我是self.ltp = LTP(path="base.tgz")这么写的，可以直接用

**Comment by LYU2026** [comment]
> @LYU2026 我是self.ltp = LTP(path="base.tgz")这么写的，可以直接用

你的模型文件是和py文件是放在同一个路径下的吗？我的small就是放一起的。我把|small删除后就报ltp/frontend.py ,line128, config=AutoConfig.for_model(**ckpt['transformer_config']) ,keyerror :'transformer_config'了

**Comment by AlongWY** [comment]
> > @LYU2026 我是self.ltp = LTP(path="base.tgz")这么写的，可以直接用
> 
> 你的模型文件是和py文件是放在同一个路径下的吗？我的small就是放一起的。我把|small删除后就报ltp/frontend.py ,line128, config=AutoConfig.for_model(**ckpt['transformer_config']) ,keyerror :'transformer_config'了

是不是先对照一下版本是否匹配，不同版本的代码支持的模型版本是不同的

**Comment by LYU2026** [comment]
换了base.tagz, ok了，果然small模型不管用呀，谢谢。
