### ISSUE TITLE
用户自定义词典添加词性

### ISSUE THREAD

**Issue by zhaokanghuiasd** [HIT-SCIR/ltp#459]
是否可以在用户自定义词典中给添加的词加入词性？

**Comment by zhaokanghuiasd** [comment]
还有一个问题，如果我想把 “跳转到”、“跳转”和“转到”三个词同时加入用户自定义词典，那么“跳转到”这个词是无法生效的。这个问题如何解决呢？

**Comment by AlongWY** [comment]
这个最新的代码已经更新了，之后发布的新版本会解决该问题

**Comment by AlongWY** [comment]
自定义词典暂时还不支持词性，之后可能考虑加上

**Comment by zhaokanghuiasd** [comment]
好的，感谢~
