### ISSUE TITLE
LTP支持英文分析吗

### ISSUE THREAD

**Issue by unikcc** [HIT-SCIR/ltp#460]
好像没看到英文的选项，能否推荐一下英文的支持SRL和SDP的工具

**Comment by AlongWY** [comment]
中英文混在一起，LTP的效果也还可以

**Comment by unikcc** [comment]
> 中英文混在一起，LTP的效果也还可以

才发现原来英文也可以，厉害了

**Comment by unikcc** [comment]
> 中英文混在一起，LTP的效果也还可以
同一句话，[LTP](http://ltp.ai/demo.html)和[云孚的](https://www.yunfutech.com/demo?tab=1)不太一致，是算法版本不同吗，哪个比较新以点
![LTP的依存和SDP](https://user-images.githubusercontent.com/19505579/102991963-465d7a00-4555-11eb-9af9-fed0d21c7496.png)

![云孚的依存](https://user-images.githubusercontent.com/19505579/102991990-5aa17700-4555-11eb-84f4-4e5687dc782c.png)

![云孚的SDP](https://user-images.githubusercontent.com/19505579/102992041-71e06480-4555-11eb-9e9c-af34fa3eb958.png)

**Comment by AlongWY** [comment]
ltp.ai 的demo稍微新一点
