### ISSUE TITLE
SRL的测试集合是什么？是从cpb3.0随机划分的吗？

### ISSUE THREAD

**Issue by ZiJianZhao** [HIT-SCIR/ltp#461]
你好，请问，SRL的测试集合是什么？是从cpb3.0随机划分的吗？我从cpb 3.0随机划分了2000条样例，利用LTP-SRL预测的Fscore结果为87左右，比报告的高很多。我推测可能是因为我随机划分的样例有一些出现在了训练集合中？测试集合是否方便公开，或者说明划分方法？谢谢！

**Comment by AlongWY** [comment]
对，当时是按照8:1:1随机划分的

**Comment by ZiJianZhao** [comment]
嗯嗯，好的，谢谢。所以测试集合不方便公开是吗？

**Comment by AlongWY** [comment]
这个语料应该是收费的，不便公开

**Comment by ZiJianZhao** [comment]
嗯嗯，好的，谢谢。
