### ISSUE TITLE
请问ltp有停用词处理吗？

### ISSUE THREAD

**Issue by weiziyao1130** [HIT-SCIR/ltp#463]
您好，看到ltp支持向词典中添加词，那ltp有停用词处理步骤吗，能否自己向词典中添加呢，十分感谢！！！

**Comment by AlongWY** [comment]
暂时没有停用词的处理

**Comment by weiziyao1130** [comment]
> 暂时没有停用词的处理

好的  非常感谢作者！您辛苦啦！
