### ISSUE TITLE
请问可以报告单任务的模型性能吗？

### ISSUE THREAD

**Issue by ZiJianZhao** [HIT-SCIR/ltp#464]
你好，现在展示的模型性能应该都是multi-task联合训练的吧？请问可以报告单任务的模型性能吗？大概会比multi-task差多少啊？谢谢。

**Comment by AlongWY** [comment]
|      模型       | 分词  | 词性  | 命名实体 | 语义角色 | 依存句法 | 语义依存 | 
| :-------------: | :---: | :---: | :------: | :------: | :------: | :------: | 
| ELECTRA BASE  | 98.5  | 98.2  |   93.8   |  80.7   |   89.4   |   76.2   | 
| LTP 4.0 (Base)  | 98.7  | 98.5  |   95.4   |   80.6   |   89.5   |   75.2   |

**Comment by ZiJianZhao** [comment]
好的，谢谢。
