### ISSUE TITLE
srl_labels

### ISSUE THREAD

**Issue by Devictor0815** [HIT-SCIR/ltp#467]
训练文件里面的srl_labels.txt的格式是如何的？

**Comment by AlongWY** [comment]
就是一行一个label

**Comment by Devictor0815** [comment]
跑训练的时候发现label_feature的index对不上，请问下，这个文件是固定的在训练数据集里面的，还是可以自己生成的。我没找到cpb的数据集。

**Comment by AlongWY** [comment]
可以自己从语料里面生成，num_labels要对上

**Comment by Devictor0815** [comment]
非常感谢!
