### ISSUE TITLE
LTP没有Constituency Parsing吗

### ISSUE THREAD

**Issue by unikcc** [HIT-SCIR/ltp#469]
您好！感谢维护LTP
我看了一下论文和Demo界面，LTP好像没有Constituency Parsing模块，是吗
![image](https://user-images.githubusercontent.com/19505579/103540179-4d30a900-4ed4-11eb-9cc7-ac2807ceaaff.png)
![image](https://user-images.githubusercontent.com/19505579/103540224-60dc0f80-4ed4-11eb-867e-4a53154f2838.png)
可以说下原因吗，Constituency Parsing也是非常基础的解析吧，现成的中文Constituency Parser好像不多，很需要LTP来解析一下。

**Comment by AlongWY** [comment]
暂时没有涉及这方面的工作
