### ISSUE TITLE
在做语义依存分析时, 使用 baseV3 模型, LTP4.1.1, 跑出来的结果与官网在线演示结果不同

### ISSUE THREAD

**Issue by qiangangZ** [HIT-SCIR/ltp#470]
样例: '绝对值不等式A的解集'

**Comment by white55** [comment]
我也发现同样的问题，您解决了嘛？

**Comment by white55** [comment]
样例： ["姚先生当时正在成都市武侯区的办公室打电话，突然感觉电脑显示器晃得很厉害，便丢下电话、抓起手机和钱包往外跑，手里还拿着无绳电话子机，准备给远在江苏的家人打电话。"]

**Comment by ybch14** [comment]
样例: "他是国内充气电离室领域主要开创者"
模型: Base V3
版本: 4.1.1
本地运行结果: 充气 <--ATT--- 电离室, 电离室 <--VOB--- 充气 (**环形依存**)
在线演示结果: 充气 <--ATT--- 领域, 电离室 <--COO--- 充气

**Comment by ybch14** [comment]
我参照 #447 把`ltp.dep(hidden)`改成`ltp.dep(hidden, fast=False)`之后问题解决了

**Comment by white55** [comment]
> 我参照[＃447](https://github.com/HIT-SCIR/ltp/issues/447)把`ltp.dep(hidden)`改成`ltp.dep(hidden, fast=False)`之后问题解决了

可是sdp中没有fast参数，不能设置的说。。

**Comment by ybch14** [comment]
唔是SDP吗...不好意思看成了DEP... #451好像说的是SDP的问题 @white55

**Comment by white55** [comment]
> 唔是SDP吗...不好意思看成了DEP... #451好像说的是SDP的问题 @white55

谢谢兄弟拉，从#451 解决掉了~~~
