### ISSUE TITLE
SRL所使用的CPB3.0语料只用了verbs吗？

### ISSUE THREAD

**Issue by ZiJianZhao** [HIT-SCIR/ltp#472]
你好，CPB 3.0数据包括了两个文件，一个是verbs.txt（动词性谓词），一个是nouns.txt（名词性谓词），请问LTP的SRL训练的时候是两个都用了？还是只用了verbs.txt啊？谢谢！

**Comment by AlongWY** [comment]
这里用了所有带有语义角色的谓词
