### ISSUE TITLE
AttributeError: 'Version' object has no attribute 'major'

### ISSUE THREAD

**Issue by freshbirdDD** [HIT-SCIR/ltp#473]
transformer 4.1.1 ltp 4.1.3.post1
运行ltp = LTP()时就会报题目中的错误

**Comment by Chen8566** [comment]
您好，请问这个问题您是怎么解决的？

**Comment by freshbirdDD** [comment]
﻿
注意ltp的版本和对应依赖包的版本，你可以在项目issue里找到别人实测有效的版本
