### ISSUE TITLE
ltp4.x server 如何使用

### ISSUE THREAD

**Issue by weidongkl** [HIT-SCIR/ltp#474]
文档只写了如何启动server，启动之后 url是啥，data格式未描述清楚，不知道如何测试
![image](https://user-images.githubusercontent.com/7512609/104165178-fb3bd600-5433-11eb-9056-a496c120c3ce.png)

**Comment by weidongkl** [comment]
石沉大海？

**Comment by ixsword** [comment]
> 石沉大海？

python tools/server.py serve
端口默认好像是5000
请求地址 http://127.0.0.1:5000
请求类型是post，body传json  {"text":文本}

**Comment by ixsword** [comment]
> 石沉大海？

大哥是对python都不懂哈

**Comment by weidongkl** [comment]
> > 石沉大海？
> 
> python tools/server.py serve
> 端口默认好像是5000
> 请求地址 http://127.0.0.1:5000
> 请求类型是post，body传json {"text":文本}

我试了好像不行呀

**Comment by AlongWY** [comment]
事实上这个 server 是针对官网的demo来做的，社区里有人写了一个 [ltp_server](https://github.com/smilelight/ltp_server)，也许你可以看看？

**Comment by weidongkl** [comment]
> 事实上这个 server 是针对官网的demo来做的，社区里有人写了一个 [ltp_server](https://github.com/smilelight/ltp_server)，也许你可以看看？

这个不错,文档齐全
