### ISSUE TITLE
無法正確解析特殊字元 例如韓語

### ISSUE THREAD

**Issue by kanasimi** [HIT-SCIR/ltp#478]
當我們將 LTP 使用於泛用環境時，輸入可能包含特殊字元，例如韓語。但 LTP 似乎不能正確解析，例如一段文章中包含 `韓語：한국의 단오` 可能會產出 `韓語：한한한국국국의의단단단오오`。不知可否改正。

**Comment by AlongWY** [comment]
我们会尽快处理该问题
