### ISSUE TITLE
pip install ltp库失败 报错 怎么解决

### ISSUE THREAD

**Issue by dy0021** [HIT-SCIR/ltp#487]
Collecting ltp
  Using cached https://files.pythonhosted.org/packages/04/93/52c9f29a4c2e26b606b908c521cbea43cf718d58e1a045d08e7ee98dce1d/ltp-4.1.3.post1-py3-none-any.whl
Collecting torch>=1.2.0 (from ltp)
  Using cached https://files.pythonhosted.org/packages/77/0c/c70f85961ad643801e82276087c8d816ae9b3d9119645313232b73840579/torch-1.5.1-cp35-cp35m-manylinux1_x86_64.whl
Collecting pygtrie<2.5,>=2.3.0 (from ltp)
  Using cached https://files.pythonhosted.org/packages/a5/8b/90d0f21a27a354e808a73eb0ffb94db990ab11ad1d8b3db3e5196c882cad/pygtrie-2.4.2.tar.gz
Collecting transformers<5.0,>=4.0.0 (from ltp)
  Using cached https://files.pythonhosted.org/packages/88/b1/41130a228dd656a1a31ba281598a968320283f48d42782845f6ba567f00b/transformers-4.2.2-py3-none-any.whl
Collecting future (from torch>=1.2.0->ltp)
  Using cached https://files.pythonhosted.org/packages/45/0b/38b06fd9b92dc2b68d58b75f900e97884c45bedd2ff83203d933cf5851c9/future-0.18.2.tar.gz
Collecting numpy (from torch>=1.2.0->ltp)
  Using cached https://files.pythonhosted.org/packages/51/60/3f0fe5b7675a461d96b9d6729beecd3532565743278a9c3fe6dd09697fa7/numpy-1.19.5.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-4mh_t0e7/numpy/setup.py", line 68
        f"NumPy {VERSION} may not yet support Python "
                                                     ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-4mh_t0e7/numpy/

**Comment by dy0021** [comment]
python版本 3.5.2     ubuntu 16.04

**Comment by shamy1997** [comment]
报错是因为python3.6 以后才支持f-string特性，我想应该是你的Python 版本过低了@dy0021

**Comment by dy0021** [comment]
好的谢谢你，已经解决，是python版本太低了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HIT-SCIR/ltp"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月30日(星期六) 晚上10:02
收件人:&nbsp;"HIT-SCIR/ltp"<ltp@noreply.github.com&gt;;
抄送:&nbsp;"段赟"<1601826830@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [HIT-SCIR/ltp] pip install ltp库失败 报错 怎么解决 (#487)





 
报错是因为python3.6 以后才支持f-string特性，我想应该是你的Python 版本过低了@dy0021
