### ISSUE TITLE
哪里可以指定只使用cpu

### ISSUE THREAD

**Issue by gbolin** [HIT-SCIR/ltp#492]
调api的时候，可以指定仅仅使用cpu吗

**Comment by AlongWY** [comment]
初始化的时候 device 参数指定称为 cpu 即可

**Comment by gbolin** [comment]
> 初始化的时候 device 参数指定称为 cpu 即可

`ltp = LTP(device='cpu')`

**Comment by gbolin** [comment]
已经解决
