### ISSUE TITLE
为什么自己跑的同样的文本，在本地和网页演示结果是不一样的？

### ISSUE THREAD

**Issue by yindisun** [HIT-SCIR/ltp#497]
如题，希望可以解答

**Comment by yindisun** [comment]
![image](https://user-images.githubusercontent.com/78191712/112834280-6196d300-90ca-11eb-8982-b3cdc0174171.png)
![image](https://user-images.githubusercontent.com/78191712/112834321-6eb3c200-90ca-11eb-85f2-b2c733641863.png)

**Comment by yindisun** [comment]
用了 small 和 base 两个模型尝试，结果均不一样

**Comment by yindisun** [comment]
同时，希望能有个交流群，有好多疑问想请教

**Comment by AlongWY** [comment]
demo 的设置是 dep(fast=False), sdp(mode='mix')
