### ISSUE TITLE
SRL示例问题

### ISSUE THREAD

**Issue by xinyubai1209** [HIT-SCIR/ltp#500]

**Comment by xinyubai1209** [comment]
文档快速上手教程中，SRL示例输出谓词“叫”的语义角色ARG2的起始位置为3和5，分词结果为：[['他', '叫', '汤姆', '去', '拿', '外衣', '。']]。
ARG2是“去拿外衣”还是“拿外衣”？示例中是：叫 -> [ARG0: 他, ARG1: 汤姆, ARG2: 拿外衣]
如果是“拿外衣”，那么输出语义角色起始位置区间是否为左开右闭(3, 5]？
教程地址：https://ltp.readthedocs.io/zh_CN/latest/quickstart.html

**Comment by AlongWY** [comment]
谢谢你的提醒，应该是去拿外衣，这里是写错了
