### ISSUE TITLE
在加载LTP模型时出现 Can't get attribute '_gpus_arg_default' on <module 'pytorch_lightning.utilities.argparse' ...

### ISSUE THREAD

**Issue by ScottishFold007** [HIT-SCIR/ltp#504]
在加载LTP模型时出现这个问题：

![image](https://user-images.githubusercontent.com/36957508/115117156-c65d9300-9fcf-11eb-815f-c190d7845888.png)

**Comment by AlongWY** [comment]
可以尝试升级一下ltp的版本，最新的版本应该解决了该问题
