### ISSUE TITLE
网站上、ltp small、ltp base三者对于“浮士德与魔鬼达成协议。”句法解析的结果都不一样。

### ISSUE THREAD

**Issue by jialin666** [HIT-SCIR/ltp#505]
在线网站上句法解析是正确的，ltp small 将ADV解析为LAD，ltp base解析为coo，感觉还是3.x版本的解析效果更好呢。

**Comment by AlongWY** [comment]
在线网站上也是 4.0 版本，可能是某些设置不一样

**Comment by AlongWY** [comment]
较小的模型相对来说精度没有这么高
