### ISSUE TITLE
本次LTP4 v4.1.4升級、Small(v3) 模型似乎將太多詞彙黏著在一起

### ISSUE THREAD

**Issue by kanasimi** [HIT-SCIR/ltp#507]
本次LTP4 v4.1.4升級、Small(v3) 模型似乎將太多詞彙黏著在一起
例如
富贵人家更是费尽心思夸显华采。 → a:富贵人家+d:更是+v:费尽心思夸显华采+wp:。
所以自己已经成了宁采臣二代？ → c:所以+r:自己+d:已经+v:成+u:了+nh:宁采臣二代+wp:？
派我们的吴广及周文大将军带着百万大军攻打咸阳城去了。 → v:派+r:我们+u:的+nh:吴广及+nh:周文大将军+v:带+u:着+m:百万+n:大军+v:攻打+ns:咸阳城去+u:了+wp:。
露营扎帐篷。 → n:露营扎帐篷+wp:。
搬着小马扎过来了。 → v:搬+u:着+a:小马扎过来+u:了+wp:。
先入咸阳者为王。 → d:先入咸阳者为王+wp:。
就等着老头子一旦升天，他就坐稳单于之位。 → d:就+v:等+u:着+n:老头子+d:一旦+v:升天+wp:，+r:他+d:就+v:坐稳单于之位+wp:。
小心别扭伤。 → a:小心别扭伤+wp:。
他们的领导不叫皇帝，而叫单于。 → r:他们+u:的+n:领导+d:不+v:叫+n:皇帝+wp:，+c:而叫单于+wp:。
军臣单于心儿一紧。 → n:军臣+v:单于心儿一紧+wp:。
乌维单于子詹师庐接班。 → nh:乌维单于子詹师庐+v:接班+wp:。
姜先生在园里种姜。 → nh:姜+n:先生+p:在+nl:园里+ **v:种姜** +wp:。

先前的4.1.3版本中沒此問題
這些太長的詞會被拆分

**Comment by AlongWY** [comment]
我们会尽快检查该问题
