### ISSUE TITLE
 'Version' object has no attribute 'major'

### ISSUE THREAD

**Issue by Qin-ai** [HIT-SCIR/ltp#509]
执行ltp.seg(["他叫汤姆去拿外衣。"])语句时：
if transformers_version.major >= 3 and transformers_version.major > 1:
    247             kwargs = {'is_split_into_words': is_preseged}
    248         else:

AttributeError: 'Version' object has no attribute 'major'

**Comment by zejunwang1** [comment]
+1

**Comment by AlongWY** [comment]
`pip install -U pip` 试一下？

**Comment by zejunwang1** [comment]
还是报错，你这个pip install ltp一键安装后能跑通吗。。

**Comment by scanf3** [comment]
packaging这个包的问题，升级到20.0以上就行了  pip install packaging==20.0

**Comment by Duncanswilson** [comment]
just to save someone else from having to google translate the above:

> For packaging problems, just upgrade to 20.0 or higher. `pip install packaging==20.0`
