### ISSUE TITLE
ltp对英文语义依存分析结果的疑问与求助

### ISSUE THREAD

**Issue by Cyich** [HIT-SCIR/ltp#510]
请问一下，对英文句子进行SDP分析，如何得到格式化的结果呢？
ltp.ai 的demo演示结果效果还可以 ，但是只有一个示意图（或者是我没找到格式化输出？）

而通过pip install ltp，调用ltp.sdp得到的结果不太好（是最新的ltp 4.1.4），不知道是small的分析效果问题还是对英文句子分析的支持度不够？希望得到解答，谢谢！
调用ltp.sdp的测试结果如下，可以看到SDP分析结果输出为空：

from ltp import LTP
ltp = LTP()
seg, hidden = ltp.seg(["The boy wants to go to school."])
sdp = ltp.sdp(hidden)
print(sdp)
[[]]
seg, hidden = ltp.seg(["Iraqi Vice President Taha Yasin Ramadan, speaking on Iraqi Radio, was quoted by the British Broadcasting Corp.'s monitoring service as accusing Britain and the United States of working to ``eliminate'' the state of Iraq."])
sdp = ltp.sdp(hidden)
print(sdp)
[[]]

希望尽快得到答复，十分感谢！（通过什么方式能够得到ltp.ai的demo演示结果示意图这种效果的格式化输出，望指路，感谢！）

**Comment by AlongWY** [comment]
现在没有提供过这种图示的API，可以自行绘制，另外，demo网站上的sdp参数为mode='mix'

**Comment by Cyich** [comment]
> 现在没有提供过这种图示的API，可以自行绘制，另外，demo网站上的sdp参数为mode='mix'

好的，感谢感谢！！可能我没有表达清楚，我想得到的恰恰不是分析结果图片，而是图片对应的结构化输出。另外进一步问下，demo网站上用的是4.1.4版本吗？（直接拉master就可以吗）

**Comment by AlongWY** [comment]
demo 网站是 4.1.3.post1
