### ISSUE TITLE
ltp = LTP()时报错

### ISSUE THREAD

**Issue by chenjie97** [HIT-SCIR/ltp#520]
![image](https://user-images.githubusercontent.com/55337872/123605894-e9f25480-d82e-11eb-8345-744137c56e03.png)
为啥会报这个错误呢？

**Comment by GuohyCoding** [comment]
蹲一个解答，同样的错误

**Comment by AlongWY** [comment]
看上去是路径解析出现了问题，应该是 transformers 那边没有考虑 windows 环境导致的，也许可以尝试手动加载本地模型？

**Comment by spindensity** [comment]
给个解答，不是路径冲突，而是 LTP 4.1.x 目前发布的模型文件不兼容 transformers 4.8.x，临时的解决方法：

```bash
pip install transformers==4.7.0
```

**Comment by liuyunwww** [comment]
按照上面说的改了，但是又出现#527的错误，而且是在能运行一段时间后。

**Comment by lycz91** [comment]
同样报这个错误。。。

**Comment by MySilentCat** [comment]
安装以下版本的包可以正常运行，ltp版本号为4.1.5.post2：
huggingface-hub-0.0.8 
ltp-4.1.5.post2 
pygtrie-2.4.2
sacremoses-0.0.45
tokenizers-0.10.3 t
ransformers-4.7.0

**Comment by MrYxJ** [comment]
> 安装以下版本的包可以正常运行，ltp版本号为4.1.5.post2：
> huggingface-hub-0.0.8
> ltp-4.1.5.post2
> pygtrie-2.4.2
> sacremoses-0.0.45
> tokenizers-0.10.3
> transformers-4.7.0

transformer 仍然显示 ImportError: cannot import name 'AutoModel'

**Comment by zy614582280** [comment]
> > 安装以下版本的包可以正常运行，ltp版本号为4.1.5.post2：
> > huggingface-hub-0.0.8
> > ltp-4.1.5.post2
> > pygtrie-2.4.2
> > sacremoses-0.0.45
> > tokenizers-0.10.3
> > transformers-4.7.0
> 
> transformer 仍然显示 ImportError: cannot import name 'AutoModel'

这个问题我也遇到了，我这边是由于torch的版本低了，transformers需要torch >=1.3.0。希望对你有帮助

**Comment by MrYxJ** [comment]
> > > 安装以下版本的包可以正常运行，ltp版本号为4.1.5.post2：
> > > huggingface-hub-0.0.8
> > > ltp-4.1.5.post2
> > > pygtrie-2.4.2
> > > sacremoses-0.0.45
> > > tokenizers-0.10.3
> > > transformers-4.7.0
> > 
> > 
> > transformer 仍然显示 ImportError: cannot import name 'AutoModel'
> 
> 这个问题我也遇到了，我这边是由于torch的版本低了，transformers需要torch >=1.3.0。希望对你有帮助

Yes，我后来将torch 1.2 -> torch 1.4，transformer 4.7后，报错解决。

**Comment by shm007g** [comment]
提供一组macos catalina 可行的组合：
```
pip install torch==1.7.0 torchvision==0.8.0 torchaudio==0.7.0
pip install tensorflow==1.15
pip install ltp==4.1.0

python -c "from ltp import LTP"
```

**Comment by MrYxJ** [comment]
谢谢，MrYx已经收到您的邮件!

**Comment by zxmei1** [comment]
mac Monterey 组合：

pip install torch==1.7.0 torchvision==0.8.0 torchaudio==0.7.0
pip install transformer==3.5.1
pip intall ltp==4.1.0

试了一个多小时才试出来......

**Comment by MrYxJ** [comment]
谢谢，MrYx已经收到您的邮件!
