### ISSUE TITLE
ImportError: cannot import name 'LTP' from 'ltp' 

### ISSUE THREAD

**Issue by liuyunwww** [HIT-SCIR/ltp#521]
pip install ltp成功

(Demo) E:\文本分类\Demo>pip install ltp
Collecting ltp
  Downloading ltp-4.1.5-py3-none-any.whl (94 kB)
     |████████████████████████████████| 94 kB 103 kB/s
Collecting transformers<5.0,>=4.0.0
  Downloading transformers-4.8.2-py3-none-any.whl (2.5 MB)
     |████████████████████████████████| 2.5 MB 262 kB/s
Collecting pygtrie<2.5,>=2.3.0
  Downloading pygtrie-2.4.2.tar.gz (35 kB)
Collecting packaging>=20.0
  Downloading packaging-20.9-py2.py3-none-any.whl (40 kB)
     |████████████████████████████████| 40 kB 63 kB/s
Collecting torch>=1.2.0
  Downloading torch-1.9.0-cp37-cp37m-win_amd64.whl (222.0 MB)
     |████████████████████████████████| 222.0 MB 13 kB/s
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read
timed out. (read timeout=15)")': /simple/requests/
Collecting requests
  Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 178 kB/s
Collecting sacremoses
  Downloading sacremoses-0.0.45-py3-none-any.whl (895 kB)
     |████████████████████████████████| 895 kB 198 kB/s
Collecting numpy>=1.17
  Downloading numpy-1.21.0-cp37-cp37m-win_amd64.whl (13.9 MB)
     |████████████████████████████████| 13.9 MB 285 kB/s
Collecting huggingface-hub==0.0.12
  Downloading huggingface_hub-0.0.12-py3-none-any.whl (37 kB)
Collecting regex!=2019.12.17
  Downloading regex-2021.7.1-cp37-cp37m-win_amd64.whl (269 kB)
     |████████████████████████████████| 269 kB 345 kB/s
Collecting tokenizers<0.11,>=0.10.1
  Downloading tokenizers-0.10.3-cp37-cp37m-win_amd64.whl (2.0 MB)
     |████████████████████████████████| 2.0 MB 252 kB/s
Collecting filelock
  Downloading filelock-3.0.12-py3-none-any.whl (7.6 kB)
Collecting pyyaml
  Downloading PyYAML-5.4.1-cp37-cp37m-win_amd64.whl (210 kB)
     |████████████████████████████████| 210 kB 312 kB/s
Collecting importlib-metadata; python_version < "3.8"
  Downloading importlib_metadata-4.6.0-py3-none-any.whl (17 kB)
Collecting tqdm>=4.27
  Downloading tqdm-4.61.1-py2.py3-none-any.whl (75 kB)
     |████████████████████████████████| 75 kB 114 kB/s
Collecting pyparsing>=2.0.2
  Downloading pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
     |████████████████████████████████| 67 kB 67 kB/s
Collecting typing-extensions
  Downloading typing_extensions-3.10.0.0-py3-none-any.whl (26 kB)
Collecting idna<3,>=2.5
  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 25 kB/s
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.6-py2.py3-none-any.whl (138 kB)
     |████████████████████████████████| 138 kB 39 kB/s
Collecting chardet<5,>=3.0.2
  Downloading chardet-4.0.0-py2.py3-none-any.whl (178 kB)
     |████████████████████████████████| 178 kB 96 kB/s
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\envs\demo\lib\site-packages (from requests->transformers<5.0,>=4.0.0->ltp) (2020.6.20)
Collecting click
  Downloading click-8.0.1-py3-none-any.whl (97 kB)
     |████████████████████████████████| 97 kB 82 kB/s
Collecting joblib
  Downloading joblib-1.0.1-py3-none-any.whl (303 kB)
     |████████████████████████████████| 303 kB 145 kB/s
Collecting six
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting zipp>=0.5
  Downloading zipp-3.5.0-py3-none-any.whl (5.7 kB)
Collecting colorama; platform_system == "Windows"
  Downloading colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Building wheels for collected packages: pygtrie
  Building wheel for pygtrie (setup.py) ... done
  Created wheel for pygtrie: filename=pygtrie-2.4.2-py3-none-any.whl size=19067 sha256=41a22bae080502c8a587cd8e8fe43942bd1b2df3528c800a034ff853d7d4a8e8
  Stored in directory: c:\users\administrator\appdata\local\pip\cache\wheels\d3\f8\ba\1d828b1603ea422686eb694253a43cb3a5901ea4696c1e0603
Successfully built pygtrie
Installing collected packages: idna, urllib3, chardet, requests, tqdm, zipp, typing-extensions, importlib-metadata, colorama, click, joblib, regex, six, sacremoses, numpy, pyparsing, pack
aging, filelock, huggingface-hub, tokenizers, pyyaml, transformers, pygtrie, torch, ltp
Successfully installed chardet-4.0.0 click-8.0.1 colorama-0.4.4 filelock-3.0.12 huggingface-hub-0.0.12 idna-2.10 importlib-metadata-4.6.0 joblib-1.0.1 ltp-4.1.5 numpy-1.21.0 packaging-20.
9 pygtrie-2.4.2 pyparsing-2.4.7 pyyaml-5.4.1 regex-2021.7.1 requests-2.25.1 sacremoses-0.0.45 six-1.16.0 tokenizers-0.10.3 torch-1.9.0 tqdm-4.61.1 transformers-4.8.2 typing-extensions-3.1
0.0.0 urllib3-1.26.6 zipp-3.5.0

**Comment by liuyunwww** [comment]
![image](https://user-images.githubusercontent.com/29895612/124343038-1d502d00-dbfb-11eb-842e-a0b280e0be8a.png)
就是运行文件不成功，但一句句运行代码就可以。是我哪里有问题吗？

**Comment by liuyunwww** [comment]
![03`JXWMDFAJ35M5M CO5@LX](https://user-images.githubusercontent.com/29895612/124350791-4edfed00-dc29-11eb-860b-a081ca735f3c.png)
找到原因了，必须是某个文件夹下的文件才能成功。

**Comment by liuyunwww** [comment]
![03`JXWMDFAJ35M5M CO5@LX](https://user-images.githubusercontent.com/29895612/124350791-4edfed00-dc29-11eb-860b-a081ca735f3c.png)
找到原因了，必须是某个文件夹下的文件才能成功。

**Comment by yslion** [comment]
> ![image](https://user-images.githubusercontent.com/29895612/124343038-1d502d00-dbfb-11eb-842e-a0b280e0be8a.png) 就是运行文件不成功，但一句句运行代码就可以。是我哪里有问题吗？

原因在于你的文件名和包名一样了 都叫ltp

**Comment by yslion** [comment]
> ![image](https://user-images.githubusercontent.com/29895612/124343038-1d502d00-dbfb-11eb-842e-a0b280e0be8a.png) 就是运行文件不成功，但一句句运行代码就可以。是我哪里有问题吗？

原因在于你的文件名和包名一样了 都叫ltp
