### ISSUE TITLE
加载错误 

### ISSUE THREAD

**Issue by znsoftm** [HIT-SCIR/ltp#524]
Exception has occurred: ValueError
unable to parse C:\Users\ma139/.cache\torch\ltp\ad382b14b05a2c95f3d034e1b6fd453ccec7d0e0c6444d1d2e7f2a20e783d51c-0315782f0f5abaeb286773e210d34d371ee7fb983c9c44f632229e18da24affa-extracted\tokenizer_config.json as a URL or as a local path
  File "H:\text-class-match\bilstm\ltp-test.py", line 3, in <module>
    ltp=LTP()

**Comment by znsoftm** [comment]
When it finished downloading the data, it missed the file tokenizer_config.json

**Comment by RockNHawk** [comment]
I have the same issue with `python server.py`

**Comment by MySilentCat** [comment]
I also encountered the same problem, but when I executed it on Google Colab, I found that the tokenizer_config.json file was not found in the model file downloaded from the virtual machine, but it did execute normally. So I installed the same LTP version as the Colab virtual machine on the local Windows, and the tokenizer_config.json file did execute correctly in the local, I think this can help you to some extent, the following is the colab package version information. Note that the VERSION number of LTP is 4.1.5.post2
```huggingface-hub==0.0.8 
ltp==4.1.5.post2 
pygtrie==2.4.2 
sacremoses==0.0.45 
tokenizers==0.10.3 
transformers==4.7.0

##Here is the test code execution

ltp = LTP()
 seg, hidden = ltp.seg(["你今天吃饭了吗？"])
 dep = ltp.dep(hidden)
 print(seg) ##[['你', '今天', '吃饭', '了', '吗', '？']]
 print(dep) ##[[(1, 3, 'SBV'), (2, 3, 'ADV'), (3, 0, 'HED'), (4, 3, 'RAD'), (5, 3, 'RAD'), (6, 3, 'WP')]]
```

**Comment by syw1996** [comment]
> I also encountered the same problem, but when I executed it on Google Colab, I found that the tokenizer_config.json file was not found in the model file downloaded from the virtual machine, but it did execute normally. So I installed the same LTP version as the Colab virtual machine on the local Windows, and did execute correctly in the local without the tokenizer_config.json file, I think this can help you to some extent, the following is the colab package version information. Note that the VERSION number of LTP is 4.1.5.post2
> 
> ```
> ltp==4.1.5.post2 
> pygtrie==2.4.2 
> sacremoses==0.0.45 
> tokenizers==0.10.3 
> transformers==4.7.0
> 
> ##Here is the test code execution
> 
> ltp = LTP()
>  seg, hidden = ltp.seg(["你今天吃饭了吗？"])
>  dep = ltp.dep(hidden)
>  print(seg) ##[['你', '今天', '吃饭', '了', '吗', '？']]
>  print(dep) ##[[(1, 3, 'SBV'), (2, 3, 'ADV'), (3, 0, 'HED'), (4, 3, 'RAD'), (5, 3, 'RAD'), (6, 3, 'WP')]]
> ```

主要和transformers和torch版本有关系，我最新的transformers==4.9.2也是报这个错，回退到4.7版本确实解决了，有必要和实验室的师弟说一下，在readme中备注一下，防止以后再有人踩雷
