### ISSUE TITLE
依存句法问题

### ISSUE THREAD

**Issue by slyfox1201** [HIT-SCIR/ltp#528]
最开始我使用的small模型，然后有不少句子，依存句法树存在问题
我换成base模型后，还是有问题，具体问题如下（基于base模型）：
eg：等下去干嘛你
结果：
等	下去	干嘛	你
v	v	v	r
0	1	1	0
HED|CMP|COO|HED

即，同一句话里有两个HED，这在3.0时是没有这个问题的。请教一下，是我哪里参数设置错了，导致依存树变成了依存图吗？

**Comment by AlongWY** [comment]
试试把 fast 参数改为 False

```
dep = ltp.dep(hidden, fast=False)
```

**Comment by slyfox1201** [comment]
@AlongWY 谢谢，是这个问题，改了下参数就好了
