### ISSUE TITLE
 安装失败问题

### ISSUE THREAD

**Issue by nkjulia** [HIT-SCIR/ltp#529]
错误片段，麻烦告知下，如何处理呢？

/code/pyltp/pyltp/ltp/thirdparty/eigen/Eigen/src/Core/arch/AVX512/PacketMath.h: In function ‘Packet Eigen::internal::preduxp(const Packet*) [with Packet = __vector(16) float]’:
/code/pyltp/pyltp/ltp/thirdparty/eigen/Eigen/src/Core/arch/AVX512/PacketMath.h:663:56: error: expected ‘,’ or ‘;’ before ‘__m256’
   __m256 OUTPUT##_0 = _mm512_extractf32x8_ps(INPUT, 0) __m256 OUTPUT##_1 = \
                                                        ^~~~~~
/code/pyltp/pyltp/ltp/thirdparty/eigen/Eigen/src/Core/arch/AVX512/PacketMath.h:689:3: note: in expansion of macro ‘EIGEN_EXTRACT_8f_FROM_16f’
   EIGEN_EXTRACT_8f_FROM_16f(vecs[0], vecs0);
   ^~~~~~~~~~~~~~~~~~~~~~~~~
/code/pyltp/pyltp/ltp/thirdparty/eigen/Eigen/src/Core/arch/AVX512/PacketMath.h:663:56: error: expected ‘,’ or ‘;’ before ‘__m256’
   __m256 OUTPUT##_0 = _mm512_extractf32x8_ps(INPUT, 0) __m256 OUTPUT##_1 = \
                                                        ^~~~~~
/code/pyltp/pyltp/ltp/thirdparty/eigen/Eigen/src/Core/arch/AVX512/PacketMath.h:690:3: note: in expansion of macro ‘EIGEN_EXTRACT_8f_FROM_16f’
   EIGEN_EXTRACT_8f_FROM_16f(vecs[1], vecs1);
   ^~~~~~~~~~~~~~~~~~~~~~~~~
/code/pyltp/pyltp/ltp/thirdparty/eigen/Eigen/src/Core/arch/AVX512/PacketMath.h:663:56: error: expected ‘,’ or ‘;’ before ‘__m256’
   __m256 OUTPUT##_0 = _mm512_extractf32x8_ps(INPUT, 0) __m256 OUTPUT##_1 = \
                                                        ^~~~~~
/code/pyltp/pyltp/ltp/thirdparty/eigen/Eigen/src/Core/arch/AVX512/PacketMath.h:691:3: note: in expansion of macro ‘EIGEN_EXTRACT_8f_FROM_16f’
   EIGEN_EXTRACT_8f_FROM_16f(vecs[2], vecs2);
   ^~~~~~~~~~~~~~~~~~~~~~~~~
/code/pyltp/pyltp/ltp/thirdparty/eigen/Eigen/src/Core/arch/AVX512/PacketMath.h:663:56: error: expected ‘,’ or ‘;’ before ‘__m256’
   __m256 OUTPUT##_0 = _mm512_extractf32x8_ps(INPUT, 0) __m256 OUTPUT##_1 = \
                                                        ^~~~~~
/code/pyltp/pyltp/ltp/thirdparty/eigen/Eigen/src/Core/arch/AVX512/PacketMath.h:692:3: note: in expansion of macro ‘EIGEN_EXTRACT_8f_FROM_16f’
   EIGEN_EXTRACT_8f_FROM_16f(vecs[3], vecs3);
   ^~~~~~~~~~~~~~~~~~~~~~~~~
/code/pyltp/pyltp/ltp/thirdparty/eigen/Eigen/src/Core/arch/AVX512/PacketMath.h:663:56: error: expected ‘,’ or ‘;’ before ‘__m256’
   __m256 OUTPUT##_0 = _mm512_extractf32x8_ps(INPUT, 0) __m256 OUTPUT##_1 = \
                                                        ^~~~~~
/code/pyltp/pyltp/ltp/thirdparty/eigen/Eigen/src/Core/arch/AVX512/PacketMath.h:693:3: note: in expansion of macro ‘EIGEN_EXTRACT_8f_FROM_16f’
   EIGEN_EXTRACT_8f_FROM_16f(vecs[4], vecs4);
   ^~~~~~~~~~~~~~~~~~~~~~~~~
/code/pyltp/pyltp/ltp/thirdparty/eigen/Eigen/src/Core/arch/AVX512/PacketMath.h:663:56: error: expected ‘,’ or ‘;’ before ‘__m256’
   __m256 OUTPUT##_0 = _mm512_extractf32x8_ps(INPUT, 0) __m256 OUTPUT##_1 = \
                                                        ^~~~~~
/code/pyltp/pyltp/ltp/thirdparty/eigen/Eigen/src/Core/arch/AVX512/PacketMath.h:694:3: note: in expansion of macro ‘EIGEN_EXTRACT_8f_FROM_16f’
   EIGEN_EXTRACT_8f_FROM_16f(vecs[5], vecs5);
   ^~~~~~~~~~~~~~~~~~~~~~~~~
/code/pyltp/pyltp/ltp/thirdparty/eigen/Eigen/src/Core/arch/AVX512/PacketMath.h:663:56: error: expected ‘,’ or ‘;’ before ‘__m256’
   __m256 OUTPUT##_0 = _mm512_extractf32x8_ps(INPUT, 0) __m256 OUTPUT##_1 = \
                                                        ^~~~~~
/code/pyltp/pyltp/ltp/thirdparty/eigen/Eigen/src/Core/arch/AVX512/PacketMath.h:695:3: note: in expansion of macro ‘EIGEN_EXTRACT_8f_FROM_16f’
   EIGEN_EXTRACT_8f_FROM_16f(vecs[6], vecs6);
   ^~~~~~~~~~~~~~~~~~~~~~~~~
/code/pyltp/pyltp/ltp/thirdparty/eigen/Eigen/src/Core/arch/AVX512/PacketMath.h:663:56: error: expected ‘,’ or ‘;’ before ‘__m256’
   __m256 OUTPUT##_0 = _mm512_extractf32x8_ps(INPUT, 0) __m256 OUTPUT##_1 = \
                                                        ^~~~~~
/code/pyltp/pyltp/ltp/thirdparty/eigen/Eigen/src/Core/arch/AVX512/PacketMath.h:696:3: note: in expansion of macro ‘EIGEN_EXTRACT_8f_FROM_16f’
   EIGEN_EXTRACT_8f_FROM_16f(vecs[7], vecs7);
   ^~~~~~~~~~~~~~~~~~~~~~~~~
/code/pyltp/pyltp/ltp/thirdparty/eigen/Eigen/src/Core/arch/AVX512/PacketMath.h:663:56: error: expected ‘,’ or ‘;’ before ‘__m256’
   __m256 OUTPUT##_0 = _mm512_extractf32x8_ps(INPUT, 0) __m256 OUTPUT##_1 = \
                                                        ^~~~~~
/code/pyltp/pyltp/ltp/thirdparty/eigen/Eigen/src/Core/arch/AVX512/PacketMath.h:697:3: note: in expansion of macro ‘EIGEN_EXTRACT_8f_FROM_16f’
   EIGEN_EXTRACT_8f_FROM_16f(vecs[8], vecs8);
   ^~~~~~~~~~~~~~~~~~~~~~~~~
/code/pyltp/pyltp/ltp/thirdparty/eigen/Eigen/src/Core/arch/AVX512/PacketMath.h:663:56: error: expected ‘,’ or ‘;’ before ‘__m256’
   __m256 OUTPUT##_0 = _mm512_extractf32x8_ps(INPUT, 0) __m256 OUTPUT##_1 = \
                                                        ^~~~~~
/code/pyltp/pyltp/ltp/thirdparty/eigen/Eigen/src/Core/arch/AVX512/PacketMath.h:698:3: note: in expansion of macro ‘EIGEN_EXTRACT_8f_FROM_16f’
   EIGEN_EXTRACT_8f_FROM_16f(vecs[9], vecs9);
   ^~~~~~~~~~~~~~~~~~~~~~~~~
/code/pyltp/pyltp/ltp/thirdparty/eigen/Eigen/src/Core/arch/AVX512/PacketMath.h:663:56: error: expected ‘,’ or ‘;’ before ‘__m256’

**Comment by AlongWY** [comment]
请报告一下
操作系统版本
编译器版本
Python版本
