### ISSUE TITLE
出现了这个bug: RuntimeError: CUDA out of memory. Tried to allocate 7.46 GiB (GPU 0; 10.76 GiB total capacity; 758.05 MiB already allocated; 7.45 GiB free; 772.00 MiB reserved in total by PyTorch)

### ISSUE THREAD

**Issue by ghliu521** [HIT-SCIR/ltp#530]

**Comment by ghliu521** [comment]
ltp很吃GPU资源吗？

**Comment by AlongWY** [comment]
应该是batch开的太大了？

**Comment by ghliu521** [comment]
> 应该是batch开的太大了？

我代码使用的是keras，就时ltp这个库依赖的是pytorch和transformer...

**Comment by Gavingx** [comment]
> ltp很吃GPU资源吗？

请问你解决了吗？ 我在初始化的时候也遇到了这个问题，重装ltp也没用

**Comment by ghliu521** [comment]
> > ltp很吃GPU资源吗？
> 
> 请问你解决了吗？ 我在初始化的时候也遇到了这个问题，重装ltp也没用

我记得当时是ltp操作转换的列表太大了。。。

**Comment by geasyheart** [comment]
batch调小点，再debug看下代码，跟keras没关

**Comment by ghliu521** [comment]
> batch调小点，再debug看下代码，跟keras没关

我只是用这个进行分词，得到词性，哪里来的batch?

**Comment by conan1024hao** [comment]
lz是不是开了多线程，少开几个会好一点
