### ISSUE TITLE
发现一个小bug

### ISSUE THREAD

**Issue by geasyheart** [HIT-SCIR/ltp#538]
在这一行[transformer_rel_linear.py](https://github.com/HIT-SCIR/ltp/blob/f3d4a25ee2fbb71613f76c99a47e70a5445b8c03/ltp/transformer_rel_linear.py#L49)，是不是应该
由:
```python
if not self.use_cls:
```

改成:
```python
if not self.use_sep:
```

**Comment by AlongWY** [comment]
谢谢提醒！！！确实是的

**Comment by geasyheart** [comment]
还有一个小问题，在[这一行](https://github.com/HIT-SCIR/ltp/blob/f3d4a25ee2fbb71613f76c99a47e70a5445b8c03/ltp/transformer_rel_linear.py#L58)，我认为这一行进行gather有些不对，因为padding部分（值为0）那么将会取sequence_length那一维第一个index的值。

但是为什么没有影响，因为有word_attention_mask的缘故。

另外我认为这一行不加貌似也没有影响，在计算loss的时候也是因为有word_attention_mask的缘故就会忽略掉这些。
