### ISSUE TITLE
pyltp和新版ltp之间的差别在哪里呢

### ISSUE THREAD

**Issue by jwc19890114** [HIT-SCIR/ltp#541]
最近在做事件抽取的任务，发现很多项目都是用pyltp写的，用ltp4重写方法的时候找不到pyltp输出结果，可以出一个教程么

**Comment by AlongWY** [comment]
可以参考这个 [quickstart](https://github.com/HIT-SCIR/ltp/blob/master/docs/quickstart.rst)
