### ISSUE TITLE
LTP平台与python中的ltp包分词结果不同

### ISSUE THREAD

**Issue by nanmu52** [HIT-SCIR/ltp#542]
python 中的ltp包分词不准，如何解决呢？
比如对于“客厅的房顶上有一盏银色的大吊灯”这一句话，在LTP平台上的分词结果为[客厅   的   房顶  上  有  一  盏   银色   的   大   吊灯],而在python语言中调用ltp包或者pyltp包的分词结果为[客厅   的   房顶  上  有  一  盏   银色   的   大吊灯].还有很多类似的例子.请问这有什么解决的办法吗?

**Comment by kanasimi** [comment]
是不是因為模型不同? 記得LTP平台採用 Base系列?
