### ISSUE TITLE
4.x全部有没完没了的bug

### ISSUE THREAD

**Issue by Desperado-Jia** [HIT-SCIR/ltp#545]

**Comment by Desperado-Jia** [comment]
AttributeError: Can't get attribute '_gpus_arg_default' on <module 'pytorch_lightning.utilities.argparse' from '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pytorch_lightning/utilities/argparse.py'>
 torch版本1.8以上全部不能使用

**Comment by sipie800** [comment]
same here

**Comment by AlongWY** [comment]
新的版本已经修复了该问题
