### ISSUE TITLE
ImportError: cannot import name 'tune_train'。执行 task_named_entity_recognition.py 。

### ISSUE THREAD

**Issue by wn1652400018** [HIT-SCIR/ltp#546]
执行 task_named_entity_recognition.py ，直接报该异常，ImportError: cannot import name 'tune_train'。

_Originally posted by @AlongWY in https://github.com/HIT-SCIR/ltp/issues/513#issuecomment-845608331_

**Comment by wn1652400018** [comment]
python 3.6.9
pytorch 1.9.0
ltp 4.1.5.post2
pytoch_lightning 1.5.3

**Comment by AlongWY** [comment]
需要安装 ray[tune]
