### ISSUE TITLE
sdp输出结果的维数出错

### ISSUE THREAD

**Issue by AlfredAM** [HIT-SCIR/ltp#550]
text = "像是一个220万2.07发动机。"
seg, hidden = ltp.seg([text])
sdp = ltp.sdp(hidden)

print(len(seg[0]))
print(seg[0])
print(len(sdp[0]))
print(sdp[0])

输出结果：
7
['像', '是', '一个', '220万', '2.07', '发动机', '。']
8
[(1, 0, 'Root'), (1, 2, 'mDEPD'), (2, 0, 'Root'), (3, 6, 'MEAS'), (4, 6, 'FEAT'), (5, 6, 'FEAT'), (6, 2, 'LINK'), (7, 2, 'mPUNC')]

ltp          4.1.5.post2
python   3.7.9
OS          windows 10

**Comment by AlfredAM** [comment]
@AlongWY  ltp提供了非常好的平台，在很多任务上表现出色。请问这个输出如何修正呢？谢谢！

**Comment by AlongWY** [comment]
这个结果是正常的，默认输出是 sdpg，如果要依存树的话传入参数 mode = "tree" 即可
