### ISSUE TITLE
语义依存图的分析结果有误

### ISSUE THREAD

**Issue by WitcherLeo** [HIT-SCIR/ltp#551]
ltp版本：4.1.5.post2
pytorch: 1.6.0
对文本进行语义依存分析时指定mode=='graph'，即采用图结构进行语义依存分析，结果中存在大量的词没有连接到图上，与其它部分脱离，甚至有时候不存在指向根节点的节点，导致输出的图结构完全无法进行遍历和分析。但是语义依存树、句法依存树不会出现这样的问题，至少它们都是正确的树结构，而语义依存图的输出结构很多时候连图结构都不是，甚至会出现环，这不符合语义依存图是有向无环图的定义。

**Comment by AlongWY** [comment]
尝试一下 mode = "mix"?
