### ISSUE TITLE
srl 多个角色如何标注？

### ISSUE THREAD

**Issue by yhj997248885** [HIT-SCIR/ltp#560]
请问一个词有多个角色如何标注？

# srl 格式文件
百团大战	_	B-ARG0	O	O	O
的	_	I-ARG0	O	O	O
战略	_	I-ARG0	O	O	O
目的	_	I-ARG0	O	O	O
是	Y	O	O	O	O
要	Y	B-ARG1	O	O	O
打破	Y	I-ARG1	O	O	O

他
叫 -> [ARG0: 他, ARG1: 汤姆, ARG2: 去拿外衣]
汤姆
去
拿 -> [ARG0: 汤姆, ARG1: 外衣]
外衣
。
汤姆有2个role，在srl.txt中，[ARG0: 汤姆, ARG1: 外衣]是 标注在第四列 还是 标注在第三列并用 | 之类的符号分隔开

**Comment by qdchenxiaoyan** [comment]
他	_	B-A0	O	O	O	O
叫	Y	O	O	O	O	O
汤姆	_	B-A1	B-A0	O	O	O
去	_	B-A2	O	O	O	O
拿	Y	I-A2	O	O	O	O
外衣	_	I-A2	B-A1	O	O	O
。	_	O	O	O	O	O

我看数据读取的代码，推测数据格式应该是这样的，但是具体的列数是不是固定的还是根据谓语数量变化我不太确定，给出的样例只有4列，但是显然有的句子不止4个谓词。

**Comment by yhj997248885** [comment]
> 他 _ B-A0 O O O O 叫 Y O O O O O 汤姆 _ B-A1 B-A0 O O O 去 _ B-A2 O O O O 拿 Y I-A2 O O O O 外衣 _ I-A2 B-A1 O O O 。 _ O O O O O
> 
> 我看数据读取的代码，推测数据格式应该是这样的，但是具体的列数是不是固定的还是根据谓语数量变化我不太确定，给出的样例只有4列，但是显然有的句子不止4个谓词。

谢谢。 @qdchenxiaoyan 我已经看过这部分源码了，它是有一个谓语动词就对应新的标签列，标签列的列数数不限，只要>=谓语个数就行。
