### ISSUE TITLE
在加载LTP模型时出现 Can't get attribute '_gpus_arg_default' on <module 'pytorch_lightning.utilities.argparse'

### ISSUE THREAD

**Issue by Reuben-Yang** [HIT-SCIR/ltp#562]
所有的4.*版本都试过了，全部都有这个问题........
Can't get attribute '_gpus_arg_default' on <module 'pytorch_lightning.utilities.argparse' from '/data/user/conda/envs/pretrain/lib/python3.7/site-packages/pytorch_lightning/utilities/argparse.py'>

**Comment by CheaSim** [comment]
https://github.com/Lightning-AI/lightning/issues/7031
这里好像解释了。
