### ISSUE TITLE
Error when 'pip install lip'  using m1 MacBook 

### ISSUE THREAD

**Issue by klyuhang9** [HIT-SCIR/ltp#565]
Hi, friends. I meet a problem when I use m1 MacBook install ltp.
I run the command
 `pip install lip`
There is the problem as follows:
`Using legacy 'setup.py install' for pygtrie, since package 'wheel' is not installed.
Building wheels for collected packages: tokenizers
  Building wheel for tokenizers (pyproject.toml) ... \`
The interface will get stuck here and not move forward. I don't know how to fix it.I wonder if it is incompatible with the M1 ARM architecture MacBook. I hope your help. Thanks a lot!

**Comment by SheriffRabbit** [comment]
看你名字是中文的 我就直接说了  首先你的pip命令有问题 pip lip  应该是ltp 然后m1是支持ltp的 只不过安装过程中需要rust环境 如果是用conda可以直接一键安装 如果装的是miniforge3的话 需要自己安装rust 安装rust因为apple版本的doc缺失所以会报错 需要到这个网址https://forge.rust-lang.org/infra/other-installation-methods.html 下载aarch64-apple-darwin 的安装包 然后点击安装包 在选择安装项的时候把doc取消掉 其他保留 然后再次安装pip install ltp即可
