### ISSUE TITLE
请问一下LTP分词用的是什么词典？

### ISSUE THREAD

**Issue by conan1024hao** [HIT-SCIR/ltp#567]
请问一下LTP分词用的是什么词典？
和日本人导师提到这个库，他很感兴趣，所以想问一下。

**Comment by geasyheart** [comment]
LTP是用BIOS标注训练出来的，没有词典。

**Comment by geasyheart** [comment]
LTP官网中附录部分没有写到分词的数据集：https://ltp.ai/docs/appendix.html#id2。

那估计是没有写到。

**Comment by conan1024hao** [comment]
@carfly 车教授求解答

**Comment by AlongWY** [comment]
训练分词使用的是人民日报分词数据集，使用BIO标注
模型是基于深度神经网络开发的，没有使用词典

**Comment by conan1024hao** [comment]
@AlongWY 谢谢！
