### ISSUE TITLE
请问可以不分词直接进行词性标注嘛

### ISSUE THREAD

**Issue by lelechallc** [HIT-SCIR/ltp#572]
请问可以不分词直接进行词性标注嘛，比如我现在已经有一个词典，需要进行词性标注

**Comment by geasyheart** [comment]
直接按BMES或者BIO来标就行，词典这东西感觉又回到了统计学习。

**Comment by lelechallc** [comment]
> 直接按BMES或者BIO来标就行，词典这东西感觉又回到了统计学习。

我是想对一些词进行人名实体识别，本生数据中的词是比较短的，想用ltp直接做二分类不知道是否可行

**Comment by geasyheart** [comment]
可以做二分类哇。输入词，判断是不是人名。这个自己搭个模型就行，很快速的。
但是相反你可以尝试下lac里面的人名识别，看看是否能满足你的期望。不行再自己训练。
