### ISSUE TITLE
如何高速处理5万多行的分词数据

### ISSUE THREAD

**Issue by liyanfu520** [HIT-SCIR/ltp#573]
为了处理5万多行的分词数据，改写了脚本案例
import sys,os,time
sys.path.append(os.path.abspath(os.path.dirname(__file__) + '/' + '..'))
from ltp import LTP
root_path=os.path.abspath(os.path.dirname(__file__) + '/' + '..')
ltp = LTP(path = "base")
url = "tests/zrbzdz.txt"
t1 = time.time()

url = "tests/zrbzdz.txt"
t1 = time.time()

output=''
with open(url,"r",encoding='utf-8-sig') as f:
    lines=f.readlines()
    for line in lines:
        segment, _ = ltp.seg([line])
        output+="/ ".join(segment[0])+'\n'

tt =  time.time()-t1

# 输出分词后的文件路径
LTP_f = open("tests/output/1_LTP.txt","wb")
LTP_f.write(output.encode('utf-8'))
LTP_f.close()

print('time ' + str(tt))

执行这个脚本，数据5万多条，执行时间43分钟，怎么解决这个时间长的问题

**Comment by liyanfu520** [comment]
如果是写成这种的

import sys,os,time

sys.path.append(os.path.abspath(os.path.dirname(__file__) + '/' + '..'))

from ltp import LTP
root_path=os.path.abspath(os.path.dirname(__file__) + '/' + '..')

ltp = LTP(path = "base")
url = "tests/zrbzdz.txt"
t1 = time.time()

contents = open(url,"r",encoding='utf-8-sig').read()
segment, _ = ltp.seg([contents])

output="/ ".join(segment[0])
# print(segment)
t2 = time.time()-t1

# 输出分词后的文件路径
LTP_f = open("tests/output/1_LTP.txt","wb")
LTP_f.write(output.encode('utf-8'))
LTP_f.close()

print('time ' + str(t2))

虽然执行脚本时间少，但是输出并不是逐行的，算是把所有数据当成一行数据来处理，而且数据被截断，显然是不行的

**Comment by geasyheart** [comment]
你的问题不在ltp，在于你读文本的方式。加快模型预测的方式，可以使用batch_size。
那么，你可以参考如下：

```python
def split_l(l, n=8):
    return [l[i:i + n] for i in range(0, len(l), n)]

lines = []
with open(your file) as f:
   for line in f:
      line = line.strip()
      lines.append(line)

for batch_data in split_l(lines, 32):
   output = ltp(batch_data)

```

建议你先学基础，再来问问题。

**Comment by liyanfu520** [comment]
感谢回答，这种方法有尝试过，我之前没有限制列表的长度，把5万多条数据都丢进列表，结果执行后电脑卡死，看来列表里面一次性不能放太多元素
我想知道第二种方法，就是把读取的所有数据作为一个字符串来输入，这样列表就只有一个元素了，但是字符串会被切割掉，而且回车符‘\n’也并没有留下，这种方法在jieba里面是可以实现的，不知道这里面如何实现，还是只能用上面的方法
jieba脚本

import time
import sys
sys.path.append("../")
import jieba
jieba.initialize()

# 输入需要分词的文件路径
url = "test/data/zrbzdz.txt"
content = open(url,"r",encoding='utf-8-sig').read()
t1 = time.time()
words = "/ ".join(jieba.cut(content))

t2 = time.time()-t1

# 输出分词后的文件路径
jieba_f = open("test/data/output/jieba_1.txt","wb")
jieba_f.write(words.encode('utf-8'))
jieba_f.close()

print('time ' + str(t2))

**Comment by AlongWY** [comment]
可以尝试一下我们新放出的 Legacy 模型

**Comment by liyanfu520** [comment]
好的，谢谢

**Comment by nxznm** [comment]
我加载legacy后`LTP(path = "legacy")`, 3kw行的语料分词加tokenize在单进程下只要1个多小时, 不过我一行的语料很短, 长度平均就25.

**Comment by 1191000606** [comment]
我这边2w行, 差不多半分钟.

具体思路是 多线程, 每个线程初始化一个LTP, 并且都放到GPU里, 一个进程一次循环处理差不多10条20条
