### ISSUE TITLE
4.2版本安装还存在较大不便

### ISSUE THREAD

**Issue by Liu131452** [HIT-SCIR/ltp#577]
1、 py37及以上版本
2、 需要pip install --upgrade transformers
3、from ltp import LTP   ltp = LTP("LTP/small")   需要电脑开发者模式，而且启动后还不能用。。
不能本地文件路径？

**Comment by AlongWY** [comment]
可以本地路径

**Comment by qq345736500** [comment]
请问现在线上的版本是LTP/small 还是 LTP/base 还是 LTP/base 。

**Comment by AlongWY** [comment]
LTP/small

**Comment by Liu131452** [comment]
![image](https://user-images.githubusercontent.com/84161060/186381820-9d1a692c-f25a-468a-a245-9c44ead16262.png)
1、新的模型文件重新下载后能够本地使用， from  https://huggingface.co/LTP/
2、SRL的输出为BIO，不直观

**Comment by AlongWY** [comment]
我确认一下，可能是tokenize对齐的问题

**Comment by MrRace** [comment]
使用`pip install ltp`安装的结果最新版本还是`4.1.5.post2`，如何安装4.2版本？

**Comment by AlongWY** [comment]
pip install ltp==4.2.6 -i https://pypi.org/simple
