### ISSUE TITLE
config.json not found in HuggingFace Hub

### ISSUE THREAD

**Issue by MachineSheep** [HIT-SCIR/ltp#578]
`from ltp import  LTP`
`ltp_model = LTP()`
报错
![image](https://user-images.githubusercontent.com/109952192/187012817-cb99831a-15d7-47e2-ac58-3a0f5a073aa4.png)

**Comment by SicongLiang** [comment]
我也遇到了这个问题，朋友解决了吗？

**Comment by MachineSheep** [comment]
> 我也遇到了这个问题，朋友解决了吗？

换个网络，用手机热点或者其他网，别用某些内网

**Comment by SicongLiang** [comment]
> 

但是我在公司，只能用内网应该。。。这个问题原因是什么呢？如果是config文件这些我可以下载下来吗

**Comment by MachineSheep** [comment]
> > 
> 
> 但是我在公司，只能用内网应该。。。这个问题原因是什么呢？如果是config文件这些我可以下载下来吗

按道理可以直接在huggingface上把LTP对应的模型文件夹安装下来，然后加载模型的时候指定路径，不过我在windows上尝试还是会报其他错误

**Comment by AlongWY** [comment]
也许版本不够新？

**Comment by gitforziio** [comment]
请问有人解决这个问题了吗？
以及如果手动下载模型，应该放在什么目录里？
谢谢
@AlongWY @SicongLiang @MachineSheep
