### ISSUE TITLE
语义角色分析关于动词V的问题

### ISSUE THREAD

**Issue by qq345736500** [HIT-SCIR/ltp#583]
在demo中显示的语义角色分析会提供修饰受词的动词。想请问一下是如何判断动词归属于哪一条角色分析链
![image](https://user-images.githubusercontent.com/31954765/188075113-cf75b013-a47e-42db-a31d-b5bd2bdce3cc.png)

**Comment by geasyheart** [comment]
本质来讲，获取分析链还是来自指向和被指向，获得一个无向图。你可以看看语义角色标注，那个可能有你更想要的。

**Comment by qq345736500** [comment]
> 本质来讲，获取分析链还是来自指向和被指向，获得一个无向图。你可以看看语义角色标注，那个可能有你更想要的。

是的，就是语义角色标注的问题呢，在api中动词被标注为"O"，我在实做时无法像线上demo一样将动词和分析结果连在一起，想请问一下是基于什么认为上图中的”吃“归属于第一条规则，而”还有“不属于任何一条规则。

**Comment by qq345736500** [comment]
![image](https://user-images.githubusercontent.com/31954765/188077877-4c41a233-1f25-4c53-97e2-99d0cdf9b2fe.png)

这个例子更直观一些，确实难以看出动词是基于什么写入的规则

**Comment by qq345736500** [comment]
不小心关掉了，，

**Comment by qq345736500** [comment]
@AlongWY 大佬帮忙看看~

**Comment by AlongWY** [comment]
4.2.7 版本默认把谓词和语义角色组合在一起了，也许你可以看一下是不是你想要的
