### ISSUE TITLE
M2的MAC能用吗？

### ISSUE THREAD

**Issue by megumin1204** [HIT-SCIR/ltp#584]
问下 如何兼容M2的MAC吗？普通pip安装貌似报错:
ImportError: dlopen(/opt/anaconda3/envs/nlp/lib/python3.7/site-packages/ltp_extension/ltp_extension.cpython-37m-darwin.so, 0x0002): tried: '/opt/anaconda3/envs/nlp/lib/python3.7/site-packages/ltp_extension/ltp_extension.cpython-37m-darwin.so' (mach-o file, but is an incompatible architecture (have (arm64), need (x86_64)))
这个问题有解决办法吗？ 谢谢

**Comment by AlongWY** [comment]
应当是可以的，我会尽快编译arm64版本的

**Comment by AlongWY** [comment]
M2 要求的 python 版本最低需要 3.8

**Comment by AlongWY** [comment]
最新的版本降低了对 python 版本的要求，M2 最低需要 python 3.7

**Comment by megumin1204** [comment]
> 最新的版本降低了对 python 版本的要求，M2 最低需要 python 3.7
嗯， 谢谢了
