### ISSUE TITLE
最新版本无法add_words

### ISSUE THREAD

**Issue by hackerchenzhuo** [HIT-SCIR/ltp#585]
报错：

> *** torch.nn.modules.module.ModuleAttributeError: 'LTP' object has no attribute 'add_words'

如果用add_word的话，在分词的时候报错：

> *** TypeError: argument 'sentence': 'list' object cannot be converted to 'PyString'

**Comment by AlongWY** [comment]
应当传入单个词语

**Comment by hackerchenzhuo** [comment]
单个单词也是一样的，报这个错误：

> *** TypeError: argument 'sentence': 'list' object cannot be converted to 'PyString'

**Comment by AlongWY** [comment]
好的 我确认一下

**Comment by AlongWY** [comment]
该问题在最新的 4.2.8 已经解决

**Comment by hackerchenzhuo** [comment]
我现在回退到了4.1.5版本，请问 4.2.8 和 4.1.5 的函数接口兼容吗？4.1.5我使用的

> ltp.add_words(words=add_words, max_window=10)

和

> segment, _ = ltp.seg([data])

进行的词添加和分词，不知道和4.2.8 是否兼容？

**Comment by AlongWY** [comment]
二者并不完全一样
