### ISSUE TITLE
[报错] add_words引起的 8786 abort (core dumped) 【base1，2，small模型都有】

### ISSUE THREAD

**Issue by hackerchenzhuo** [HIT-SCIR/ltp#586]
`from ltp import LTP`
`ltp = LTP("LTP/base1") `
`ltp.add_words(["他叫汤姆去拿外衣。", "我爱你"])`
`ltp.pipeline(["  AMF112-B 通讯系统 [SEP]"], tasks=["cws"])`
报如下错误：（
> (Pdb) ltp.pipeline(["  AMF112-B 通讯系统 [SEP]"], tasks=["cws"])
thread '<unnamed>' panicked at 'byte index 18 is not a char boundary; it is inside '统' (bytes 17..20) of `AMF112-B通讯系统[SEP]`', library/core/src/str/mod.rs:127:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[1]    8786 abort (core dumped)  python test.py

**Comment by hackerchenzhuo** [comment]
base2貌似也没有

**Comment by hackerchenzhuo** [comment]
经过测试，add_word也是一样的情况

**Comment by AlongWY** [comment]
也许你需要升级一下版本？

**Comment by AlongWY** [comment]
之后升级一下 ltp-extension 就可以了
```
pip install ltp-extension==0.1.7 -i https://pypi.org/simple
```

**Comment by AlongWY** [comment]
可以进行一下升级即可解决该问题
