### ISSUE TITLE
试用报错：TpyeError: argument 'scores': 'ndarry' object cannot be converted to 'Sequence'

### ISSUE THREAD

**Issue by pizts** [HIT-SCIR/ltp#588]
按照readme中安装ltp了，版本是4.2.8。
```
import torch
from ltp import LTP
output = ltp.pipeline(["他叫汤姆去拿外衣。"], tasks=["cws", "pos", "ner"])
```
是没有问题的，但是如果增加了dep的话，就会报错
```
import torch
from ltp import LTP
output = ltp.pipeline(["他叫汤姆去拿外衣。"], tasks=["cws", "pos", "ner", "dep"])
```

报错信息如下

Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "xxx/site-package/ltp/nerual.py", line 26, in wrapper
        return func(*args, **kwargs)
    File "xxx/site-package/ltp/nerual.py", line 186, in pipeline
        store[task] = self.post[task](result, hidden, store, inputs, tokenized)
    File "xxx/site-package/ltp/nerual.py", line 26, in wrapper
        return func(*args, **kwargs)
    File "xxx/site-package/ltp/nerual.py", line 437, in _dep_post
        arcs = [sequence for sequence in eisner(s_arc, length, True)]
TpyeError: argument 'scores': 'ndarry' object cannot be converted to 'Sequence'

环境 
python=3.7.4
torch=1.12.1
transformers=4.21.0
ltp=4.2.8
numpy=1.21.0
请问该如何解决呢

**Comment by AlongWY** [comment]
请尝试更新到如下版本 ![Screenshot_2022-09-07-22-53-11-883-edit_com microsoft emmx](https://user-images.githubusercontent.com/20281571/188909812-14df5403-2d1b-498b-a4b5-83a0686ecad3.jpg)

**Comment by pizts** [comment]
哦哦，试了一下，果然解决了错误，多谢
