### ISSUE TITLE
在进行一个总长度30万句子集合的分词时出现BUG：KeyError: 127

### ISSUE THREAD

**Issue by hackerchenzhuo** [HIT-SCIR/ltp#590]
```
 File "get_chinese_ref.py", line 118, in cws
    _output = ltp.pipeline(seq_data[b:e], tasks=["cws"])
  File "python3.8/site-packages/ltp/nerual.py", line 26, in wrapper
    return func(*args, **kwargs)
  File "python3.8/site-packages/ltp/nerual.py", line 186, in pipeline
    store[task] = self.post[task](result, hidden, store, inputs, tokenized)
  File "/home/chenzhuo/miniconda3/lib/python3.8/site-packages/ltp/nerual.py", line 26, in wrapper
    return func(*args, **kwargs)
  File "python3.8/site-packages/ltp/nerual.py", line 296, in _cws_post
```
**entities[-1].append((char_index[word_end[i - 1]] + 1, char_index[e]))**

```
KeyError: 127
```

这是为啥

**Comment by hackerchenzhuo** [comment]
加粗的应该是出错的那行源码，具体原因我也不清楚，127这个KEY可能有问题？

**Comment by AlongWY** [comment]
能不能把错误的这个例子挑出来一下

**Comment by hackerchenzhuo** [comment]
找到了，感觉是一个比较普遍的bug

> (Pdb) ltps.add_words(words=['tool'])
(Pdb) ltps.pipeline(['too low'], tasks=["cws"])
*** KeyError: 4

**Comment by AlongWY** [comment]
需要那个被分词的句子，不是这些

**Comment by hackerchenzhuo** [comment]
被分词的句子就是too low，这个句子

**Comment by hackerchenzhuo** [comment]
<img width="813" alt="image" src="https://user-images.githubusercontent.com/42081540/189510960-75702195-8033-4442-a6d4-e23bfaf887f4.png">

**Comment by AlongWY** [comment]
尝试更新一下 ltp?
```python
pip install -U ltp ltp-core ltp-extension -i https://pypi.org/simple # 安装 ltp
```

**Comment by hackerchenzhuo** [comment]
好的我再测试一下

**Comment by hackerchenzhuo** [comment]
好像出现了新bug...空格会被分词
<img width="803" alt="image" src="https://user-images.githubusercontent.com/42081540/189516869-204c7d96-fe44-48fb-9860-f914afd11242.png">

**Comment by hackerchenzhuo** [comment]
新的bug：

> ltp = LTP("LTP/small")
ltp.add_words(words=['[ENT]'])
ltp.pipeline(['[ENT] Info'], tasks=["cws"])

报错：
*** KeyError: 5

**Comment by AlongWY** [comment]
请在更新一次试试

**Comment by hackerchenzhuo** [comment]
这次在几个样本上测试没有报错，但是分词结果中依然有空格：
<img width="296" alt="image" src="https://user-images.githubusercontent.com/42081540/189521719-241530b8-6d22-4159-a95a-fa346da9ff98.png">

**Comment by AlongWY** [comment]
是故意保留空格的，如果不需要可以自行strip一下

**Comment by hackerchenzhuo** [comment]
好的谢谢
请问后续，是否会出相关的参数，来控制是否保留空格呢？

**Comment by AlongWY** [comment]
之后可以加一下
