### ISSUE TITLE
请问在线演示平台使用的是哪个版本啊

### ISSUE THREAD

**Issue by TinaGioro** [HIT-SCIR/ltp#591]

**Comment by TinaGioro** [comment]
如题，我使用3.4版本进行分词结果和在线演示平台不一样，请问在线的使用的是哪个版本呀，如何安装呢

**Comment by AlongWY** [comment]
在线演示用的是 4.2 (small) 的版本，是基于 pytorch 的版本，使用 pip 安装即可
