### ISSUE TITLE
添加add words 之后出现bug

### ISSUE THREAD

**Issue by BigHyf** [HIT-SCIR/ltp#592]
ltp = LTP("LTP/base2")
ltp.add_words(words=['SCSG','IP地址'])
ltp.pipeline(['SCSGIP地址'], tasks=["cws"])

这种情况下报错 KeyError: 4

**Comment by hackerchenzhuo** [comment]
<img width="822" alt="image" src="https://user-images.githubusercontent.com/42081540/190869396-feb2abc2-d16b-44df-b715-8d07f7ab9124.png">

**Comment by AlongWY** [comment]
这是由于 tokenizer 在 tokenize 的时候对 SCSGIP 将 SCSGIP 考虑成一个整体导致的，无法强行拆分。

**Comment by hackerchenzhuo** [comment]
请问这个的原因是什么呢，为什么针对base2，添加了两个words却刚好无法分词

**Comment by AlongWY** [comment]
对于英文来说，tokenizer 会把没有空格的一段英文字母当做一整个单词，非常合理
