### ISSUE TITLE
How do I load the model offline

### ISSUE THREAD

**Issue by klyuhang9** [HIT-SCIR/ltp#596]
Hi, friends, I meet a problem about how to load the model offline.
When I run the code:
`ltp = LTP("LTP/small")`
This process need to connected to the Internet, I want to know where the model was downloaded. I want to download the model first, then tell the model which path to read the downloaded model through parameters, and run the model offline. Can this be achieved? Thanks for your help！

**Comment by AlongWY** [comment]
```bash
git lfs install
git clone https://huggingface.co/LTP/tiny
```

```python
from ltp import LTP
ltp = LTP("path/to/tiny/dir")
```
