### ISSUE TITLE
求在线演示平台ltp版本

### ISSUE THREAD

**Issue by TinaGioro** [HIT-SCIR/ltp#599]
我下载的版本4.2.10，但与在线平台的结果还是有出入，求平台使用的版本

**Comment by yt-liang** [comment]
同求，您知道具体版本号了吗？我还发现好像只能下载最新4.x版本，之前3.x版本的不能使用。

**Comment by AlongWY** [comment]
3.x 版本的使用 pyltp 即可

**Comment by TinaGioro** [comment]
我用的就是4.2.10。后发现这个版本是可用的。平台会自动对输入的句子进行分句后再识别其他语义，在使用的时候先分句再用ltp包结果和平台上就差不多了

**Comment by yt-liang** [comment]
> 我用的就是4.2.10。后发现这个版本是可用的。平台会自动对输入的句子进行分句后再识别其他语义，在使用的时候先分句再用ltp包结果和平台上就差不多了

好的，谢谢您，那我就用4.2.了
