### ISSUE TITLE
LTP文档的一个bug

### ISSUE THREAD

**Issue by LightChen233** [HIT-SCIR/ltp#600]
----源码
from ltp import LTP
ltp = LTP("LTP/base")
words = ltp.pipeline(["他叫汤姆去拿外衣。"], tasks = ["cws"], return_dict=False)

----问题
返回为空的tuple“()”

----一些其他测试
words = ltp.pipeline(["他叫汤姆去拿外衣。"], tasks = ["cws"])
此时words.cws能正确返回

----版本
ltp=4.2.10=pypi_0
ltp-core=0.1.2=pypi_0
ltp-extension=0.1.8=pypi_0

**Comment by AlongWY** [comment]
好的，我确认一下
