### ISSUE TITLE
安装成功调用失败

### ISSUE THREAD

**Issue by mingkin** [HIT-SCIR/ltp#602]
pip install -U ltp ltp-core ltp-extension -i https://pypi.org/simple # 安装 ltp
安装成功
但是导入包时：
from ltp import LTP
报错：
Traceback (most recent call last):
  File "/media/king/d1/conda/py37/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-faf68f5095a3>", line 1, in <module>
    from ltp import LTP
  File "/home/king/software/pycharm-2020.1.1/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'ltp'

**Comment by ppd118** [comment]
我也遇到了这个问题，pip list 内有ltp,ltp-core,ltp-extension但是import报错

**Comment by kkbossa** [comment]
我也是一样的问题，无论是colab还是本地都无法import，检查pip目录下有ltp,ltp-core,ltp-extension

**Comment by kkbossa** [comment]
pip install ltp==4.2.0解决问题

**Comment by AlongWY** [comment]
好的我确认一下

**Comment by ppd118** [comment]
> 

你好，我按照这个安装上能调用了，但是运行官方文档示例代码还是报了错，请问你有遇到这个问题吗？
运行代码
```python
import torch
from ltp import LTP

ltp = LTP("LTP/small")  # 默认加载 Small 模型

# 将模型移动到 GPU 上
if torch.cuda.is_available():
    # ltp.cuda()
    ltp.to("cuda")

output = ltp.pipeline(["他叫汤姆去拿外衣。"], tasks=["cws", "pos", "ner", "srl", "dep", "sdp"])
# 使用字典格式作为返回结果
print(output.cws)  # print(output[0]) / print(output['cws']) # 也可以使用下标访问
print(output.pos)
print(output.sdp)
```
报错信息
```
Traceback (most recent call last):
  File "new_words.py", line 11, in <module>
    output = ltp.pipeline(["他叫汤姆去拿外衣。"], tasks=["cws", "pos", "ner", "srl", "dep", "sdp"])
  File "D:\Program Files\Anaconda3\envs\pytorch_py37\lib\site-packages\ltp\nerual.py", line 29, in wrapper  
    return func(*args, **kwargs)
  File "D:\Program Files\Anaconda3\envs\pytorch_py37\lib\site-packages\ltp\nerual.py", line 169, in pipeline
    output = LTPOutput(**store)
TypeError: __init__() got an unexpected keyword argument 'cws'
```

**Comment by ppd118** [comment]
> pip install ltp==4.2.0解决问题

> 

你好，我按照这个安装上能调用了，但是运行官方文档示例代码还是报了错，请问你有遇到这个问题吗？
运行代码
```python
import torch
from ltp import LTP

ltp = LTP("LTP/small")  # 默认加载 Small 模型

# 将模型移动到 GPU 上
if torch.cuda.is_available():
    # ltp.cuda()
    ltp.to("cuda")

output = ltp.pipeline(["他叫汤姆去拿外衣。"], tasks=["cws", "pos", "ner", "srl", "dep", "sdp"])
# 使用字典格式作为返回结果
print(output.cws)  # print(output[0]) / print(output['cws']) # 也可以使用下标访问
print(output.pos)
print(output.sdp)
```
报错信息
```
Traceback (most recent call last):
  File "new_words.py", line 11, in <module>
    output = ltp.pipeline(["他叫汤姆去拿外衣。"], tasks=["cws", "pos", "ner", "srl", "dep", "sdp"])
  File "D:\Program Files\Anaconda3\envs\pytorch_py37\lib\site-packages\ltp\nerual.py", line 29, in wrapper  
    return func(*args, **kwargs)
  File "D:\Program Files\Anaconda3\envs\pytorch_py37\lib\site-packages\ltp\nerual.py", line 169, in pipeline
    output = LTPOutput(**store)
TypeError: __init__() got an unexpected keyword argument 'cws'
```

**Comment by yizhicheng1** [comment]
> > pip install ltp==4.2.0解决问题
> 
> > 
> 
> 你好，按照这个安装上可以调用我，但是运行官方文档报错了，请问你运行时遇到了这个示例代码吗 ？
> 
> ```python
> import torch
> from ltp import LTP
> 
> ltp = LTP("LTP/small")  # 默认加载 Small 模型
> 
> # 将模型移动到 GPU 上
> if torch.cuda.is_available():
>     # ltp.cuda()
>     ltp.to("cuda")
> 
> output = ltp.pipeline(["他叫汤姆去拿外衣。"], tasks=["cws", "pos", "ner", "srl", "dep", "sdp"])
> # 使用字典格式作为返回结果
> print(output.cws)  # print(output[0]) / print(output['cws']) # 也可以使用下标访问
> print(output.pos)
> print(output.sdp)
> ```
> 
> 报错信息
> 
> ```
> Traceback (most recent call last):
>   File "new_words.py", line 11, in <module>
>     output = ltp.pipeline(["他叫汤姆去拿外衣。"], tasks=["cws", "pos", "ner", "srl", "dep", "sdp"])
>   File "D:\Program Files\Anaconda3\envs\pytorch_py37\lib\site-packages\ltp\nerual.py", line 29, in wrapper  
>     return func(*args, **kwargs)
>   File "D:\Program Files\Anaconda3\envs\pytorch_py37\lib\site-packages\ltp\nerual.py", line 169, in pipeline
>     output = LTPOutput(**store)
> TypeError: __init__() got an unexpected keyword argument 'cws'
> ```
你好，这个问题你解决了吗，我遇到的问题和你一样

**Comment by yizhicheng1** [comment]
我把版本换成pip install ltp==4.2.1就可以跑了

**Comment by AlongWY** [comment]
现在可以安装最新版本 `4.2.11.post1`
使用该命令安装即可 `pip install -U ltp ltp-core ltp-extension -i https://pypi.org/simple # 安装 ltp`
