### ISSUE TITLE
语义角色标注

### ISSUE THREAD

**Issue by yt-liang** [HIT-SCIR/ltp#603]
您好，想请教一下，语义角色标注任务的数据集的格式是什么样的？读论文的时候了解到把角色标注任务看作是依存分析类似，预测每个字作为谓语，其他字作为论元构成的标签，但是有一个问题是，如果一个单词参与到多个角色标注，是如何建模的？例如 A是谓语B C D组成论元，对于B C D ，C又作为谓语B和D分作为论元这种情况。

**Comment by AlongWY** [comment]
可以看此处的[训练样例](https://github.com/HIT-SCIR/ltp/tree/main/python/core/data/srl)
