### ISSUE TITLE
分句方法报错

### ISSUE THREAD

**Issue by pigff250g** [HIT-SCIR/ltp#604]
您好
根据官方文档（http://ltp.ai/docs/quickstart.html）的 “分句” 部分代码，同样的代码显示报错 “'ltp_extension.algorithms.StnSplit' object has no attribute 'sent_split'”

![微信图片_20221028054909](https://user-images.githubusercontent.com/74137580/198404836-0dc11994-ffd7-474e-a821-618dd2435dc2.png)

使用版本：
pip version 20.1.1
python 3.8
LTP 4.2

请问有头绪是哪里的问题吗 感谢指教

**Comment by AlongWY** [comment]
直接 split
