### ISSUE TITLE
实例化的时候报错，是transformers版本问题吗，我是4.17.0

### ISSUE THREAD

**Issue by 2001-SamLiu** [HIT-SCIR/ltp#606]
ImportError: cannot import name 'PaddingStrategy' from 'transformers.utils'

**Comment by AlongWY** [comment]
应该是版本的问题，升级到最新的试一下？

**Comment by clvsit** [comment]
transformers 4.17.0 版本会报错，升级到 4.24 .0 版本后不会报错，其实 4.18.0 版本之后就已经有 PaddingStrategy
![image](https://user-images.githubusercontent.com/12505375/200120654-b4ad34ed-542d-4928-88ee-821d9d076403.png)
