### ISSUE TITLE
请问语义角色标注的时候怎么获取谓词的index

### ISSUE THREAD

**Issue by yyyf-g** [HIT-SCIR/ltp#607]
比如我送进去的句子是“朋友来找我玩的这天恰好大姨也来我家了”
然后srl的结果是：
[[{'predicate': '来', 'arguments': [('A0', '朋友'), ('A1', '找我玩')]},
  {'predicate': '找', 'arguments': [('A0', '朋友'), ('A1', '我玩')]},
  {'predicate': '来',
   'arguments': [('ARGM-TMP', '朋友来找我玩的这天'),
    ('ARGM-ADV', '恰好'),
    ('A0', '大姨'),
    ('ARGM-DIS', '也'),
    ('A1', '我家')]}]]

接下来我想遍历这个句子中的每个词，去查它在srl中有没有对应的结果
但是句子中有两个‘来‘，怎么去拿到它们对应的结果呢
以前的ltp的角色标注结果有index这一项 现在好像没有了是嘛？

**Comment by AlongWY** [comment]
```python
ltp.pipeline(batch,raw_format=True)
```

**Comment by yyyf-g** [comment]
> ```python
> ltp.pipeline(batch,raw_format=True)
> ```

所以是没有办法直接获取index的嘛？因为raw format输出的结果很难看懂QAQ 我似乎得先将raw_format设为true拿到index 再从将raw_format设为false的结果里找

**Comment by AlongWY** [comment]
普通的结果也是就是从 raw_format 中生成的
