### ISSUE TITLE
Rust 报错

### ISSUE THREAD

**Issue by mayii2001** [HIT-SCIR/ltp#610]
thread '<unnamed>' panicked at 'byte index 415 is not a char boundary; it is inside '入' (bytes 414..417) of `​稍微有点`[...]', library\core\src\str\mod.rs:127:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

警告出现之后 占用资源飙升而没有计算进展

**Comment by mayii2001** [comment]
分词前删除空格、和特殊字符（零宽空格）可以解决

**Comment by AlongWY** [comment]
目测是自定义词典导致的错误，最好发一下错误样例，方便复现

**Comment by mayii2001** [comment]
> 目测是自定义词典导致的错误，最好发一下错误样例，方便复现

检查文本发现一个新的特殊字符没删掉，删掉就好了(ˉ▽ˉ；)...
对于爬下来的网络文本还是检查一遍特殊空格（参考https://www.qqxiuzi.cn/zh/space.html）

**Comment by AlongWY** [comment]
嗯嗯
