### ISSUE TITLE
使用 python 版本时，当语料中有中英数字混合的时候，易产生 rust 错误

### ISSUE THREAD

**Issue by njczh** [HIT-SCIR/ltp#612]
使用 python 版本时，当语料中有中英数字混合的时候，易产生 rust 错误

thread '<unnamed>' panicked at 'byte index 6 is not a char boundary; it is inside '抽' (bytes 4..7) of ` 80 抽两五星武器给我吧哥`', rust/ltp/src/hook.rs:82:33

类似于这样的错误。

我也不希望把所有的数字和英文字符去掉，该怎么办呢

**Comment by AlongWY** [comment]
我确认一下

**Comment by AlongWY** [comment]
是不是加了词典呢

**Comment by letiantony** [comment]
加了词典会报错，我这边也遇到了相同的问题，但是很奇怪，单条处理的时候不报错，批量处理的时候就会报错。
