### ISSUE TITLE
最新版ltp windows上初始化很慢

### ISSUE THREAD

**Issue by emmayang1992** [HIT-SCIR/ltp#613]
如图， ltp 4.2.11.post2初始化需要4.57s,  4.1.5.post.2 仅需要0.5s, 加载同样的模型base2为何时间差别这么大呢？ windows上有没有参数可以优化速度呢

![飞书20221122-100135](https://user-images.githubusercontent.com/19280868/203199045-591b36fc-46fe-4085-a16b-e8d96a18a266.jpg)

![2](https://user-images.githubusercontent.com/19280868/203199058-905d77f1-6a94-4194-b68f-894d87615245.jpg)

**Comment by AlongWY** [comment]
可以尝试加入如下参数
```
ltp_new = LTP("LTP/base2", local_files_only=True)
```

**Comment by emmayang1992** [comment]
好滴 感谢大佬
