### ISSUE TITLE
LTP4 有根据分词结果和词性标注结果进行句法分析的方法吗？ 

### ISSUE THREAD

**Issue by emmayang1992** [HIT-SCIR/ltp#615]
RT
类似于之前的pyltp 中的parser 可以进行parser.parser(分词结果,词性标注结果)的计算

**Comment by AlongWY** [comment]
可以仅仅进行句法分析，不需要词性标注结果

**Comment by emmayang1992** [comment]
> 以仅仅进行句法分析，不需要词性标注结果

不不 我这边是在分词和词性标注的结果上，对部分分词结果进行了短语合并，同时对应修改了合并后短语的词性。 
因此想在 进行短语合并后的 分词结果&词性上，进行句法分析。 
pyltp是可以输入分词结果和词性进行句法分析的， ltp4有对应的方法嘛？

**Comment by AlongWY** [comment]
暂时没有，现在是去除了依赖，尽量做端到端了

**Comment by geasyheart** [comment]
即使支持，效果未必能达到你期望的效果。
你可以自行训练。

**Comment by emmayang1992** [comment]
好滴 感谢大佬们
