### ISSUE TITLE
请问支持传统的分词么，不用模型的那种

### ISSUE THREAD

**Issue by wqh17101** [HIT-SCIR/ltp#616]

**Comment by AlongWY** [comment]
传统分词也是需要模型的吧

**Comment by wqh17101** [comment]
@AlongWY 指jieba那种基于分词表的

**Comment by wqh17101** [comment]
因为我们可能没有GPU，模型的话会不会很慢

**Comment by geasyheart** [comment]
cpu也很快

**Comment by AlongWY** [comment]
使用 "LTP/legacy" 模型？

**Comment by wqh17101** [comment]
![image](https://user-images.githubusercontent.com/26429138/204544350-e8d070b6-005c-4377-b485-24cba9c33d17.png)

**Comment by wqh17101** [comment]
@AlongWY 看看这个问题

**Comment by AlongWY** [comment]
可能是网络问题，可以试一下把[模型](https://huggingface.co/LTP)下载下来，然后本地加载
