### ISSUE TITLE
使用Legacy 模型报错

### ISSUE THREAD

**Issue by HE-2022** [HIT-SCIR/ltp#617]
使用ltp = LTP("LTP/legacy")分词和词性标注，文件大了就出现下方提示，自动结束进程
memory allocation of memory allocation of memory allocation of 6464 bytes failed
 bytes failed
memory allocation of 64memory allocation of 64

Restarting kernel...

**Comment by AlongWY** [comment]
拆一下文件？

**Comment by HE-2022** [comment]
因为处理的文本数量比较多，现在已经差分成很多小文件了。还有其它办法解决吗？

**Comment by HE-2022** [comment]
> 拆一下文件？
你好，因为处理的文本数量比较多，现在已经差分成很多小文件了。还有其它办法解决吗？

**Comment by AlongWY** [comment]
拆一下句子？
