### ISSUE TITLE
AttributeError: 'LTP' object has no attribute 'seg'

### ISSUE THREAD

**Issue by godspirit00** [HIT-SCIR/ltp#619]
您好，我在尝试命名实体识别，但是在`seg, hidden = ltp.seg(["他叫汤姆去拿外衣。"])`这步，提示错误`AttributeError: 'LTP' object has no attribute 'seg'`，我是按照README里的方式`pip install -U ltp ltp-core ltp-extension`安装的。
请问应该怎么办？
谢谢您。

**Comment by todochenxi** [comment]
我也遇到了，重装好几回，还是报错

**Comment by AlongWY** [comment]
```python
output = ltp.pipeline(["他叫汤姆去拿外衣。"], tasks=["cws", "pos", "ner", "srl", "dep", "sdp"])
```

**Comment by godspirit00** [comment]
@AlongWY 感谢回答~文档可能也需要更新一下~
