### ISSUE TITLE
ImportError: cannot import name 'PaddingStrategy'

### ISSUE THREAD

**Issue by MengfeiShen** [HIT-SCIR/ltp#620]
您好，我在 from ltp import LTP这一步，就报错了，显示import错误。

ImportError: cannot import name 'PaddingStrategy' from 'transformers.utils' (/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/transformers/utils/__init__.py)

我是按照README里的方式pip install -U ltp ltp-core ltp-extension安装的。
请问应该怎么办？
谢谢您。
![截屏2022-12-10 17 39 08](https://user-images.githubusercontent.com/73157043/206844120-7a2eed60-942d-4930-b3e0-b77119f06fa5.png)

**Comment by AlongWY** [comment]
升级一下 transformers 试一下
