### ISSUE TITLE
ltp在CPU和GPU下的分词结果不同

### ISSUE THREAD

**Issue by MRY-py** [HIT-SCIR/ltp#625]
![1672898514778](https://user-images.githubusercontent.com/99491273/210712907-097f1bd4-84e9-4743-adb7-94af1adcdfc6.png)
![1672898472194](https://user-images.githubusercontent.com/99491273/210712917-df5668bd-6304-41ef-aa53-5a1fc8b95e85.png)

**Comment by AlongWY** [comment]
没有复现成功

**Comment by MRY-py** [comment]
> 没有复现成功

这个对pytorch和python的版本有要求吗，我的torch==1.7.0,python==3.7.15。或者这个会对GCC编译版本有要求吗，我的GCC==11.2.0,。之前在其他任务中也出现过gpu和cpu结果不同的情况，当时是因为gcc版本不兼容。

**Comment by AlongWY** [comment]
目前来说，应该不需要编译器，最低需求是
+ `python >= 3.7`
+ `torch >= 1.6.0`
+ `transformers >= 4.0`
