### ISSUE TITLE
ltp_server这个功能是不是去掉了呀，没有这个server.py文件呢

### ISSUE THREAD

**Issue by CoinCheung** [HIT-SCIR/ltp#628]
麻烦更新一下文档?

**Comment by geasyheart** [comment]
https://github.com/HIT-SCIR/ltp/blob/master/tools/server.py
https://github.com/HIT-SCIR/ltp/tree/3.X/src/server

**Comment by CoinCheung** [comment]
好的，看到了，建议更新一下这部分的文档哈，默认打开的是main分枝，里面让运行python utils/server.py，然后main里面没有这个。还有wiki里面的文档好像也没更新，里面说可以用cmake自己编译，main分枝里面也没有CMakeList.txt
