### ISSUE TITLE
为什么在LTP的模型引用介绍参数中会有两个base1？

### ISSUE THREAD

**Issue by RyanBin0126** [HIT-SCIR/ltp#643]
Parameters:
                pretrained_model_name_or_path (`str` or `os.PathLike`):
                    Can be either:
                        - A string, the `model id` of a pretrained model
                          hosted inside a model repo on huggingface.co.
                          Valid model ids are [`LTP/tiny`, `LTP/small`,
                          `LTP/base`, `LTP/base1`, `**LTP/base1**`, `LTP/legacy`
                          ], the legacy model only support cws, pos and ner,
                          but more fast.

**Comment by AlongWY** [comment]
写错了，应该是 base2
