### ISSUE TITLE
ltp = LTP( "LTP/base2")报错

### ISSUE THREAD

**Issue by liyanfu520** [HIT-SCIR/ltp#649]
运行ltp = LTP( "LTP/base2")
有时候正常，
有时候会报错  
发生异常: ConnectionError
('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
是什么原因

**Comment by AlongWY** [comment]
应该是 hf 被墙了，可以试试本地载入
