### ISSUE TITLE
最近几天怎么模型都下载不了？手动下载模型的连接好像也缺失了，到底怎么回事？

### ISSUE THREAD

**Issue by longgongdh** [HIT-SCIR/ltp#650]
ltp = LTP("LTP/base2")

raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

手动下载：
YAML Metadata Warning: empty or missing yaml metadata in repo card (https://huggingface.co/docs/hub/model-cards#model-card-metadata)

**Comment by AlongWY** [comment]
应该是 hf 被墙了
增补了本地载入模型的文档
