### ISSUE TITLE
更新到4.2.0后，文档太过简单了，太粗糙，太不负责任了!

### ISSUE THREAD

**Issue by longgongdh** [HIT-SCIR/ltp#651]
太不负责任了！既然开源和公开，就应该提供详细的文档。包括安装时，不应该一句 pip install 就结束。应该把详细的依赖包介绍一下，至少让新人预先知道要安装torch，torch文件这么大，如果只执行pip install ltp ，很容易报错，要告知用户可以镜像源安装。另外，模型下载链接经常失效。另外更新到4.2.0后，结构发生了很大的调整，很多和4.1.5不一样。例如：手动模型下载后，如何配置，LTP()的属性和方法都有更新，都需要有详细的文档说明。而不是不负责任的，给了一个最简单的文档！

**Comment by AlongWY** [comment]
增补了本地载入模型的文档
