### ISSUE TITLE
如何将模型改为本地路径

### ISSUE THREAD

**Issue by liyanfu520** [HIT-SCIR/ltp#652]
模型文件中有个config.json文件，里面的内容是这样的
{"url": "http://39.96.43.154/ltp/v3/base2.tgz", "etag": "\"6039bfcc-246c5320\""}，url是一个模型的链接，那么我把这个模型下载到本地了，如何修改这个config.json文件，让它指向我本地的模型路径呢？

**Comment by AlongWY** [comment]
增补了本地载入模型的文档
