### ISSUE TITLE
LTP的API与数据结果要保持稳定性，否则会造成严重的应用问题！

### ISSUE THREAD

**Issue by longgongdh** [HIT-SCIR/ltp#654]
自从升级到4.2.0之后，ltp的API，不仅变了，从原来的.seg方法，变更成了pipeline的方法，这倒不要紧，但是输出的结果，从原来的三元组列表，变成了全新的格式：例如语法依存的结果为：[{'head': [2, 0, 2, 5, 2, 5, 2], 'label': ['SBV', 'HED', 'DBL', 'LAD', 'VOB', 'VOB', 'WP']}]，和原来的完全不一样了！这直接导致了我们基于LTP4.1.5的应用，代码完全报废，而且都要重写，这对于LTP的应用发展来说，是个巨大的问题。无论你核心代码怎样，作为LTP的API代码如何升级，但API和输出结果应该要始终的一直的保持一致。而不能随意调整输出格式！输出结果变来变去，那么下游应用直接奔溃！请LTP的研发大牛们，一定要非常重视这个问题！

**Comment by longgongdh** [comment]
既然4.2.0的输出已经改了，就改了，希望4.2.0以后版本API接口输出不要再修改了！

**Comment by AlongWY** [comment]
格式的变动当时主要是考虑效率，现在最大程度减少了LTP内部的处理，之后基本不会再进行如此大的变动了

**Comment by xxllp** [comment]
确实是个坑，感觉api就一直在变动~
