### ISSUE TITLE
有必要再加上ltp.to("cuda")吗

### ISSUE THREAD

**Issue by liyanfu520** [HIT-SCIR/ltp#655]
加载模型的时候，看到初始化里面包含了判断是否有GPU
![image](https://github.com/HIT-SCIR/ltp/assets/40288288/9ee74554-f4a1-4944-942c-fcf046673706)
在文档里面也看到有类似的判断，那这个是有必要的吗
![image](https://github.com/HIT-SCIR/ltp/assets/40288288/64fbf1f0-025c-46e2-b6b8-0acc5b9b132d)

**Comment by AlongWY** [comment]
新的版本没有做自动检测处理，如果要用 cuda 还是需要的
