### ISSUE TITLE
预训练模型加载不了，下载到本地也显示出错

### ISSUE THREAD

**Issue by ShirleyLi123** [HIT-SCIR/ltp#669]
在ltp = LTP("/home/******/LTP/Module/LTP/base") 处报错显示
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
没搞明白 我整个模型都下下来了，包括.json，.txt等。为什么一直提示有错，这里说json文件的问题我也重新下载过，还是无法解决。求求各路大神帮忙

**Comment by ShirleyLi123** [comment]
上面问题已解决，大家注意下载的几个模型，有json文件是空的必须加{}，不然必报错

**Comment by ZihaoZheng98** [comment]
> 上面问题已解决，大家注意下载的几个模型，有json文件是空的必须加{}，不然必报错

你好，我也遇到了这个问题，请问你说的有json文件是空的必须加{}是什么意思呢？

**Comment by ZihaoZheng98** [comment]
> > 上面问题已解决，大家注意下载的几个模型，有json文件是空的必须加{}，不然必报错
> 
> 你好，我也遇到了这个问题，请问你说的有json文件是空的必须加{}是什么意思呢？

@ShirleyLi123
