### ISSUE TITLE
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

### ISSUE THREAD

**Issue by pioneerRick** [HIT-SCIR/ltp#686]
thread '<unnamed>' panicked at 'byte index 3 is not a char boundary; it is inside '苯' (bytes 1..4) of ` 苯甲醛广泛用于医药、农药、染料、香料等行业.为了寻找产率高、成本低的新合成方法,人们进行了广泛的研究.本文用Grignard试剂与苯并咪唑盐合成苯甲醛.合成路线如下:
`', rust\ltp\src\hook.rs:82:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Process finished with exit code -1073740791 (0xC0000409)

不知道为啥,查了一下说是因为 set RUST_BACKTRACE=1

**Comment by pioneerRick** [comment]
这样设置还是报这个错误,但是是不同的地方

**Comment by pioneerRick** [comment]
破案了数据不干净,每个句子前面带有一个空格就报这个错,删除空格就没有事了

**Comment by xuJ14** [comment]
same question

**Comment by brownfoxsir** [comment]
我也遇到了类似的问题：
```
thread '<unnamed>' panicked at 'byte index 43 is not a char boundary; it is inside '，' (bytes 42..45) of `��辛泰“联合广辽爵匣贵患颍，�,-A巨詈＇芩哭会社师事`', rust/ltp/src/hook.rs:82:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
我的临时解决办法是：
- 1 ```��辛泰“联合广辽爵匣贵患颍，�,-A巨詈＇芩哭会社师事```给这个字符串前面加个```'```
- 2 ``` re.sub('�','',"��辛泰“联合广辽爵匣贵患颍，�,-A巨詈＇芩哭会社师事")```

底层库能直接给个异常能被捕获就好了，这种直接panic整个进程都挂了。。。。

**Comment by AlongWY** [comment]
好的，我会修正一下，抛出异常

**Comment by brownfoxsir** [comment]
> 好的，我会修正一下，抛出异常，最好能给一个样例

先感谢一波大佬，静等更新~

**Comment by AlongWY** [comment]
该问题应该已经解决，修改成为了抛出异常的模式

**Comment by brownfoxsir** [comment]
> 该问题应该已经解决，修改成为了抛出异常的模式，升级 ltp-extension 即可

感谢大佬(🙏ˊᗜˋ*)。我周日回去测试一下。谢谢！！！！！！！！

**Comment by brownfoxsir** [comment]
@AlongWY 经过测试，这个异常已经可以正常捕获了，感谢大佬

**Comment by wellhowtosay** [comment]
> 该问题应该已经解决，修改成为了抛出异常的模式，升级 ltp-extension 即可
Python内还是cache不住呀

**Comment by wellhowtosay** [comment]
> 该问题应该已经解决，修改成为了抛出异常的模式，升级 ltp-extension 即可

Python内这个异常还是except不住呀， ltp-extension已经是0.1.13

**Comment by brownfoxsir** [comment]
> > 该问题应该已经解决，修改成为了抛出异常的模式，升级 ltp-extension 即可
> 
> Python内这个异常还是except不住呀， ltp-extension已经是0.1.13

我提供的用例我试了下，是可以捕获的 @wellhowtosay ,你抛出异常的是啥字符？

**Comment by wellhowtosay** [comment]
> > > 该问题应该已经解决，修改成为了抛出异常的模式，升级 ltp-extension 即可
> > 
> > 
> > Python内这个异常还是except不住呀， ltp-extension已经是0.1.13
> 
> 我提供的用例我试了下，是可以捕获的 @wellhowtosay ,你抛出异常的是啥字符？

是\u00a0 这个字符

**Comment by wellhowtosay** [comment]
> 该问题应该已经解决，修改成为了抛出异常的模式，升级 ltp-extension 即可
'\u{a0}' 这个字符在
panicked at rust/ltp/src/hook.rs:139:34:
这个地方引起了错误

**Comment by wellhowtosay** [comment]
> 该问题应该已经解决，修改成为了抛出异常的模式，升级 ltp-extension 即可

'\u{a0}' 这个字符在
panicked at rust/ltp/src/hook.rs:139:34:
这个地方引起了错误
