### ISSUE TITLE
修改自定义词性标注词典相关文档

### ISSUE THREAD

**Issue by carfly** [HIT-SCIR/ltp#69]

**Comment by Oneplus** [comment]
@ruoshui1126 现在线上系统可能还没有使用词性词典，所以postag还会把标点tag成动词。需要改一下ltp_server的实现，使得词典也能load进来。

**Comment by Oneplus** [comment]
计划的实现方式是：ltp-server从config file方式转为command line option的方式。在command line中加入词性词典的路径。
