### ISSUE TITLE
srl.Model文件标签说明

### ISSUE THREAD

**Issue by jackycaf** [HIT-SCIR/ltp#93]
ltp-cloud技术支持：
您好，非常感谢贵校提供的ltp-cloud以及相关源代码，我们正在虚心学习中。
有一些问题不知道请教哪位老师。现将问题发布如下：
语义角色标注模块中：
srl.Model文件中带有问号的类别标识的含义请您能否给出说明：

NULL  非角色
A0  施事，动作的发出者
A1  受事，动作接受者
A2 动作的间接作用对象
A3  直接目的、目标等
A4  直接工具、方法等
C-A0 ?
C-A1  ? 
C-A2  ?
C-A3  ? 
C-ARGM-TMP ? 
C-ARGM-DIS  ? 
C-C-A0 ? 
DIS  话语标记
LOC locative ( 地点 )
ADV Adverbials（附加的，默认标记）
TMP  temporal ( 时间 )
EXT  extent ( 范围 )
FRQ  frequency ( 频率 )
DGR  degree ( 程度 )
MNR manner ( 方式 )
TPC topic ( 主题 )
CND condition ( 条件 )
DIR direction ( 方向 )
PRP Purpose or Reason（目的或原因）
CRD coordinated arguments ( 并列参数 )
PRD predicate ( 谓语动词 )
BNF ?
ASP ? 
VOC ? 
ARGM 修饰成分
QTY  数量
PN ? 
T ? 
PSE  possessee ( 被持有 )
PSR  possessor ( 持有者 )

**Comment by carfly** [comment]
可以参考这篇文章：
Labeling Chinese Predicates with Semantic Roles   
Nianwen Xue
Computational Linguistics June 2008, Vol. 34, No. 2: 225–255.

http://www.mitpressjournals.org/doi/pdfplus/10.1162/coli.2008.34.2.225

**Comment by jackycaf** [comment]
车老师，


有关方面的资料阅读中，问题已经基本解决，很感谢您的帮助！


此致


郑先生






在 2015-01-26 11:08:09，"Wanxiang Che" <notifications@github.com> 写道：


可以参考这篇文章：
Labeling Chinese Predicates with Semantic Roles

Nianwen Xue
Computational Linguistics June 2008, Vol. 34, No. 2: 225–255.

http://www.mitpressjournals.org/doi/pdfplus/10.1162/coli.2008.34.2.225
