### ISSUE TITLE
编译成功后ltp_server 无法运行

### ISSUE THREAD

**Issue by suood** [HIT-SCIR/ltp#95]
下载了 ltp-master.zip 后unzip。
在ltp-master 目录下执行./configure  执行完成后 执行 make 。

到 bin目录下执行 ./ltp_server 。 报出错误如下

[ERROR] 2015/02/27 11:27:01 /usr/local/bin/ltp-master/src/__ltp_dll/Ltp.cpp: line 54: ReadConfFile(): Failed to open config file "conf/ltp.cnf"

ltp_master 目录下执行 ./bin/ltp_server 报错如下
[TRACE] 2015/02/27 11:42:00 Loading segmentor model from "ltp_data/cws.model" ...
[ERROR] 2015/02/27 11:42:00 /usr/local/bin/ltp-master/src/__ltp_dll/LTPResource.cpp: line 58: LoadSegmentorResource(): Failed to load segmentor model
[ERROR] 2015/02/27 11:42:00 /usr/local/bin/ltp-master/src/__ltp_dll/Ltp.cpp: line 87: ReadConfFile(): in LTP::wordseg, failed to load segmentor resource
请问 我到底该如何才能运行 ltp_server

**Comment by carfly** [comment]
第一个问题是配置文件 conf/ltp.cnf 没有放到正确位置。

第二个问题是模型文件没有下载或在没有放到正确位置。

**Comment by suood** [comment]
所有的操作都是使用说明文档上做的。 您说的模型文件下载文档中并没有提到过。。。

**Comment by carfly** [comment]
https://github.com/HIT-SCIR/ltp 上有关于模型下载的地址。

**Comment by suood** [comment]
感谢您的回复，问题已经解决了

**Comment by xohozu** [comment]
@suood 请问你是怎么解决的呢？我检测了配置文件和模型目录，依然出现此问题。并且尝试了几个版本，依旧如此。
```
LoadSegmentorResource(): Failed to load segmentor model
ReadConfFile(): in LTP::wordseg, failed to load segmentor resource
```

**Comment by Oneplus** [comment]
@xohozu 首先推荐使用3.3.0。然后请使用release中的ltp3.3.0（以及模型3.3.0）而非github master，因为我们在3.3.1里面更新了一个分词模型签名的bug，导致3.3.0的模型不能使用了。另3.3.0 ltp_test中有一个postagger-model的bug，具体的规避方法是将pos.model放到ltp_data下，并且不要在ltp_test中指定`postagger-model`这个选项
