### ISSUE TITLE
请问在ltp_server中如何配置使用用户自定义辞典

### ISSUE THREAD

**Issue by m00nlight** [HIT-SCIR/ltp#98]
rt

**Comment by carfly** [comment]
ltp的分词模块虽然支持添加词典的功能，但是在ltp_server这部分代码逻辑中，是不支持添加词典的。要实现添加词典也很容易，具体在src/__dll_ltp/LTPResource.cpp
中 int LTPResource::LoadSegmentorResource
中这一句话segmentor_create_segmentor(model_file);
改为segmentor_create_segmentor(model_file，“词典路径"); 即可。

**Comment by Oneplus** [comment]
新版(3.3.0)的ltp_server可以通过`--segmentor-lexicon`这个参数支持外部词典。具体参考http://ltp.readthedocs.org/zh_CN/latest/ltpserver.html

**Comment by m00nlight** [comment]
@Oneplus 谢谢
